import { NextResponse } from "next/server";
import { runAutoGenerateDraftsAgent } from "@/lib/ai-agents/auto-generate-drafts-agent";
import { requireInternalAiAgentAuth } from "@/lib/ai-agents/internal-auth";

export const dynamic = "force-dynamic";

export async function POST(request: Request) {
  const auth = requireInternalAiAgentAuth(request);
  if (!auth.ok) return auth.response;

  try {
    const result = await runAutoGenerateDraftsAgent();
    return NextResponse.json(result);
  } catch (error) {
    return NextResponse.json(
      {
        ok: false,
        error:
          error instanceof Error
            ? error.message
            : "Auto-generate drafts failed.",
      },
      { status: 500 }
    );
  }
}
