import { runAutoGenerateDraftsAgent } from "@/lib/ai-agents/auto-generate-drafts-agent";
import { runAutoPublishGeneratedPagesAgent } from "@/lib/ai-agents/auto-publish-generated-pages-agent";
import { runBigQueryTrendsIngestAgent } from "@/lib/ai-agents/bigquery-trends-ingest-agent";
import { runGscUrlIssueAuditAgent } from "@/lib/ai-agents/gsc-url-issue-audit-agent";
import { runInternalSeoExpansionAgent } from "@/lib/ai-agents/internal-seo-expansion-agent";
import { runSearchConsoleIngestionAgent } from "@/lib/ai-agents/search-console-ingestion-agent";
import { runSeoOpportunityAgent } from "@/lib/ai-agents/seo-opportunity-agent";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { getMarketBySlug, getMarketUrlPath, getNearbyMarkets } from "@/lib/geo";
import { categories, getSubcategoryBySlug } from "@/lib/services";
import { getIndexableServiceIntents } from "@/lib/seo/intents/registry";
import {
  getCampaignCategoryBoost,
  getCampaignGeoBoost,
} from "@/lib/seo/campaigns";

type SeoOpportunityRow = {
  id: string;
  country_code: string;
  market_slug: string | null;
  category_slug: string | null;
  subcategory_slug: string | null;
  intent_slug: string | null;
  opportunity_type: string;
  title: string;
  target_url: string | null;
  search_query: string | null;
  priority_score: number | null;
  status: string;
  recommendation: string;
  proposed_action: Record<string, unknown> | null;
};

type GeneratedPageRow = {
  id: string;
  target_url: string;
  status: string;
  quality_status: string | null;
};

type OrchestratorReason = {
  stage: string;
  status: "completed" | "skipped" | "failed";
  message: string;
  metadata?: Record<string, unknown>;
};

type OpportunityScoreInput = {
  impressions?: number;
  ctr?: number;
  intentSlug?: string | null;
  countryCode?: string | null;
  marketSlug?: string | null;
  categorySlug?: string | null;
  subcategorySlug?: string | null;
  qualityScore?: number | null;
  internalLinksCount?: number;
  duplicationRisk?: number;
};

const SERVICE_ALIASES: Record<string, string> = {
  "leak-repair": "leak-detection-repair",
  "water-leak-repair": "leak-detection-repair",
  "pipe-leak-repair": "pipe-repair-replacement",
  "tv-mounting": "tv-mounting-shelves",
  "television-mounting": "tv-mounting-shelves",
  "ac-repair": "air-conditioning-repair",
  "air-conditioner-repair": "air-conditioning-repair",
  "yard-cleanup": "yard-clean-up",
  "junk-hauling": "junk-removal",
};

const INTENT_ALIASES: Record<string, string> = {
  cost: "price",
  pricing: "price",
  prices: "price",
  "24-7": "24-hour",
  urgent: "emergency",
  "nearby": "near-me",
};

const SERVICE_PRIORITY: Record<string, number> = {
  plumbing: 10,
  electrical: 10,
  roofing: 9,
  hvac: 9,
  handyman: 8,
  cleaning: 8,
  "appliance-repair-installation": 9,
};

const EMERGENCY_INTENTS = new Set(["emergency", "24-hour", "same-day"]);

export async function runSeoGrowthOrchestrator() {
  const admin = createSupabaseAdminClient();
  const startedAt = Date.now();
  const reasons: OrchestratorReason[] = [];

  const { data: run, error: runError } = await admin
    .from("seo_growth_orchestration_runs")
    .insert({
      status: "running",
      metadata: {
        version: 1,
        strategy: "ai_first_geo_service_intent_growth",
      },
    })
    .select("id")
    .single();

  if (runError || !run) {
    throw new Error(runError?.message ?? "Unable to create SEO growth run.");
  }

  try {
    await runStage("search_console_ingest", reasons, () =>
      runSearchConsoleIngestionAgent()
    );
    await runStage("gsc_url_issue_audit", reasons, () =>
      runGscUrlIssueAuditAgent()
    );
    await runStage("bigquery_trends_ingest", reasons, () =>
      runBigQueryTrendsIngestAgent()
    );
    await runStage("trend_opportunity_agent", reasons, () =>
      runSeoOpportunityAgent()
    );
    await runStage("internal_seo_expansion", reasons, () =>
      runInternalSeoExpansionAgent()
    );

    const opportunitySummary = await prioritizeAndDedupeOpportunities();

    const draftResult = await runStage("auto_generate_drafts", reasons, () =>
      runAutoGenerateDraftsAgent()
    );

    const sitemapAwareness = await applySitemapAwareness();

    const publishResult = await runStage("auto_publish_generated_pages", reasons, () =>
      runAutoPublishGeneratedPagesAgent()
    );

    const durationMs = Date.now() - startedAt;
    const draftsCreated = getNumber(draftResult, "generatedCount");
    const pagesPublished = getNumber(publishResult, "publishedCount");
    const pagesRejected = getNumber(publishResult, "rejectedCount");
    const pagesReviewed = getNumber(publishResult, "reviewedCount");

    await admin
      .from("seo_growth_orchestration_runs")
      .update({
        status: "completed",
        finished_at: new Date().toISOString(),
        duration_ms: durationMs,
        opportunities_discovered: opportunitySummary.total,
        opportunities_prioritized: opportunitySummary.prioritized,
        opportunities_deduplicated: opportunitySummary.deduplicated,
        drafts_created: draftsCreated,
        pages_reviewed: pagesReviewed,
        pages_rejected: pagesRejected,
        pages_published: pagesPublished,
        reasons,
        metadata: {
          sitemapAwareness,
          opportunitySummary,
        },
        updated_at: new Date().toISOString(),
      })
      .eq("id", run.id);

    return {
      ok: true,
      runId: run.id,
      durationMs,
      opportunities: opportunitySummary,
      draftsCreated,
      pagesReviewed,
      pagesRejected,
      pagesPublished,
      reasons,
    };
  } catch (error) {
    const durationMs = Date.now() - startedAt;
    const message = error instanceof Error ? error.message : "Unknown error";

    reasons.push({
      stage: "orchestrator",
      status: "failed",
      message,
    });

    await admin
      .from("seo_growth_orchestration_runs")
      .update({
        status: "failed",
        finished_at: new Date().toISOString(),
        duration_ms: durationMs,
        reasons,
        metadata: {
          error: message,
        },
        updated_at: new Date().toISOString(),
      })
      .eq("id", run.id);

    throw error;
  }
}

async function runStage<T>(
  stage: string,
  reasons: OrchestratorReason[],
  fn: () => Promise<T>
) {
  try {
    const result = await fn();

    reasons.push({
      stage,
      status: "completed",
      message: `${stage} completed.`,
      metadata: toMetadata(result),
    });

    return result;
  } catch (error) {
    const message = error instanceof Error ? error.message : "Unknown error";

    reasons.push({
      stage,
      status: message.includes("Missing") ? "skipped" : "failed",
      message,
    });

    return null;
  }
}

async function prioritizeAndDedupeOpportunities() {
  const admin = createSupabaseAdminClient();

  const { data, error } = await admin
    .from("ai_seo_opportunities")
    .select(
      "id, country_code, market_slug, category_slug, subcategory_slug, intent_slug, opportunity_type, title, target_url, search_query, priority_score, status, recommendation, proposed_action"
    )
    .in("status", ["new", "approved"])
    .order("priority_score", { ascending: false })
    .limit(500);

  if (error) {
    throw new Error(error.message);
  }

  const opportunities = (data ?? []) as SeoOpportunityRow[];
  const canonicalMap = new Map<string, SeoOpportunityRow>();
  const deduplicatedIds: string[] = [];
  let prioritized = 0;

  for (const opportunity of opportunities) {
    const canonicalTarget = normalizeCanonicalTarget(opportunity);
    const duplicationRisk = canonicalMap.has(canonicalTarget) ? 90 : 0;
    const score = scoreSeoOpportunity({
      impressions: getMetadataNumber(opportunity, "impressions"),
      ctr: getMetadataNumber(opportunity, "ctr"),
      intentSlug: opportunity.intent_slug,
      countryCode: opportunity.country_code,
      marketSlug: opportunity.market_slug,
      categorySlug: opportunity.category_slug,
      subcategorySlug: opportunity.subcategory_slug,
      qualityScore: getMetadataNumber(opportunity, "qualityScore"),
      internalLinksCount: getMetadataNumber(opportunity, "internalLinksCount"),
      duplicationRisk,
    });

    const existing = canonicalMap.get(canonicalTarget);

    if (existing && (existing.priority_score ?? 0) >= score) {
      deduplicatedIds.push(opportunity.id);
      continue;
    }

    if (existing) {
      deduplicatedIds.push(existing.id);
    }

    canonicalMap.set(canonicalTarget, {
      ...opportunity,
      priority_score: score,
      target_url: canonicalTarget,
    });

    const proposedAction = {
      ...(opportunity.proposed_action ?? {}),
      canonicalTarget,
      normalizedAt: new Date().toISOString(),
      scoreBreakdown: getScoreBreakdown(opportunity, score, duplicationRisk),
      internalLinkRecommendations: buildAutonomousInternalLinks(opportunity),
      sitemap: {
        includedWhenPublished: true,
        sitemapPath: "/sitemaps/generated-pages.xml",
      },
    };

    const { error: updateError } = await admin
      .from("ai_seo_opportunities")
      .update({
        target_url: canonicalTarget,
        priority_score: score,
        proposed_action: proposedAction,
        updated_at: new Date().toISOString(),
      })
      .eq("id", opportunity.id);

    if (updateError) {
      throw new Error(updateError.message);
    }

    prioritized += 1;
  }

  if (deduplicatedIds.length > 0) {
    const { error: duplicateError } = await admin
      .from("ai_seo_opportunities")
      .update({
        status: "duplicate",
        updated_at: new Date().toISOString(),
      })
      .in("id", deduplicatedIds);

    if (duplicateError) {
      throw new Error(duplicateError.message);
    }
  }

  return {
    total: opportunities.length,
    prioritized,
    deduplicated: deduplicatedIds.length,
  };
}

export function scoreSeoOpportunity(input: OpportunityScoreInput) {
  const impressionScore = Math.min(Math.round((input.impressions ?? 0) / 20), 20);
  const ctrPenalty = input.ctr !== undefined && input.ctr < 0.02 ? 10 : 0;
  const intentScore = getIntentScore(input.intentSlug);
  const geoScore = getGeoScore(input.countryCode, input.marketSlug);
  const serviceScore = SERVICE_PRIORITY[input.categorySlug ?? ""] ?? 5;
  const campaignCategoryScore = getCampaignCategoryBoost(input.categorySlug);
  const campaignGeoScore = getCampaignGeoBoost(
    input.marketSlug ? getMarketBySlug(input.marketSlug) : null
  );
  const emergencyScore = EMERGENCY_INTENTS.has(input.intentSlug ?? "") ? 10 : 0;
  const qualityGapScore =
    input.qualityScore === undefined || input.qualityScore === null
      ? 6
      : Math.max(0, Math.round((80 - input.qualityScore) / 4));
  const linkDepthScore =
    input.internalLinksCount === undefined
      ? 5
      : Math.max(0, 10 - input.internalLinksCount);
  const duplicationPenalty = Math.round((input.duplicationRisk ?? 0) / 5);

  return Math.max(
    1,
    Math.min(
      100,
      35 +
        impressionScore +
        ctrPenalty +
        intentScore +
        geoScore +
        serviceScore +
        campaignCategoryScore +
        campaignGeoScore +
        emergencyScore +
        qualityGapScore +
        linkDepthScore -
        duplicationPenalty
    )
  );
}

export function normalizeCanonicalTarget(opportunity: SeoOpportunityRow) {
  const rawTarget =
    opportunity.target_url ??
    buildTargetFromOpportunity(opportunity) ??
    `/${opportunity.country_code}`;

  const normalizedParts = rawTarget
    .split("/")
    .filter(Boolean)
    .map((part) => {
      const clean = part.toLowerCase().replace(/_/g, "-");
      return SERVICE_ALIASES[clean] ?? INTENT_ALIASES[clean] ?? clean;
    });

  return `/${normalizedParts.join("/")}`;
}

export function buildAutonomousInternalLinks(
  opportunity: Pick<
    SeoOpportunityRow,
    "market_slug" | "category_slug" | "subcategory_slug" | "intent_slug" | "target_url"
  >
) {
  const links: Array<{ label: string; href: string; reason: string }> = [
    {
      label: "Post a service request",
      href: "/book",
      reason: "Marketplace conversion path",
    },
    {
      label: "Browse open requests",
      href: "/requests",
      reason: "Marketplace request discovery",
    },
  ];

  const market = opportunity.market_slug
    ? getMarketBySlug(opportunity.market_slug)
    : null;
  const category = opportunity.category_slug
    ? categories[opportunity.category_slug]
    : null;
  const subcategory = opportunity.subcategory_slug
    ? getSubcategoryBySlug(opportunity.subcategory_slug)
    : null;

  if (market) {
    const marketPath = getMarketUrlPath(market);

    links.push({
      label: `Home services in ${market.city}`,
      href: marketPath,
      reason: "Nearby city hub",
    });

    if (category) {
      links.push({
        label: `${category.shortTitle} in ${market.city}`,
        href: `${marketPath}/${category.slug}`,
        reason: "Parent category",
      });
    }

    if (subcategory) {
      links.push({
        label: `${subcategory.shortTitle} in ${market.city}`,
        href: `${marketPath}/${subcategory.parentSlug}/${subcategory.slug}`,
        reason: "Related service",
      });
    }

    for (const nearby of getNearbyMarkets(market.slug).slice(0, 3)) {
      links.push({
        label: `${category?.shortTitle ?? "Home services"} in ${nearby.city}`,
        href: category
          ? `${getMarketUrlPath(nearby)}/${category.slug}`
          : getMarketUrlPath(nearby),
        reason: "Nearby service page",
      });
    }

    const servicePath = subcategory
      ? `${marketPath}/${subcategory.parentSlug}/${subcategory.slug}`
      : category
        ? `${marketPath}/${category.slug}`
        : marketPath;

    for (const intent of getIndexableServiceIntents().slice(0, 4)) {
      links.push({
        label: `${intent.title} ${subcategory?.shortTitle ?? category?.shortTitle ?? "service"}`,
        href: `${servicePath}/${intent.slug}`,
        reason: "Intent variation",
      });
    }
  }

  return dedupeLinks(links).slice(0, 12);
}

async function applySitemapAwareness() {
  const admin = createSupabaseAdminClient();

  const { data, error } = await admin
    .from("ai_generated_pages")
    .select("id, target_url, status, quality_status")
    .in("status", ["draft", "needs_review", "published"])
    .limit(500);

  if (error) {
    throw new Error(error.message);
  }

  const pages = (data ?? []) as GeneratedPageRow[];
  let markedNoindex = 0;

  for (const page of pages) {
    if (page.status === "published" && page.quality_status !== "approved") {
      const { error: updateError } = await admin
        .from("ai_generated_pages")
        .update({
          status: "needs_review",
          updated_at: new Date().toISOString(),
          quality_notes: ["Published page was pulled back because quality status is not approved."],
        })
        .eq("id", page.id);

      if (updateError) {
        throw new Error(updateError.message);
      }

      markedNoindex += 1;
    }
  }

  return {
    publishedPagesInGeneratedSitemap: pages.filter(
      (page) => page.status === "published" && page.quality_status === "approved"
    ).length,
    pulledBackWeakPublishedPages: markedNoindex,
    sitemapPath: "/sitemaps/generated-pages.xml",
  };
}

function getIntentScore(intentSlug?: string | null) {
  if (intentSlug === "emergency") return 14;
  if (intentSlug === "same-day") return 12;
  if (intentSlug === "price") return 11;
  if (intentSlug === "licensed") return 9;
  if (intentSlug === "near-me") return 6;
  return 4;
}

function getGeoScore(countryCode?: string | null, marketSlug?: string | null) {
  if (!marketSlug) return 0;
  if (countryCode === "us") return 10;
  if (["ca", "gb", "au"].includes(countryCode ?? "")) return 8;
  return 4;
}

function buildTargetFromOpportunity(opportunity: SeoOpportunityRow) {
  const market = opportunity.market_slug
    ? getMarketBySlug(opportunity.market_slug)
    : null;

  if (!market || !opportunity.category_slug) return null;

  const marketPath = getMarketUrlPath(market);
  const servicePath = opportunity.subcategory_slug
    ? `${opportunity.category_slug}/${opportunity.subcategory_slug}`
    : opportunity.category_slug;

  return opportunity.intent_slug
    ? `${marketPath}/${servicePath}/${opportunity.intent_slug}`
    : `${marketPath}/${servicePath}`;
}

function getMetadataNumber(opportunity: SeoOpportunityRow, key: string) {
  const metadata = opportunity.proposed_action ?? {};
  const value = metadata[key];

  return typeof value === "number" && Number.isFinite(value) ? value : undefined;
}

function getScoreBreakdown(
  opportunity: SeoOpportunityRow,
  score: number,
  duplicationRisk: number
) {
  return {
    score,
    intent: opportunity.intent_slug,
    servicePriority: SERVICE_PRIORITY[opportunity.category_slug ?? ""] ?? 5,
    campaignCategoryBoost: getCampaignCategoryBoost(opportunity.category_slug),
    campaignGeoBoost: getCampaignGeoBoost(
      opportunity.market_slug ? getMarketBySlug(opportunity.market_slug) : null
    ),
    emergencyIntent: EMERGENCY_INTENTS.has(opportunity.intent_slug ?? ""),
    duplicationRisk,
  };
}

function dedupeLinks<T extends { href: string }>(links: T[]) {
  return Array.from(new Map(links.map((link) => [link.href, link])).values());
}

function getNumber(value: unknown, key: string) {
  if (!value || typeof value !== "object" || !(key in value)) return 0;
  const maybeNumber = (value as Record<string, unknown>)[key];
  return typeof maybeNumber === "number" ? maybeNumber : 0;
}

function toMetadata(value: unknown): Record<string, unknown> | undefined {
  if (!value || typeof value !== "object") return undefined;
  return value as Record<string, unknown>;
}
