import { createSupabaseAdminClient } from "@/lib/supabase/admin";

type OpportunityRow = {
  id: string;
  country_code: string;
  market_slug: string | null;
  category_slug: string | null;
  subcategory_slug: string | null;
  intent_slug: string | null;
  title: string;
  target_url: string | null;
  search_query: string | null;
  recommendation: string | null;
  proposed_action: Record<string, unknown> | null;
};

type DraftResult = {
  created: boolean;
  pageId?: string;
};

export async function runAutoGenerateDraftsAgent() {
  const admin = createSupabaseAdminClient();

  const { data: run, error: runError } = await admin
    .from("ai_agent_runs")
    .insert({
      agent_name: "auto_generate_drafts_agent",
      status: "running",
      metadata: {
        source: "ai_seo_opportunities",
      },
    })
    .select("id")
    .single();

  if (runError || !run) {
    throw new Error(runError?.message ?? "Unable to create agent run.");
  }

  try {
    const { data: opportunities, error } = await admin
      .from("ai_seo_opportunities")
      .select(
        "id, country_code, market_slug, category_slug, subcategory_slug, intent_slug, title, target_url, search_query, recommendation, proposed_action"
      )
      .in("status", ["new", "approved"])
      .order("priority_score", { ascending: false })
      .order("created_at", { ascending: true })
      .limit(25);

    if (error) {
      throw new Error(error.message);
    }

    let generatedCount = 0;
    let skippedCount = 0;
    let failedCount = 0;

    for (const opportunity of (opportunities ?? []) as OpportunityRow[]) {
      try {
        const result = await generateDraftForOpportunity(opportunity);

        if (result.created) {
          generatedCount += 1;
        } else {
          skippedCount += 1;
        }
      } catch (error) {
        failedCount += 1;

        console.error("Failed to auto-generate draft", {
          opportunityId: opportunity.id,
          error,
        });
      }
    }

    await admin
      .from("ai_agent_runs")
      .update({
        status: "completed",
        summary: `Processed ${
          opportunities?.length ?? 0
        } opportunities. Generated ${generatedCount}. Skipped ${skippedCount}. Failed ${failedCount}.`,
        finished_at: new Date().toISOString(),
        metadata: {
          source: "ai_seo_opportunities",
          processedCount: opportunities?.length ?? 0,
          generatedCount,
          skippedCount,
          failedCount,
        },
      })
      .eq("id", run.id);

    return {
      ok: true,
      runId: run.id,
      processedCount: opportunities?.length ?? 0,
      generatedCount,
      skippedCount,
      failedCount,
    };
  } catch (error) {
    await admin
      .from("ai_agent_runs")
      .update({
        status: "failed",
        summary: error instanceof Error ? error.message : "Unknown error",
        finished_at: new Date().toISOString(),
      })
      .eq("id", run.id);

    throw error;
  }
}

async function generateDraftForOpportunity(
  opportunity: OpportunityRow
): Promise<DraftResult> {
  const admin = createSupabaseAdminClient();

  if (!opportunity.target_url || !opportunity.category_slug || !opportunity.intent_slug) {
    return { created: false };
  }

  const { data: existingByOpportunity, error: existingOpportunityError } = await admin
    .from("ai_generated_pages")
    .select("id")
    .eq("opportunity_id", opportunity.id)
    .maybeSingle();

  if (existingOpportunityError) {
    throw new Error(existingOpportunityError.message);
  }

  if (existingByOpportunity) {
    return {
      created: false,
      pageId: existingByOpportunity.id,
    };
  }

  const { data: existingByTarget, error: existingTargetError } = await admin
    .from("ai_generated_pages")
    .select("id")
    .eq("target_url", opportunity.target_url)
    .maybeSingle();

  if (existingTargetError) {
    throw new Error(existingTargetError.message);
  }

  if (existingByTarget) {
    return {
      created: false,
      pageId: existingByTarget.id,
    };
  }

  const content = buildDraftContent(opportunity);

  const { data: created, error: insertError } = await admin
  .from("ai_generated_pages")
  .insert({
    opportunity_id: opportunity.id,
    page_type:
      typeof opportunity.proposed_action?.pageType === "string"
        ? opportunity.proposed_action.pageType
        : "geo_category_intent",
    target_url: opportunity.target_url,
    status: "draft",
    title: content.title,
    meta_description: content.metaDescription,
    h1: content.h1,
    intro: content.intro,
    sections: content.sections,
    faqs: content.faqs,
    internal_links: content.internalLinks,
    cta: content.cta,
    quality_status: "pending",
    quality_notes: [],
  })
  .select("id")
  .single();

  if (insertError) {
    throw new Error(insertError.message);
  }

  await admin
    .from("ai_seo_opportunities")
    .update({
      status: "in_progress",
      updated_at: new Date().toISOString(),
    })
    .eq("id", opportunity.id);

  return {
    created: true,
    pageId: created.id,
  };
}

function buildDraftContent(opportunity: OpportunityRow) {
  const category = titleCase(
    opportunity.category_slug?.replace(/-/g, " ") ?? "home service"
  );
  const intent = opportunity.intent_slug ?? "service";
  const marketName = getReadableMarketName(opportunity);
  const searchQuery = opportunity.search_query ?? `${category} ${intent}`;

  const intentLabel =
    intent === "price"
      ? "cost and pricing"
      : intent === "same-day"
        ? "same-day service"
        : intent === "emergency"
          ? "emergency help"
          : intent === "near-me"
            ? "nearby pros"
            : intent.replace(/-/g, " ");
  const recommendedLinks = getRecommendedLinks(opportunity);

  return {
    title: `${category} ${intentLabel} in ${marketName} | Fixly`,
    metaDescription: `Find ${category.toLowerCase()} ${intentLabel} in ${marketName}. Compare local options, understand pricing, and post a request on Fixly.`,
    h1: `${category} ${intentLabel} in ${marketName}`,
    intro: `If you searched for "${searchQuery}", Fixly helps you understand what to expect and quickly request help from local home service pros in ${marketName}. Use this page for a direct summary, pricing guidance, urgency context, process steps, and related local service options before posting your request.`,
    sections: [
      {
        heading: "Direct summary",
        body: `${category} ${intentLabel} in ${marketName} is for homeowners who need clear local guidance before requesting help. The important details are the service type, timing, location, likely scope, safety concerns, and whether the work may require a licensed pro.`,
      },
      {
        heading: "Price guidance",
        body: `${category} pricing depends on labor time, materials, access, project complexity, local availability, and urgency. Emergency, same-day, after-hours, or permit-sensitive work can cost more than a routine scheduled visit.`,
      },
      {
        heading: "Urgency guidance",
        body: `Request faster help when the issue affects safety, water, power, heat, access, active damage, security, or normal use of the home. If the situation is not urgent, include preferred timing so pros can quote accurately.`,
      },
      {
        heading: `What affects ${category.toLowerCase()} ${intentLabel}`,
        body: `${category} pricing and availability can depend on project size, access, materials, urgency, property condition, and whether licensed work is required. The best first step is to describe the issue clearly so local pros can respond with accurate next steps.`,
      },
      {
        heading: "Typical process",
        body: `Most ${category.toLowerCase()} requests follow a simple path: describe the issue, add photos or measurements, confirm access and timing, compare pro responses, approve the scope, complete the work, and review any follow-up maintenance.`,
      },
      {
        heading: "DIY vs professional help",
        body: `DIY may be reasonable for small cosmetic or non-urgent tasks. Hire a pro when the work involves safety, code requirements, water, electricity, structural risk, specialized tools, active damage, or unclear diagnosis.`,
      },
      {
        heading: `How Fixly helps`,
        body: `Fixly lets you post a clear service request, organize the project details, and make the request visible to local professionals. This reduces back-and-forth and helps pros decide whether they are a good fit before contacting you.`,
      },
    ],
    faqs: [
      {
        question: `How much does ${category.toLowerCase()} cost in ${marketName}?`,
        answer:
          "The final cost depends on the scope, materials, labor time, access, urgency, and local availability. Small jobs usually cost less, while complex or urgent work can cost more.",
      },
      {
        question: `Can I request ${category.toLowerCase()} help near me?`,
        answer: `Yes. Fixly helps homeowners post local service requests in ${marketName} so nearby pros can review the job details.`,
      },
      {
        question: `Is ${category.toLowerCase()} urgent?`,
        answer:
          "It may be urgent when there is active damage, unsafe operation, loss of essential service, water, electricity, heat, security, or a problem that is spreading.",
      },
      {
        question: `Do I need a licensed ${category.toLowerCase()} pro?`,
        answer:
          "Licensing depends on the service, local rules, and project scope. Electrical, plumbing, HVAC, structural, roofing, and major installation work may require a licensed professional or permit.",
      },
      {
        question: "Can this problem get worse if I wait?",
        answer:
          "Yes, some home service issues can spread or become more expensive when moisture, electrical load, structural stress, repeated use, pests, or weather exposure are involved.",
      },
      {
        question: "What should I include in my request?",
        answer:
          "Include the service needed, location, timing, photos if available, access notes, and any details about materials, measurements, symptoms, or urgency.",
      },
      {
        question: "Can this be handled same day?",
        answer:
          "Same-day availability depends on the service type, pro availability, project complexity, and how clearly the request is described.",
      },
    ],
    internalLinks: [
      ...recommendedLinks,
      {
        label: "Post a service request",
        href: "/book",
      },
      {
        label: "Browse open requests",
        href: "/requests",
      },
      {
        label: "View all services",
        href: "/services",
      },
    ],
    cta: `Post your ${category.toLowerCase()} request on Fixly with the project details, preferred timing, and location. Local pros can review the request and respond if they are available.`,
  };
}

function getRecommendedLinks(opportunity: OpportunityRow) {
  const rawLinks = opportunity.proposed_action?.internalLinkRecommendations;

  if (!Array.isArray(rawLinks)) {
    return [];
  }

  return rawLinks
    .map((link) => {
      if (!link || typeof link !== "object") return null;

      const record = link as Record<string, unknown>;
      const label = typeof record.label === "string" ? record.label : null;
      const href = typeof record.href === "string" ? record.href : null;

      return label && href ? { label, href } : null;
    })
    .filter((link): link is { label: string; href: string } => Boolean(link));
}

function getReadableMarketName(opportunity: OpportunityRow) {
  const raw =
    typeof opportunity.proposed_action?.marketSlug === "string"
      ? opportunity.proposed_action.marketSlug
      : opportunity.market_slug;

  if (!raw) return "your area";

  return titleCase(
    raw
      .replace(/-[a-z]{2}$/i, "")
      .replace(/-\d+$/g, "")
      .replace(/-/g, " ")
  );
}

function titleCase(value: string) {
  return value.replace(/\w\S*/g, (word) => {
    return word.charAt(0).toUpperCase() + word.slice(1).toLowerCase();
  });
}
