import Link from "next/link";
import { requireAdminUser } from "@/lib/auth/admin";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { AiOpportunityActions } from "@/features/account/AiOpportunityActions";

export const dynamic = "force-dynamic";

type AiSeoOpportunity = {
  id: string;
  title: string;
  target_url: string | null;
  search_query: string | null;
  priority_score: number;
  status: string;
  recommendation: string;
  created_at: string;
};

export default async function AiAgentsPage() {
  await requireAdminUser();

  const admin = createSupabaseAdminClient();

  const { data: opportunities, error } = await admin
    .from("ai_seo_opportunities")
    .select(
      "id, title, target_url, search_query, priority_score, status, recommendation, created_at"
    )
    .order("priority_score", { ascending: false })
    .order("created_at", { ascending: false })
    .limit(100);

  if (error) {
    throw new Error(error.message);
  }

  return (
    <main className="page">
      <section className="section">
        <div className="container">
          <p className="eyebrow">Fixly AI Ops</p>

          <h1>AI Agent Opportunities</h1>

          <p className="hero-text">
            Review SEO and marketplace improvement ideas generated by internal
            Fixly agents.
          </p>

          <div className="grid-1">
            {(opportunities ?? []).map((item: AiSeoOpportunity) => (
              <article key={item.id} className="card">
                <div className="flex flex-between gap-md">
                  <div>
                    <p className="eyebrow">
                      Priority {item.priority_score} · {item.status}
                    </p>

                    <h2>{item.title}</h2>

                    {item.search_query ? (
                      <p>
                        <strong>Search query:</strong> {item.search_query}
                      </p>
                    ) : null}

                    {item.target_url ? (
                      <p>
                        <strong>Target URL:</strong>{" "}
                        <Link href={item.target_url}>{item.target_url}</Link>
                      </p>
                    ) : null}

                    <p>{item.recommendation}</p>
                    <AiOpportunityActions opportunityId={item.id} status={item.status} />
                  </div>
                </div>
              </article>
            ))}
          </div>
        </div>
      </section>
    </main>
  );
}