import type { SubcategoryMap } from "../types";

export const appliancesSubcategories: SubcategoryMap = {
  "washer-dryer-repair-installation": {
    slug: "washer-dryer-repair-installation",
    title: "Washer and Dryer Repair & Installation",
    shortTitle: "Washer & Dryer",
    parentSlug: "appliance-repair-installation",
    description:
      "Repair, installation, replacement, vent connection, troubleshooting, and setup for washing machines and dryers.",
    commonProblems: [
      "Washer not draining",
      "Dryer not heating",
      "Washer shaking or leaking",
      "Dryer taking too long to dry",
      "Stackable washer dryer installation",
      "New laundry appliance hookup",
    ],
    priceMin: 95,
    priceMax: 450,
    priceUnit: "flat",
    relatedSlugs: [
      "dryer-vent-cleaning-repair",
      "appliance-troubleshooting",
      "garbage-disposal-repair-installation",
    ],
    formFields: [
      "Appliance brand and model",
      "Repair or installation",
      "Gas or electric dryer",
      "Stacked or side-by-side",
      "Issue description",
      "Photos of appliance and connections",
    ],
  },

  "refrigerator-freezer-repair": {
    slug: "refrigerator-freezer-repair",
    title: "Refrigerator and Freezer Repair",
    shortTitle: "Refrigerator Repair",
    parentSlug: "appliance-repair-installation",
    description:
      "Troubleshooting and repair for refrigerators, freezers, cooling issues, leaks, ice maker problems, and noisy operation.",
    commonProblems: [
      "Refrigerator not cooling",
      "Freezer icing up",
      "Water leaking from fridge",
      "Ice maker not working",
      "Loud refrigerator noise",
      "Door seal or temperature problems",
    ],
    priceMin: 120,
    priceMax: 600,
    priceUnit: "flat",
    relatedSlugs: [
      "ice-maker-water-line-installation",
      "appliance-troubleshooting",
      "dishwasher-repair-installation",
    ],
    formFields: [
      "Appliance brand and model",
      "Cooling issue",
      "Freezer or refrigerator section",
      "Ice maker status",
      "How long issue has existed",
      "Photos of appliance and label",
    ],
  },

  "dishwasher-repair-installation": {
    slug: "dishwasher-repair-installation",
    title: "Dishwasher Repair & Installation",
    shortTitle: "Dishwasher",
    parentSlug: "appliance-repair-installation",
    description:
      "Dishwasher repair, replacement, new installation, leak troubleshooting, drain fixes, and secure cabinet hookup.",
    commonProblems: [
      "Dishwasher not draining",
      "Dishwasher leaking",
      "Dishwasher not cleaning dishes",
      "New dishwasher installation",
      "Old dishwasher replacement",
      "Water supply or drain connection issue",
    ],
    priceMin: 110,
    priceMax: 500,
    priceUnit: "flat",
    relatedSlugs: [
      "garbage-disposal-repair-installation",
      "appliance-installation",
      "appliance-troubleshooting",
    ],
    formFields: [
      "Repair or installation",
      "Existing dishwasher present",
      "Brand and model",
      "Leak or drain issue",
      "Cabinet opening ready",
      "Photos under sink and dishwasher",
    ],
  },

  "oven-range-stove-repair-installation": {
    slug: "oven-range-stove-repair-installation",
    title: "Oven, Range and Stove Repair & Installation",
    shortTitle: "Oven & Stove",
    parentSlug: "appliance-repair-installation",
    description:
      "Repair and installation for ovens, cooktops, ranges, stoves, burners, heating issues, and appliance replacements.",
    commonProblems: [
      "Oven not heating",
      "Burner not working",
      "Range installation",
      "Cooktop replacement",
      "Gas stove connection issue",
      "Temperature or control panel problem",
    ],
    priceMin: 120,
    priceMax: 650,
    priceUnit: "flat",
    relatedSlugs: [
      "appliance-installation",
      "appliance-troubleshooting",
      "microwave-installation-repair",
    ],
    formFields: [
      "Gas or electric appliance",
      "Repair or installation",
      "Brand and model",
      "Issue description",
      "Existing hookup type",
      "Photos of appliance and connection",
    ],
  },

  "microwave-installation-repair": {
    slug: "microwave-installation-repair",
    title: "Microwave Installation & Repair",
    shortTitle: "Microwave",
    parentSlug: "appliance-repair-installation",
    description:
      "Over-the-range microwave installation, replacement, mounting, vent setup, basic repair, and troubleshooting.",
    commonProblems: [
      "Over-the-range microwave installation",
      "Microwave replacement",
      "Microwave not heating",
      "Turntable or door issue",
      "Vent connection problem",
      "Mounting bracket or cabinet fit issue",
    ],
    priceMin: 90,
    priceMax: 350,
    priceUnit: "flat",
    relatedSlugs: [
      "appliance-installation",
      "oven-range-stove-repair-installation",
      "appliance-troubleshooting",
    ],
    formFields: [
      "Over-the-range or countertop",
      "Repair or installation",
      "Brand and model",
      "Existing microwave installed",
      "Vented or recirculating",
      "Photos of cabinet and outlet",
    ],
  },

  "garbage-disposal-repair-installation": {
    slug: "garbage-disposal-repair-installation",
    title: "Garbage Disposal Repair & Installation",
    shortTitle: "Garbage Disposal",
    parentSlug: "appliance-repair-installation",
    description:
      "Garbage disposal repair, replacement, installation, jam clearing, leak troubleshooting, and sink connection work.",
    commonProblems: [
      "Garbage disposal humming",
      "Disposal leaking",
      "Disposal not turning on",
      "New garbage disposal installation",
      "Old disposal replacement",
      "Sink drain connection issue",
    ],
    priceMin: 95,
    priceMax: 350,
    priceUnit: "flat",
    relatedSlugs: [
      "dishwasher-repair-installation",
      "appliance-installation",
      "appliance-troubleshooting",
    ],
    formFields: [
      "Repair or replacement",
      "Disposal brand if known",
      "Leak location",
      "Power switch status",
      "Sink type",
      "Photos under sink",
    ],
  },

  "ice-maker-water-line-installation": {
    slug: "ice-maker-water-line-installation",
    title: "Ice Maker and Water Line Installation",
    shortTitle: "Ice Maker Line",
    parentSlug: "appliance-repair-installation",
    description:
      "Refrigerator water line installation, ice maker hookup, leak repair, shutoff valve replacement, and connection troubleshooting.",
    commonProblems: [
      "Ice maker not filling",
      "Refrigerator water line leak",
      "New fridge water line hookup",
      "No shutoff valve behind fridge",
      "Low water flow",
      "Filter or connection issue",
    ],
    priceMin: 120,
    priceMax: 450,
    priceUnit: "flat",
    relatedSlugs: [
      "refrigerator-freezer-repair",
      "appliance-installation",
      "dishwasher-repair-installation",
    ],
    formFields: [
      "Existing water line present",
      "Fridge brand and model",
      "Leak or new installation",
      "Distance to water source",
      "Shutoff valve location",
      "Photos behind fridge",
    ],
  },

  "dryer-vent-cleaning-repair": {
    slug: "dryer-vent-cleaning-repair",
    title: "Dryer Vent Cleaning & Repair",
    shortTitle: "Dryer Vent",
    parentSlug: "appliance-repair-installation",
    description:
      "Dryer vent cleaning, vent hose replacement, airflow troubleshooting, bird guard repair, and dryer performance improvement.",
    commonProblems: [
      "Dryer takes too long to dry",
      "Dryer overheating",
      "Lint buildup",
      "Disconnected dryer vent hose",
      "Damaged exterior vent cover",
      "Burning smell from dryer area",
    ],
    priceMin: 90,
    priceMax: 300,
    priceUnit: "flat",
    relatedSlugs: [
      "washer-dryer-repair-installation",
      "appliance-maintenance",
      "appliance-troubleshooting",
    ],
    formFields: [
      "Dryer location",
      "Vent exit location",
      "Last cleaning date",
      "Drying performance issue",
      "Flexible or rigid vent",
      "Photos of dryer and vent",
    ],
  },

  "appliance-installation": {
    slug: "appliance-installation",
    title: "Appliance Installation",
    shortTitle: "Installation",
    parentSlug: "appliance-repair-installation",
    description:
      "Professional appliance installation, replacement, leveling, connection, haul-away coordination, and setup for major home appliances.",
    commonProblems: [
      "New appliance needs installation",
      "Old appliance replacement",
      "Appliance not level",
      "Connection parts missing",
      "Cabinet or opening fit issue",
      "Need appliance setup after delivery",
    ],
    priceMin: 90,
    priceMax: 550,
    priceUnit: "flat",
    relatedSlugs: [
      "dishwasher-repair-installation",
      "washer-dryer-repair-installation",
      "oven-range-stove-repair-installation",
    ],
    formFields: [
      "Appliance type",
      "New installation or replacement",
      "Brand and model",
      "Existing hookup ready",
      "Old appliance removal needed",
      "Photos of installation area",
    ],
  },

  "appliance-troubleshooting": {
    slug: "appliance-troubleshooting",
    title: "Appliance Troubleshooting",
    shortTitle: "Troubleshooting",
    parentSlug: "appliance-repair-installation",
    description:
      "Diagnostic help for appliance problems when the issue is unclear, including leaks, noises, power issues, heating, cooling, and performance problems.",
    commonProblems: [
      "Appliance suddenly stopped working",
      "Unusual noise or vibration",
      "Water leak near appliance",
      "Appliance trips breaker",
      "Heating or cooling problem",
      "Error code on appliance display",
    ],
    priceMin: 85,
    priceMax: 250,
    priceUnit: "flat",
    relatedSlugs: [
      "appliance-maintenance",
      "refrigerator-freezer-repair",
      "washer-dryer-repair-installation",
    ],
    formFields: [
      "Appliance type",
      "Brand and model",
      "Error code if visible",
      "Issue description",
      "When problem started",
      "Photos or short video",
    ],
  },

  "appliance-maintenance": {
    slug: "appliance-maintenance",
    title: "Appliance Maintenance",
    shortTitle: "Maintenance",
    parentSlug: "appliance-repair-installation",
    description:
      "Preventive appliance maintenance, cleaning, inspection, filter checks, vent checks, leveling, and performance review.",
    commonProblems: [
      "Annual appliance checkup",
      "Dryer vent maintenance",
      "Refrigerator coil cleaning",
      "Dishwasher cleaning and inspection",
      "Appliance performance decline",
      "Preventive maintenance before rental turnover",
    ],
    priceMin: 90,
    priceMax: 350,
    priceUnit: "flat",
    relatedSlugs: [
      "dryer-vent-cleaning-repair",
      "appliance-troubleshooting",
      "refrigerator-freezer-repair",
    ],
    formFields: [
      "Appliance types",
      "Number of appliances",
      "Maintenance goal",
      "Known issues",
      "Property type",
      "Photos if available",
    ],
  },
};