import type { SubcategoryMap } from "../types";

export const awningsSubcategories: SubcategoryMap = {
  "retractable-awning-installation": {
    slug: "retractable-awning-installation",
    title: "Retractable Awning Installation",
    shortTitle: "Retractable Awnings",
    parentSlug: "awnings",
    description:
      "Manual and motorized retractable awning installation for patios, decks, balconies, windows, and outdoor seating areas.",
    commonProblems: [
      "No shade over patio or deck",
      "Old awning no longer extends correctly",
      "Need motorized retractable shade",
      "Sun exposure makes outdoor space unusable",
      "Mounting surface needs professional evaluation",
    ],
    priceMin: 450,
    priceMax: 3500,
    priceUnit: "flat",
    relatedSlugs: [
      "awning-repair",
      "motorized-awning-service",
      "patio-awning-installation",
      "awning-fabric-replacement",
    ],
    formFields: [
      "Awning location",
      "Manual or motorized",
      "Approximate width",
      "Mounting surface",
      "Existing awning removal needed",
      "Preferred timeline",
    ],
  },

  "patio-awning-installation": {
    slug: "patio-awning-installation",
    title: "Patio Awning Installation",
    shortTitle: "Patio Awnings",
    parentSlug: "awnings",
    description:
      "Patio and deck awning installation for residential outdoor living spaces, including fixed, retractable, and shade canopy options.",
    commonProblems: [
      "Patio gets too much direct sun",
      "Outdoor furniture fades from UV exposure",
      "Need shade for family seating area",
      "Deck or patio is uncomfortable in summer",
      "Existing shade solution is unstable or worn",
    ],
    priceMin: 350,
    priceMax: 3000,
    priceUnit: "flat",
    relatedSlugs: [
      "retractable-awning-installation",
      "fixed-awning-installation",
      "awning-replacement",
      "awning-repair",
    ],
    formFields: [
      "Patio or deck size",
      "Preferred awning type",
      "Wall, roof, or freestanding mount",
      "Existing structure details",
      "Photos of installation area",
      "Desired shade coverage",
    ],
  },

  "fixed-awning-installation": {
    slug: "fixed-awning-installation",
    title: "Fixed Awning & Canopy Installation",
    shortTitle: "Fixed Awnings",
    parentSlug: "awnings",
    description:
      "Fixed awning and canopy installation for doors, windows, patios, walkways, storefronts, and weather-protected entrances.",
    commonProblems: [
      "Doorway needs rain protection",
      "Window gets heavy sun exposure",
      "Entry area needs permanent cover",
      "Existing canopy is damaged",
      "Need a durable non-retractable awning",
    ],
    priceMin: 300,
    priceMax: 2500,
    priceUnit: "flat",
    relatedSlugs: [
      "commercial-storefront-awning",
      "patio-awning-installation",
      "awning-frame-repair",
      "awning-replacement",
    ],
    formFields: [
      "Installation location",
      "Awning width and projection",
      "Material preference",
      "Mounting surface",
      "Residential or commercial property",
      "Permit or HOA constraints",
    ],
  },

  "commercial-storefront-awning": {
    slug: "commercial-storefront-awning",
    title: "Commercial Storefront Awning Service",
    shortTitle: "Storefront Awnings",
    parentSlug: "awnings",
    description:
      "Commercial storefront awning installation, repair, replacement, and branding-ready canopy service for restaurants, shops, offices, and retail spaces.",
    commonProblems: [
      "Storefront needs better curb appeal",
      "Old commercial awning is faded or torn",
      "Restaurant patio needs shade",
      "Business entrance needs weather protection",
      "Awning frame or signage area needs repair",
    ],
    priceMin: 800,
    priceMax: 7500,
    priceUnit: "flat",
    relatedSlugs: [
      "fixed-awning-installation",
      "awning-fabric-replacement",
      "awning-frame-repair",
      "awning-removal-disposal",
    ],
    formFields: [
      "Business type",
      "Storefront width",
      "Awning condition",
      "Branding or signage needs",
      "Access limitations",
      "Preferred work hours",
    ],
  },

  "awning-repair": {
    slug: "awning-repair",
    title: "Awning Repair",
    shortTitle: "Awning Repair",
    parentSlug: "awnings",
    description:
      "Awning repair for torn fabric, loose mounts, bent arms, damaged frames, stuck retractable systems, and weather-related wear.",
    commonProblems: [
      "Awning will not open or close",
      "Fabric is torn or sagging",
      "Frame is bent or loose",
      "Mounting brackets are pulling away",
      "Storm or wind caused damage",
    ],
    priceMin: 150,
    priceMax: 1200,
    priceUnit: "flat",
    relatedSlugs: [
      "awning-frame-repair",
      "awning-fabric-replacement",
      "motorized-awning-service",
      "awning-replacement",
    ],
    formFields: [
      "Type of damage",
      "Manual or motorized system",
      "Awning size",
      "Photos of damaged area",
      "Age of awning",
      "Urgency",
    ],
  },

  "awning-fabric-replacement": {
    slug: "awning-fabric-replacement",
    title: "Awning Fabric Replacement",
    shortTitle: "Fabric Replacement",
    parentSlug: "awnings",
    description:
      "Awning fabric replacement for faded, torn, stained, sagging, or weather-damaged residential and commercial awnings.",
    commonProblems: [
      "Fabric is faded from sun exposure",
      "Awning canvas is torn",
      "Water stains or mildew are visible",
      "Fabric has separated from frame",
      "Need updated color or material",
    ],
    priceMin: 250,
    priceMax: 2500,
    priceUnit: "flat",
    relatedSlugs: [
      "awning-repair",
      "commercial-storefront-awning",
      "awning-frame-repair",
      "awning-replacement",
    ],
    formFields: [
      "Awning dimensions",
      "Fabric condition",
      "Residential or commercial use",
      "Color or material preference",
      "Frame condition",
      "Photos of current awning",
    ],
  },

  "awning-frame-repair": {
    slug: "awning-frame-repair",
    title: "Awning Frame Repair",
    shortTitle: "Frame Repair",
    parentSlug: "awnings",
    description:
      "Awning frame repair for bent supports, loose brackets, damaged arms, rusted components, and unstable canopy structures.",
    commonProblems: [
      "Frame is bent after wind",
      "Awning feels unstable",
      "Support arms are damaged",
      "Mounting brackets are loose",
      "Rust or corrosion is visible",
    ],
    priceMin: 175,
    priceMax: 1500,
    priceUnit: "flat",
    relatedSlugs: [
      "awning-repair",
      "awning-fabric-replacement",
      "fixed-awning-installation",
      "awning-replacement",
    ],
    formFields: [
      "Frame material",
      "Damage location",
      "Awning size",
      "Mounting condition",
      "Photos of frame",
      "Safety concerns",
    ],
  },

  "motorized-awning-service": {
    slug: "motorized-awning-service",
    title: "Motorized Awning Service",
    shortTitle: "Motorized Awnings",
    parentSlug: "awnings",
    description:
      "Motorized awning installation, troubleshooting, adjustment, and repair for remote-controlled and automated retractable systems.",
    commonProblems: [
      "Motorized awning stopped working",
      "Remote does not respond",
      "Awning moves unevenly",
      "Sensor or switch is not working",
      "Need upgrade from manual to motorized",
    ],
    priceMin: 250,
    priceMax: 2200,
    priceUnit: "flat",
    relatedSlugs: [
      "retractable-awning-installation",
      "awning-repair",
      "awning-replacement",
      "awning-lighting-installation",
    ],
    formFields: [
      "Motor brand if known",
      "Remote or switch issue",
      "Power source",
      "Awning size",
      "Current symptoms",
      "Photos or video of issue",
    ],
  },

  "awning-replacement": {
    slug: "awning-replacement",
    title: "Awning Replacement",
    shortTitle: "Awning Replacement",
    parentSlug: "awnings",
    description:
      "Full awning replacement for worn, damaged, outdated, unsafe, or poorly functioning awnings and canopy systems.",
    commonProblems: [
      "Existing awning is beyond repair",
      "Fabric and frame are both damaged",
      "Old awning no longer fits the property",
      "Need a stronger or larger shade system",
      "Awning was damaged by storm or age",
    ],
    priceMin: 500,
    priceMax: 6000,
    priceUnit: "flat",
    relatedSlugs: [
      "awning-removal-disposal",
      "retractable-awning-installation",
      "fixed-awning-installation",
      "awning-fabric-replacement",
    ],
    formFields: [
      "Current awning type",
      "Replacement type desired",
      "Approximate dimensions",
      "Removal needed",
      "Mounting surface",
      "Budget range",
    ],
  },

  "awning-removal-disposal": {
    slug: "awning-removal-disposal",
    title: "Awning Removal & Disposal",
    shortTitle: "Awning Removal",
    parentSlug: "awnings",
    description:
      "Safe awning removal and disposal for old, damaged, unsafe, or unwanted awnings, canopies, frames, and mounting hardware.",
    commonProblems: [
      "Old awning needs to be removed",
      "Damaged awning is unsafe",
      "Property is being renovated",
      "Need disposal after replacement",
      "Mounting hardware must be removed cleanly",
    ],
    priceMin: 150,
    priceMax: 1200,
    priceUnit: "flat",
    relatedSlugs: [
      "awning-replacement",
      "fixed-awning-installation",
      "commercial-storefront-awning",
      "patio-awning-installation",
    ],
    formFields: [
      "Awning size",
      "Height from ground",
      "Frame material",
      "Disposal needed",
      "Access conditions",
      "Photos of awning",
    ],
  },

  "seasonal-awning-setup-takedown": {
    slug: "seasonal-awning-setup-takedown",
    title: "Seasonal Awning Setup & Takedown",
    shortTitle: "Seasonal Setup",
    parentSlug: "awnings",
    description:
      "Seasonal awning installation, takedown, storage preparation, and weather-readiness service for homes, patios, and commercial spaces.",
    commonProblems: [
      "Awning needs spring setup",
      "Fabric should be removed before winter",
      "Storm season preparation is needed",
      "Seasonal canopy must be reinstalled",
      "Hardware needs inspection before use",
    ],
    priceMin: 125,
    priceMax: 900,
    priceUnit: "flat",
    relatedSlugs: [
      "awning-repair",
      "awning-fabric-replacement",
      "patio-awning-installation",
      "awning-removal-disposal",
    ],
    formFields: [
      "Setup or takedown",
      "Awning type",
      "Storage plan",
      "Number of awnings",
      "Access height",
      "Preferred date",
    ],
  },

  "awning-lighting-installation": {
    slug: "awning-lighting-installation",
    title: "Awning Lighting Installation",
    shortTitle: "Awning Lighting",
    parentSlug: "awnings",
    description:
      "Awning lighting installation for patios, storefronts, outdoor seating areas, accent lighting, and improved evening visibility.",
    commonProblems: [
      "Outdoor seating area is too dark",
      "Storefront awning needs lighting",
      "Need lights under patio cover",
      "Existing lights are outdated",
      "Awning area needs safer visibility",
    ],
    priceMin: 150,
    priceMax: 1500,
    priceUnit: "flat",
    relatedSlugs: [
      "commercial-storefront-awning",
      "patio-awning-installation",
      "motorized-awning-service",
      "fixed-awning-installation",
    ],
    formFields: [
      "Lighting type",
      "Power source",
      "Awning location",
      "Number of lights",
      "Commercial or residential",
      "Photos of installation area",
    ],
  },
};