import type { SubcategoryMap } from "../types";

export const cleaningSubcategories: SubcategoryMap = {
  "residential-cleaning": {
    slug: "residential-cleaning",
    title: "Residential Cleaning",
    shortTitle: "House Cleaning",
    parentSlug: "cleaning",
    description:
      "Recurring and one-time house cleaning for kitchens, bathrooms, bedrooms, living areas, dusting, vacuuming, mopping, and surface cleaning.",
    commonProblems: [
      "Weekly house cleaning",
      "Bi-weekly cleaning service",
      "One-time home cleaning",
      "Kitchen and bathroom cleaning",
      "Dust and pet hair buildup",
      "Cleaning before guests arrive",
    ],
    priceMin: 100,
    priceMax: 350,
    priceUnit: "flat",
    relatedSlugs: [
      "deep-cleaning",
      "move-out-cleaning",
      "apartment-cleaning",
    ],
    formFields: [
      "home_size",
      "bedrooms",
      "bathrooms",
      "cleaning_frequency",
      "pets",
      "priority_areas",
      "description",
      "photos",
    ],
  },

  "deep-cleaning": {
    slug: "deep-cleaning",
    title: "Deep Cleaning",
    shortTitle: "Deep Clean",
    parentSlug: "cleaning",
    description:
      "Detailed deep cleaning for homes that need extra attention, including baseboards, buildup, appliance exteriors, cabinet fronts, fixtures, and high-touch areas.",
    commonProblems: [
      "First-time deep clean",
      "Spring cleaning",
      "Heavy dust buildup",
      "Grease in kitchen areas",
      "Bathroom soap scum",
      "Baseboards and detailed surfaces",
    ],
    priceMin: 180,
    priceMax: 650,
    priceUnit: "flat",
    relatedSlugs: [
      "residential-cleaning",
      "move-in-cleaning",
      "post-construction-cleaning",
    ],
    formFields: [
      "home_size",
      "bedrooms",
      "bathrooms",
      "level_of_buildup",
      "extras_needed",
      "priority_areas",
      "description",
      "photos",
    ],
  },

  "move-out-cleaning": {
    slug: "move-out-cleaning",
    title: "Move-Out Cleaning",
    shortTitle: "Move-Out Clean",
    parentSlug: "cleaning",
    description:
      "Move-out cleaning for apartments, rentals, and homes, focused on empty spaces, kitchens, bathrooms, floors, cabinets, and turnover readiness.",
    commonProblems: [
      "End of lease cleaning",
      "Empty apartment cleaning",
      "Security deposit cleaning",
      "Tenant turnover",
      "Cleaning before listing a home",
      "Kitchen and bathroom reset",
    ],
    priceMin: 200,
    priceMax: 750,
    priceUnit: "flat",
    relatedSlugs: [
      "move-in-cleaning",
      "deep-cleaning",
      "apartment-cleaning",
    ],
    formFields: [
      "property_type",
      "home_size",
      "bedrooms",
      "bathrooms",
      "move_date",
      "is_property_empty",
      "extras_needed",
      "description",
      "photos",
    ],
  },

  "move-in-cleaning": {
    slug: "move-in-cleaning",
    title: "Move-In Cleaning",
    shortTitle: "Move-In Clean",
    parentSlug: "cleaning",
    description:
      "Move-in cleaning before unpacking, including cabinets, counters, bathrooms, floors, closets, appliance surfaces, and high-touch areas.",
    commonProblems: [
      "Cleaning before moving in",
      "Previous owner residue",
      "Dusty cabinets and closets",
      "Bathroom sanitizing",
      "Kitchen reset before unpacking",
      "Empty house cleaning",
    ],
    priceMin: 200,
    priceMax: 750,
    priceUnit: "flat",
    relatedSlugs: [
      "move-out-cleaning",
      "deep-cleaning",
      "residential-cleaning",
    ],
    formFields: [
      "property_type",
      "home_size",
      "bedrooms",
      "bathrooms",
      "move_date",
      "is_property_empty",
      "extras_needed",
      "description",
      "photos",
    ],
  },

  "apartment-cleaning": {
    slug: "apartment-cleaning",
    title: "Apartment Cleaning",
    shortTitle: "Apartment Cleaning",
    parentSlug: "cleaning",
    description:
      "Apartment cleaning for studios, condos, townhomes, and rental units, including recurring, one-time, move-in, and move-out cleaning.",
    commonProblems: [
      "Small apartment cleaning",
      "Condo cleaning",
      "Rental unit cleaning",
      "Kitchen and bathroom cleaning",
      "Dust and floor cleaning",
      "Cleaning before inspection",
    ],
    priceMin: 90,
    priceMax: 350,
    priceUnit: "flat",
    relatedSlugs: [
      "residential-cleaning",
      "move-out-cleaning",
      "deep-cleaning",
    ],
    formFields: [
      "apartment_size",
      "bedrooms",
      "bathrooms",
      "cleaning_type",
      "parking_access",
      "pets",
      "description",
      "photos",
    ],
  },

  "maid-service": {
    slug: "maid-service",
    title: "Maid Service",
    shortTitle: "Maid Service",
    parentSlug: "cleaning",
    description:
      "Recurring maid service for routine home upkeep, including dusting, vacuuming, mopping, kitchen cleaning, bathroom cleaning, and light tidying.",
    commonProblems: [
      "Weekly maid service",
      "Bi-weekly maid service",
      "Light housekeeping",
      "Recurring bathroom cleaning",
      "Recurring kitchen cleaning",
      "Busy family home upkeep",
    ],
    priceMin: 100,
    priceMax: 400,
    priceUnit: "flat",
    relatedSlugs: [
      "residential-cleaning",
      "apartment-cleaning",
      "deep-cleaning",
    ],
    formFields: [
      "home_size",
      "bedrooms",
      "bathrooms",
      "frequency",
      "preferred_day",
      "pets",
      "priority_areas",
      "description",
    ],
  },

  "post-construction-cleaning": {
    slug: "post-construction-cleaning",
    title: "Post-Construction Cleaning",
    shortTitle: "Post-Construction",
    parentSlug: "cleaning",
    description:
      "Cleaning after remodeling, renovation, repairs, or construction work, including dust removal, surface cleaning, debris cleanup, and final detail cleaning.",
    commonProblems: [
      "Renovation dust",
      "Drywall dust cleanup",
      "Post-remodel cleaning",
      "Construction debris",
      "Dust on floors and fixtures",
      "Final clean before move-in",
    ],
    priceMin: 250,
    priceMax: 1200,
    priceUnit: "flat",
    relatedSlugs: [
      "deep-cleaning",
      "move-in-cleaning",
      "interior-painting",
    ],
    formFields: [
      "project_type",
      "home_size",
      "rooms_affected",
      "dust_level",
      "debris_removal_needed",
      "timeline",
      "description",
      "photos",
    ],
  },

  "office-cleaning": {
    slug: "office-cleaning",
    title: "Office Cleaning",
    shortTitle: "Office Cleaning",
    parentSlug: "cleaning",
    description:
      "Office and small commercial cleaning for workspaces, restrooms, breakrooms, reception areas, desks, floors, and recurring janitorial needs.",
    commonProblems: [
      "Recurring office cleaning",
      "Restroom cleaning",
      "Breakroom cleaning",
      "Reception area cleaning",
      "Trash removal",
      "After-hours cleaning",
    ],
    priceMin: 150,
    priceMax: 900,
    priceUnit: "flat",
    relatedSlugs: [
      "commercial-cleaning",
      "janitorial-services",
      "floor-cleaning",
    ],
    formFields: [
      "business_type",
      "square_feet",
      "cleaning_frequency",
      "number_of_restrooms",
      "preferred_time",
      "access_instructions",
      "description",
      "photos",
    ],
  },

  "commercial-cleaning": {
    slug: "commercial-cleaning",
    title: "Commercial Cleaning",
    shortTitle: "Commercial Cleaning",
    parentSlug: "cleaning",
    description:
      "Commercial cleaning for local businesses, retail spaces, offices, studios, clinics, and shared work areas that need reliable scheduled cleaning.",
    commonProblems: [
      "Business cleaning",
      "Retail cleaning",
      "Clinic cleaning",
      "Studio cleaning",
      "Customer-facing space cleaning",
      "Recurring commercial cleaning",
    ],
    priceMin: 180,
    priceMax: 1500,
    priceUnit: "flat",
    relatedSlugs: [
      "office-cleaning",
      "janitorial-services",
      "floor-cleaning",
    ],
    formFields: [
      "business_type",
      "square_feet",
      "cleaning_frequency",
      "areas_to_clean",
      "preferred_time",
      "access_instructions",
      "description",
      "photos",
    ],
  },

  "janitorial-services": {
    slug: "janitorial-services",
    title: "Janitorial Services",
    shortTitle: "Janitorial",
    parentSlug: "cleaning",
    description:
      "Recurring janitorial services for offices, commercial spaces, common areas, restrooms, breakrooms, trash removal, and routine facility upkeep.",
    commonProblems: [
      "Nightly janitorial service",
      "Weekly janitorial service",
      "Restroom restocking",
      "Trash and common area cleaning",
      "Breakroom cleaning",
      "Commercial floor upkeep",
    ],
    priceMin: 250,
    priceMax: 2500,
    priceUnit: "flat",
    relatedSlugs: [
      "office-cleaning",
      "commercial-cleaning",
      "floor-cleaning",
    ],
    formFields: [
      "facility_type",
      "square_feet",
      "cleaning_frequency",
      "number_of_restrooms",
      "supply_restocking_needed",
      "preferred_time",
      "description",
      "photos",
    ],
  },

  "airbnb-vacation-rental-cleaning": {
    slug: "airbnb-vacation-rental-cleaning",
    title: "Airbnb & Vacation Rental Cleaning",
    shortTitle: "Airbnb Cleaning",
    parentSlug: "cleaning",
    description:
      "Turnover cleaning for Airbnb, short-term rentals, and vacation rentals, including guest-ready cleaning, linens, bathrooms, kitchens, and reset tasks.",
    commonProblems: [
      "Same-day guest turnover",
      "Vacation rental cleaning",
      "Airbnb cleaning checklist",
      "Linens and towels reset",
      "Kitchen and bathroom reset",
      "Cleaning between guests",
    ],
    priceMin: 120,
    priceMax: 500,
    priceUnit: "flat",
    relatedSlugs: [
      "residential-cleaning",
      "laundry-service",
      "deep-cleaning",
    ],
    formFields: [
      "property_type",
      "bedrooms",
      "bathrooms",
      "turnover_date",
      "checkout_time",
      "checkin_time",
      "linen_service_needed",
      "supplies_restocking_needed",
      "description",
      "photos",
    ],
  },

  "carpet-cleaning": {
    slug: "carpet-cleaning",
    title: "Carpet Cleaning",
    shortTitle: "Carpet Cleaning",
    parentSlug: "cleaning",
    description:
      "Carpet cleaning for stains, odors, pet messes, high-traffic areas, move-out cleaning, and routine carpet maintenance.",
    commonProblems: [
      "Carpet stains",
      "Pet odor",
      "High-traffic carpet dirt",
      "Move-out carpet cleaning",
      "Area rug cleaning",
      "Carpet refresh before guests",
    ],
    priceMin: 120,
    priceMax: 600,
    priceUnit: "flat",
    relatedSlugs: [
      "upholstery-cleaning",
      "floor-cleaning",
      "pet-stain-odor-removal",
    ],
    formFields: [
      "number_of_rooms",
      "carpet_condition",
      "stain_type",
      "pets",
      "stairs",
      "preferred_date",
      "description",
      "photos",
    ],
  },

  "upholstery-cleaning": {
    slug: "upholstery-cleaning",
    title: "Upholstery Cleaning",
    shortTitle: "Upholstery",
    parentSlug: "cleaning",
    description:
      "Upholstery cleaning for sofas, sectionals, chairs, cushions, dining chairs, fabric furniture, pet odor, spills, and stains.",
    commonProblems: [
      "Sofa cleaning",
      "Sectional cleaning",
      "Pet odor on furniture",
      "Food or drink stains",
      "Dusty upholstery",
      "Dining chair cleaning",
    ],
    priceMin: 100,
    priceMax: 500,
    priceUnit: "flat",
    relatedSlugs: [
      "carpet-cleaning",
      "pet-stain-odor-removal",
      "residential-cleaning",
    ],
    formFields: [
      "furniture_type",
      "number_of_items",
      "fabric_type",
      "stain_type",
      "pets",
      "description",
      "photos",
    ],
  },

  "floor-cleaning": {
    slug: "floor-cleaning",
    title: "Floor Cleaning",
    shortTitle: "Floor Cleaning",
    parentSlug: "cleaning",
    description:
      "Floor cleaning for tile, vinyl, laminate, hardwood-safe cleaning, commercial floors, grout lines, and high-traffic areas.",
    commonProblems: [
      "Dirty tile floors",
      "Sticky floors",
      "High-traffic floor buildup",
      "Grout discoloration",
      "Commercial floor cleaning",
      "Move-out floor cleaning",
    ],
    priceMin: 150,
    priceMax: 900,
    priceUnit: "sqft",
    relatedSlugs: [
      "tile-grout-cleaning",
      "commercial-cleaning",
      "deep-cleaning",
    ],
    formFields: [
      "floor_type",
      "square_feet",
      "condition",
      "grout_cleaning_needed",
      "furniture_moving_needed",
      "description",
      "photos",
    ],
  },

  "tile-grout-cleaning": {
    slug: "tile-grout-cleaning",
    title: "Tile & Grout Cleaning",
    shortTitle: "Tile & Grout",
    parentSlug: "cleaning",
    description:
      "Tile and grout cleaning for bathrooms, kitchens, showers, floors, backsplashes, stains, discoloration, and buildup.",
    commonProblems: [
      "Dirty grout lines",
      "Shower tile buildup",
      "Kitchen tile cleaning",
      "Bathroom floor cleaning",
      "Grout discoloration",
      "Soap scum and mineral buildup",
    ],
    priceMin: 150,
    priceMax: 800,
    priceUnit: "sqft",
    relatedSlugs: [
      "floor-cleaning",
      "deep-cleaning",
      "bathroom-cleaning",
    ],
    formFields: [
      "tile_area",
      "square_feet",
      "grout_condition",
      "room_type",
      "sealing_needed",
      "description",
      "photos",
    ],
  },

  "window-cleaning": {
    slug: "window-cleaning",
    title: "Window Cleaning",
    shortTitle: "Window Cleaning",
    parentSlug: "cleaning",
    description:
      "Interior and exterior window cleaning for homes, apartments, storefronts, glass doors, tracks, screens, and hard-to-reach windows.",
    commonProblems: [
      "Dirty exterior windows",
      "Interior window cleaning",
      "Glass door cleaning",
      "Window track cleaning",
      "Screen cleaning",
      "Second-story windows",
    ],
    priceMin: 120,
    priceMax: 700,
    priceUnit: "flat",
    relatedSlugs: [
      "residential-cleaning",
      "commercial-cleaning",
      "gutter-cleaning",
    ],
    formFields: [
      "number_of_windows",
      "stories",
      "interior_exterior",
      "screens_needed",
      "tracks_needed",
      "access_notes",
      "description",
      "photos",
    ],
  },

  "gutter-cleaning": {
    slug: "gutter-cleaning",
    title: "Gutter Cleaning",
    shortTitle: "Gutter Cleaning",
    parentSlug: "cleaning",
    description:
      "Gutter cleaning for leaves, clogs, downspouts, overflow issues, roofline debris, and routine seasonal maintenance.",
    commonProblems: [
      "Clogged gutters",
      "Overflowing gutters",
      "Leaves in gutters",
      "Downspout blockage",
      "Seasonal gutter cleaning",
      "Water spilling near foundation",
    ],
    priceMin: 100,
    priceMax: 450,
    priceUnit: "flat",
    relatedSlugs: [
      "roof-maintenance",
      "exterior-pressure-washing-cleaning",
      "general-maintenance",
    ],
    formFields: [
      "home_stories",
      "gutter_length_estimate",
      "downspout_issue",
      "roof_access",
      "last_cleaned",
      "description",
      "photos",
    ],
  },

  "exterior-pressure-washing-cleaning": {
  slug: "exterior-pressure-washing-cleaning",
    title: "Pressure Washing",
    shortTitle: "Pressure Washing",
    parentSlug: "cleaning",
    description:
      "Pressure washing and exterior surface cleaning for driveways, sidewalks, patios, decks, siding, fences, and outdoor areas.",
    commonProblems: [
      "Dirty driveway",
      "Mold on siding",
      "Patio buildup",
      "Deck cleaning",
      "Sidewalk stains",
      "Fence cleaning",
    ],
    priceMin: 150,
    priceMax: 900,
    priceUnit: "sqft",
    relatedSlugs: [
      "window-cleaning",
      "gutter-cleaning",
      "deck-repair",
    ],
    formFields: [
      "surface_type",
      "square_feet",
      "stain_type",
      "water_access",
      "surface_condition",
      "description",
      "photos",
    ],
  },

  "dryer-vent-cleaning": {
    slug: "dryer-vent-cleaning",
    title: "Dryer Vent Cleaning",
    shortTitle: "Dryer Vent",
    parentSlug: "cleaning",
    description:
      "Dryer vent cleaning to remove lint buildup, improve dryer performance, reduce overheating, and support safer appliance operation.",
    commonProblems: [
      "Dryer takes too long",
      "Burning smell near dryer",
      "Lint buildup",
      "Dryer overheating",
      "Exterior vent blocked",
      "Annual dryer vent cleaning",
    ],
    priceMin: 100,
    priceMax: 300,
    priceUnit: "flat",
    relatedSlugs: [
      "appliance-maintenance",
      "washer-dryer-repair-installation",
      "residential-cleaning",
    ],
    formFields: [
      "dryer_location",
      "vent_location",
      "dryer_symptoms",
      "last_cleaned",
      "access_notes",
      "description",
      "photos",
    ],
  },

  "pet-stain-odor-removal": {
    slug: "pet-stain-odor-removal",
    title: "Pet Stain & Odor Removal",
    shortTitle: "Pet Odor Removal",
    parentSlug: "cleaning",
    description:
      "Cleaning for pet stains, odors, urine spots, carpet odor, upholstery odor, and home refresh after pet accidents.",
    commonProblems: [
      "Pet urine odor",
      "Carpet pet stains",
      "Upholstery pet smell",
      "Recurring pet odor",
      "Move-out pet cleaning",
      "Stains before guests arrive",
    ],
    priceMin: 120,
    priceMax: 650,
    priceUnit: "flat",
    relatedSlugs: [
      "carpet-cleaning",
      "upholstery-cleaning",
      "deep-cleaning",
    ],
    formFields: [
      "affected_areas",
      "surface_type",
      "number_of_spots",
      "odor_level",
      "pets",
      "description",
      "photos",
    ],
  },

  "laundry-service": {
    slug: "laundry-service",
    title: "Laundry Service",
    shortTitle: "Laundry",
    parentSlug: "cleaning",
    description:
      "Wash, dry, fold, linen reset, towel service, and laundry support for homes, short-term rentals, and busy households.",
    commonProblems: [
      "Wash and fold service",
      "Linens and towels",
      "Airbnb laundry turnover",
      "Family laundry backlog",
      "Bedding cleaning",
      "Laundry pickup coordination",
    ],
    priceMin: 60,
    priceMax: 300,
    priceUnit: "flat",
    relatedSlugs: [
      "airbnb-vacation-rental-cleaning",
      "maid-service",
      "residential-cleaning",
    ],
    formFields: [
      "laundry_amount",
      "pickup_needed",
      "detergent_preferences",
      "turnaround_time",
      "linen_service",
      "description",
      "photos",
    ],
  },

  "bathroom-cleaning": {
    slug: "bathroom-cleaning",
    title: "Bathroom Cleaning",
    shortTitle: "Bathroom Cleaning",
    parentSlug: "cleaning",
    description:
      "Bathroom cleaning for showers, tubs, toilets, sinks, mirrors, fixtures, tile, grout, soap scum, hard water buildup, and sanitizing.",
    commonProblems: [
      "Soap scum buildup",
      "Hard water marks",
      "Dirty shower tile",
      "Toilet and sink cleaning",
      "Bathroom odor",
      "Guest bathroom reset",
    ],
    priceMin: 80,
    priceMax: 300,
    priceUnit: "flat",
    relatedSlugs: [
      "deep-cleaning",
      "tile-grout-cleaning",
      "residential-cleaning",
    ],
    formFields: [
      "number_of_bathrooms",
      "bathroom_condition",
      "tile_grout_needed",
      "hard_water_buildup",
      "priority_areas",
      "description",
      "photos",
    ],
  },

  "kitchen-cleaning": {
    slug: "kitchen-cleaning",
    title: "Kitchen Cleaning",
    shortTitle: "Kitchen Cleaning",
    parentSlug: "cleaning",
    description:
      "Kitchen cleaning for counters, sinks, stovetops, appliance exteriors, cabinet fronts, floors, grease buildup, and food-prep areas.",
    commonProblems: [
      "Grease buildup",
      "Stovetop cleaning",
      "Sink and counter cleaning",
      "Cabinet front cleaning",
      "Kitchen floor cleaning",
      "Cleaning before hosting",
    ],
    priceMin: 90,
    priceMax: 350,
    priceUnit: "flat",
    relatedSlugs: [
      "deep-cleaning",
      "residential-cleaning",
      "appliance-maintenance",
    ],
    formFields: [
      "kitchen_condition",
      "appliance_exterior_cleaning",
      "inside_appliances_needed",
      "grease_level",
      "priority_areas",
      "description",
      "photos",
    ],
  },

  "garage-cleaning": {
    slug: "garage-cleaning",
    title: "Garage Cleaning",
    shortTitle: "Garage Cleaning",
    parentSlug: "cleaning",
    description:
      "Garage cleaning for dust, dirt, cobwebs, floor sweeping, light organization, move-out cleanup, and pre-sale home preparation.",
    commonProblems: [
      "Dusty garage",
      "Cobwebs",
      "Garage floor dirt",
      "Move-out garage cleaning",
      "Pre-sale garage cleanup",
      "Light organization needed",
    ],
    priceMin: 120,
    priceMax: 600,
    priceUnit: "flat",
    relatedSlugs: [
      "junk-removal",
      "exterior-pressure-washing-cleaning",
      "move-out-cleaning",
    ],
    formFields: [
      "garage_size",
      "level_of_clutter",
      "junk_removal_needed",
      "floor_cleaning_needed",
      "description",
      "photos",
    ],
  },
};