import type { SubcategoryMap } from "../types";

export const electricalSubcategories: SubcategoryMap = {
  "outlet-switch-repair-installation": {
    slug: "outlet-switch-repair-installation",
    title: "Outlet & Switch Repair / Installation",
    shortTitle: "Outlets & Switches",
    parentSlug: "electrical",
    description: "Repair, replace, or install outlets, switches, dimmers, GFCI outlets, and smart switches.",
    commonProblems: [
      "Outlet not working",
      "Loose outlet",
      "Light switch not working",
      "GFCI keeps tripping",
      "Dimmer switch install",
      "Smart switch installation",
    ],
    priceMin: 90,
    priceMax: 350,
    priceUnit: "flat",
    relatedSlugs: ["wiring-repair-troubleshooting", "breaker-panel-repair", "light-fixture-installation"],
    formFields: ["electrical_issue", "device_type", "description", "photos"],
  },

  "light-fixture-installation": {
    slug: "light-fixture-installation",
    title: "Light Fixture Installation",
    shortTitle: "Light Fixtures",
    parentSlug: "electrical",
    description: "Install or replace ceiling lights, chandeliers, pendants, vanity lights, and other fixtures.",
    commonProblems: [
      "Ceiling light replacement",
      "Chandelier installation",
      "Pendant light install",
      "Vanity light replacement",
      "Old fixture removal",
      "Fixture not working",
    ],
    priceMin: 100,
    priceMax: 500,
    priceUnit: "flat",
    relatedSlugs: ["ceiling-fan-installation", "outlet-switch-repair-installation", "wiring-repair-troubleshooting"],
    formFields: ["fixture_type", "ceiling_height", "description", "photos"],
  },

  "ceiling-fan-installation": {
    slug: "ceiling-fan-installation",
    title: "Ceiling Fan Installation",
    shortTitle: "Ceiling Fans",
    parentSlug: "electrical",
    description: "Install, replace, wire, or troubleshoot ceiling fans, fan lights, remotes, and wall controls.",
    commonProblems: [
      "New ceiling fan install",
      "Replace old ceiling fan",
      "Fan wobbles",
      "Fan light not working",
      "Remote control setup",
      "Replace light with fan",
    ],
    priceMin: 125,
    priceMax: 550,
    priceUnit: "flat",
    relatedSlugs: ["light-fixture-installation", "wiring-repair-troubleshooting", "outlet-switch-repair-installation"],
    formFields: ["fan_type", "ceiling_height", "description", "photos"],
  },

  "breaker-panel-repair": {
    slug: "breaker-panel-repair",
    title: "Breaker & Panel Repair",
    shortTitle: "Breakers & Panels",
    parentSlug: "electrical",
    description: "Troubleshoot tripping breakers, panel issues, partial power loss, circuit problems, and breaker replacement needs.",
    commonProblems: [
      "Breaker keeps tripping",
      "Partial power outage",
      "Panel buzzing",
      "Breaker replacement",
      "Circuit overload",
      "Electrical panel issue",
    ],
    priceMin: 150,
    priceMax: 1200,
    priceUnit: "flat",
    relatedSlugs: ["wiring-repair-troubleshooting", "electrical-safety-inspection", "ev-charger-installation"],
    formFields: ["panel_issue", "symptom", "description", "photos"],
  },

  "wiring-repair-troubleshooting": {
    slug: "wiring-repair-troubleshooting",
    title: "Wiring Repair & Electrical Troubleshooting",
    shortTitle: "Wiring Repair",
    parentSlug: "electrical",
    description: "Find and repair wiring issues, flickering lights, non-working circuits, power problems, and electrical faults.",
    commonProblems: [
      "Flickering lights",
      "Outlet stopped working",
      "Power issue in one room",
      "Faulty wiring",
      "Buzzing switch",
      "Electrical troubleshooting",
    ],
    priceMin: 125,
    priceMax: 800,
    priceUnit: "flat",
    relatedSlugs: ["breaker-panel-repair", "outlet-switch-repair-installation", "electrical-safety-inspection"],
    formFields: ["symptom", "affected_area", "description", "photos"],
  },

  "ev-charger-installation": {
    slug: "ev-charger-installation",
    title: "EV Charger Installation",
    shortTitle: "EV Charger",
    parentSlug: "electrical",
    description: "Install Level 2 home EV chargers, Tesla chargers, dedicated circuits, and outdoor or garage charging stations.",
    commonProblems: [
      "Level 2 charger install",
      "Tesla charger installation",
      "Garage EV charger",
      "Outdoor EV charger",
      "Dedicated circuit needed",
      "Panel capacity check",
    ],
    priceMin: 500,
    priceMax: 2500,
    priceUnit: "flat",
    relatedSlugs: ["breaker-panel-repair", "electrical-safety-inspection", "wiring-repair-troubleshooting"],
    formFields: ["charger_type", "panel_location", "charger_location", "description", "photos"],
  },

  "electrical-safety-inspection": {
    slug: "electrical-safety-inspection",
    title: "Electrical Safety Inspection",
    shortTitle: "Safety Inspection",
    parentSlug: "electrical",
    description: "Request an electrical safety inspection for home purchases, rentals, old wiring, panels, outlets, and recurring electrical issues.",
    commonProblems: [
      "Home electrical inspection",
      "Old wiring concern",
      "Repeated breaker issues",
      "Buying a home",
      "Rental property inspection",
      "Safety concern",
    ],
    priceMin: 150,
    priceMax: 600,
    priceUnit: "flat",
    relatedSlugs: ["breaker-panel-repair", "wiring-repair-troubleshooting", "outlet-switch-repair-installation"],
    formFields: ["inspection_reason", "property_type", "description", "photos"],
  },

  "smoke-detector-installation": {
    slug: "smoke-detector-installation",
    title: "Smoke & CO Detector Installation",
    shortTitle: "Smoke Detectors",
    parentSlug: "electrical",
    description: "Install or replace smoke detectors, carbon monoxide detectors, hardwired alarms, and safety devices.",
    commonProblems: [
      "Smoke detector replacement",
      "Hardwired alarm replacement",
      "Carbon monoxide detector install",
      "Detector beeping",
      "Expired detector",
      "Rental safety update",
    ],
    priceMin: 90,
    priceMax: 400,
    priceUnit: "flat",
    relatedSlugs: ["electrical-safety-inspection", "outlet-switch-repair-installation", "wiring-repair-troubleshooting"],
    formFields: ["detector_type", "quantity", "description", "photos"],
  },
};