import type { SubcategoryMap } from "../types";

export const fenceSubcategories: SubcategoryMap = {
  "fence-repair": {
    slug: "fence-repair",
    title: "Fence Repair",
    shortTitle: "Fence Repair",
    parentSlug: "fence",
    description:
      "Fence repair for leaning sections, broken boards, loose panels, damaged posts, gate problems, storm damage, and worn fencing.",
    commonProblems: [
      "Leaning fence section",
      "Broken fence boards",
      "Loose fence panels",
      "Damaged fence posts",
      "Storm-damaged fence",
      "Fence pulling away from gate",
    ],
    priceMin: 150,
    priceMax: 2500,
    priceUnit: "flat",
    relatedSlugs: [
      "wood-fence-repair",
      "vinyl-fence-repair",
      "fence-post-repair",
      "gate-repair",
    ],
    formFields: [
      "Fence material",
      "Damaged area length",
      "Issue type",
      "Photos",
      "Access instructions",
      "Urgency",
    ],
  },

  "fence-installation": {
    slug: "fence-installation",
    title: "Fence Installation",
    shortTitle: "Fence Installation",
    parentSlug: "fence",
    description:
      "Fence installation for backyards, side yards, privacy, pets, pools, property boundaries, and residential or small commercial properties.",
    commonProblems: [
      "Need new fence installed",
      "Need backyard privacy",
      "Need pet containment",
      "Old fence replacement",
      "Fence for property boundary",
      "New home fence project",
    ],
    priceMin: 1200,
    priceMax: 15000,
    priceUnit: "flat",
    relatedSlugs: [
      "privacy-fence-installation",
      "wood-fence-installation",
      "vinyl-fence-installation",
      "chain-link-fence-installation",
    ],
    formFields: [
      "Fence material preference",
      "Approximate linear feet",
      "Fence height",
      "Gate count",
      "Property access",
      "Project timing",
    ],
  },

  "privacy-fence-installation": {
    slug: "privacy-fence-installation",
    title: "Privacy Fence Installation",
    shortTitle: "Privacy Fence",
    parentSlug: "fence",
    description:
      "Privacy fence installation for yards, patios, pools, side yards, and outdoor spaces where homeowners want more separation and security.",
    commonProblems: [
      "Need backyard privacy",
      "Neighbor visibility issue",
      "Pool privacy needed",
      "Street-facing yard exposure",
      "Outdoor living area needs screening",
      "Old privacy fence replacement",
    ],
    priceMin: 1800,
    priceMax: 18000,
    priceUnit: "flat",
    relatedSlugs: [
      "fence-installation",
      "wood-fence-installation",
      "vinyl-fence-installation",
      "fence-replacement",
    ],
    formFields: [
      "Desired height",
      "Material preference",
      "Approximate linear feet",
      "Privacy goal",
      "Gate needs",
      "Timeline",
    ],
  },

  "wood-fence-installation": {
    slug: "wood-fence-installation",
    title: "Wood Fence Installation",
    shortTitle: "Wood Fence",
    parentSlug: "fence",
    description:
      "Wood fence installation for privacy fences, picket fences, backyard fencing, side-yard fencing, and custom residential fence layouts.",
    commonProblems: [
      "Need new wood fence",
      "Need custom fence layout",
      "Old wood fence replacement",
      "Backyard privacy project",
      "Fence around pets or children",
      "Damaged wood fence beyond repair",
    ],
    priceMin: 1500,
    priceMax: 16000,
    priceUnit: "flat",
    relatedSlugs: [
      "wood-fence-repair",
      "privacy-fence-installation",
      "fence-replacement",
      "fence-staining-sealing",
    ],
    formFields: [
      "Wood style",
      "Linear feet",
      "Fence height",
      "Gate count",
      "Removal needed",
      "Site conditions",
    ],
  },

  "wood-fence-repair": {
    slug: "wood-fence-repair",
    title: "Wood Fence Repair",
    shortTitle: "Wood Fence Repair",
    parentSlug: "fence",
    description:
      "Wood fence repair for broken pickets, rails, posts, rot, leaning sections, missing boards, loose gates, and storm damage.",
    commonProblems: [
      "Broken wood boards",
      "Rotten fence posts",
      "Loose rails",
      "Missing pickets",
      "Leaning wood fence",
      "Gate dragging or sagging",
    ],
    priceMin: 150,
    priceMax: 3000,
    priceUnit: "flat",
    relatedSlugs: [
      "fence-repair",
      "fence-post-repair",
      "gate-repair",
      "fence-staining-sealing",
    ],
    formFields: [
      "Damaged parts",
      "Wood type if known",
      "Number of sections",
      "Photos",
      "Access",
      "Urgency",
    ],
  },

  "vinyl-fence-installation": {
    slug: "vinyl-fence-installation",
    title: "Vinyl Fence Installation",
    shortTitle: "Vinyl Fence",
    parentSlug: "fence",
    description:
      "Vinyl fence installation for low-maintenance privacy, pool fencing, side yards, residential boundaries, and clean modern fence projects.",
    commonProblems: [
      "Need low-maintenance fence",
      "Need white vinyl privacy fence",
      "Replacing old wood fence",
      "Need pool or yard enclosure",
      "Want long-lasting fence material",
      "Need clean modern fence look",
    ],
    priceMin: 2200,
    priceMax: 20000,
    priceUnit: "flat",
    relatedSlugs: [
      "vinyl-fence-repair",
      "privacy-fence-installation",
      "fence-installation",
      "fence-replacement",
    ],
    formFields: [
      "Vinyl style",
      "Linear feet",
      "Fence height",
      "Gate count",
      "Removal needed",
      "Timeline",
    ],
  },

  "vinyl-fence-repair": {
    slug: "vinyl-fence-repair",
    title: "Vinyl Fence Repair",
    shortTitle: "Vinyl Fence Repair",
    parentSlug: "fence",
    description:
      "Vinyl fence repair for cracked panels, loose posts, damaged rails, missing caps, leaning sections, and gate alignment problems.",
    commonProblems: [
      "Cracked vinyl panel",
      "Loose vinyl fence post",
      "Missing post cap",
      "Damaged vinyl rail",
      "Leaning vinyl section",
      "Vinyl gate not closing",
    ],
    priceMin: 175,
    priceMax: 2500,
    priceUnit: "flat",
    relatedSlugs: [
      "fence-repair",
      "fence-post-repair",
      "gate-repair",
      "vinyl-fence-installation",
    ],
    formFields: [
      "Damaged vinyl part",
      "Fence color",
      "Panel style",
      "Photos",
      "Access",
      "Urgency",
    ],
  },

  "chain-link-fence-installation": {
    slug: "chain-link-fence-installation",
    title: "Chain Link Fence Installation",
    shortTitle: "Chain Link Fence",
    parentSlug: "fence",
    description:
      "Chain link fence installation for yards, pets, utility areas, side yards, commercial spaces, and affordable boundary fencing.",
    commonProblems: [
      "Need affordable fence",
      "Need pet containment",
      "Need utility area enclosure",
      "Need commercial perimeter fence",
      "Need side-yard fence",
      "Need durable boundary fence",
    ],
    priceMin: 1000,
    priceMax: 12000,
    priceUnit: "flat",
    relatedSlugs: [
      "chain-link-fence-repair",
      "fence-installation",
      "commercial-fence-installation",
      "gate-installation",
    ],
    formFields: [
      "Fence height",
      "Linear feet",
      "Coated or galvanized",
      "Gate count",
      "Property type",
      "Timeline",
    ],
  },

  "chain-link-fence-repair": {
    slug: "chain-link-fence-repair",
    title: "Chain Link Fence Repair",
    shortTitle: "Chain Link Repair",
    parentSlug: "fence",
    description:
      "Chain link fence repair for damaged mesh, bent rails, leaning posts, loose tension wire, broken gates, and storm-damaged sections.",
    commonProblems: [
      "Bent chain link rail",
      "Damaged fence mesh",
      "Leaning metal post",
      "Loose tension wire",
      "Broken chain link gate",
      "Fence cut or pulled open",
    ],
    priceMin: 150,
    priceMax: 2500,
    priceUnit: "flat",
    relatedSlugs: [
      "fence-repair",
      "fence-post-repair",
      "gate-repair",
      "chain-link-fence-installation",
    ],
    formFields: [
      "Damage type",
      "Fence height",
      "Damaged length",
      "Photos",
      "Access",
      "Urgency",
    ],
  },

  "fence-post-repair": {
    slug: "fence-post-repair",
    title: "Fence Post Repair",
    shortTitle: "Fence Post Repair",
    parentSlug: "fence",
    description:
      "Fence post repair and replacement for leaning, rotten, broken, loose, or unstable posts that affect fence strength and alignment.",
    commonProblems: [
      "Leaning fence post",
      "Rotten wood post",
      "Broken post at ground level",
      "Loose post in concrete",
      "Gate post failing",
      "Fence section unstable",
    ],
    priceMin: 175,
    priceMax: 1800,
    priceUnit: "flat",
    relatedSlugs: [
      "fence-repair",
      "wood-fence-repair",
      "vinyl-fence-repair",
      "gate-repair",
    ],
    formFields: [
      "Post material",
      "Number of posts",
      "Fence material",
      "Access",
      "Photos",
      "Urgency",
    ],
  },

  "gate-repair": {
    slug: "gate-repair",
    title: "Fence Gate Repair",
    shortTitle: "Gate Repair",
    parentSlug: "fence",
    description:
      "Fence gate repair for sagging gates, broken hinges, latch problems, dragging gates, misalignment, post issues, and storm damage.",
    commonProblems: [
      "Gate sagging",
      "Gate dragging on ground",
      "Broken hinge",
      "Latch not closing",
      "Gate post leaning",
      "Double gate misaligned",
    ],
    priceMin: 125,
    priceMax: 1500,
    priceUnit: "flat",
    relatedSlugs: [
      "gate-installation",
      "fence-post-repair",
      "fence-repair",
      "wood-fence-repair",
    ],
    formFields: [
      "Gate material",
      "Gate size",
      "Issue type",
      "Hardware condition",
      "Photos",
      "Urgency",
    ],
  },

  "gate-installation": {
    slug: "gate-installation",
    title: "Fence Gate Installation",
    shortTitle: "Gate Installation",
    parentSlug: "fence",
    description:
      "Fence gate installation for walk gates, driveway gates, side-yard gates, pet access, privacy fences, and replacement gate projects.",
    commonProblems: [
      "Need new walk gate",
      "Need side-yard gate",
      "Need driveway gate",
      "Replacing broken gate",
      "Need wider access",
      "Need gate for privacy fence",
    ],
    priceMin: 300,
    priceMax: 4000,
    priceUnit: "flat",
    relatedSlugs: [
      "gate-repair",
      "fence-installation",
      "privacy-fence-installation",
      "fence-post-repair",
    ],
    formFields: [
      "Gate type",
      "Gate width",
      "Fence material",
      "Hardware preference",
      "Post condition",
      "Timeline",
    ],
  },

  "fence-replacement": {
    slug: "fence-replacement",
    title: "Fence Replacement",
    shortTitle: "Fence Replacement",
    parentSlug: "fence",
    description:
      "Fence replacement for old, damaged, leaning, rotted, storm-damaged, or outdated fencing that is no longer worth repairing.",
    commonProblems: [
      "Old fence falling apart",
      "Fence too damaged to repair",
      "Multiple leaning sections",
      "Rot throughout wood fence",
      "Storm-damaged fence line",
      "Want different fence material",
    ],
    priceMin: 1800,
    priceMax: 22000,
    priceUnit: "flat",
    relatedSlugs: [
      "fence-installation",
      "privacy-fence-installation",
      "wood-fence-installation",
      "vinyl-fence-installation",
    ],
    formFields: [
      "Current fence material",
      "New material preference",
      "Linear feet",
      "Removal needed",
      "Gate count",
      "Timeline",
    ],
  },

  "fence-staining-sealing": {
    slug: "fence-staining-sealing",
    title: "Fence Staining & Sealing",
    shortTitle: "Fence Staining",
    parentSlug: "fence",
    description:
      "Fence staining and sealing for wood fences that need color refresh, weather protection, UV protection, and longer service life.",
    commonProblems: [
      "Fence looks faded",
      "Wood fence needs protection",
      "New fence needs sealing",
      "Fence has weather discoloration",
      "Want darker or refreshed color",
      "Need maintenance before damage spreads",
    ],
    priceMin: 400,
    priceMax: 4500,
    priceUnit: "flat",
    relatedSlugs: [
      "wood-fence-repair",
      "wood-fence-installation",
      "fence-maintenance",
      "fence-repair",
    ],
    formFields: [
      "Fence material",
      "Approximate linear feet",
      "Current condition",
      "Stain or seal preference",
      "Cleaning needed",
      "Timeline",
    ],
  },

  "fence-maintenance": {
    slug: "fence-maintenance",
    title: "Fence Maintenance",
    shortTitle: "Fence Maintenance",
    parentSlug: "fence",
    description:
      "Fence maintenance for inspections, loose hardware, minor repairs, staining, sealing, cleaning coordination, and seasonal upkeep.",
    commonProblems: [
      "Fence needs inspection",
      "Loose hardware",
      "Minor fence wear",
      "Preventive maintenance needed",
      "Fence needs seasonal care",
      "Small issues before replacement",
    ],
    priceMin: 150,
    priceMax: 2500,
    priceUnit: "flat",
    relatedSlugs: [
      "fence-repair",
      "fence-staining-sealing",
      "gate-repair",
      "fence-post-repair",
    ],
    formFields: [
      "Fence material",
      "Maintenance needs",
      "Fence age",
      "Photos",
      "Access",
      "Timeline",
    ],
  },

  "commercial-fence-installation": {
    slug: "commercial-fence-installation",
    title: "Commercial Fence Installation",
    shortTitle: "Commercial Fence",
    parentSlug: "fence",
    description:
      "Commercial fence installation for small businesses, rental properties, storage areas, offices, utility areas, and perimeter control.",
    commonProblems: [
      "Need business perimeter fence",
      "Need security fence",
      "Need dumpster enclosure",
      "Need rental property fence",
      "Need utility area enclosure",
      "Need commercial gate access",
    ],
    priceMin: 2500,
    priceMax: 35000,
    priceUnit: "flat",
    relatedSlugs: [
      "chain-link-fence-installation",
      "gate-installation",
      "fence-replacement",
      "fence-repair",
    ],
    formFields: [
      "Property type",
      "Fence purpose",
      "Linear feet",
      "Fence height",
      "Gate requirements",
      "Access restrictions",
    ],
  },
};