import type { SubcategoryMap } from "../types";

export const flooringSubcategories: SubcategoryMap = {
  "flooring-installation": {
    slug: "flooring-installation",
    title: "Flooring Installation",
    shortTitle: "Floor Install",
    parentSlug: "flooring",
    description:
      "Flooring installation for homes and businesses, including planning, material fit, subfloor review, transitions, trim, and finished floor installation.",
    commonProblems: [
      "Old flooring replacement",
      "New floor installation",
      "Uneven subfloor",
      "Loose transitions",
      "Room-to-room flooring updates",
      "Rental property flooring upgrade",
    ],
    priceMin: 500,
    priceMax: 12000,
    priceUnit: "sqft",
    relatedSlugs: [
      "lvp-flooring-installation",
      "laminate-flooring-installation",
      "hardwood-flooring-installation",
      "tile-flooring-installation",
    ],
    formFields: [
      "flooring_type",
      "area_sqft",
      "rooms",
      "material_provided",
      "subfloor_condition",
      "description",
      "photos",
    ],
  },

  "flooring-repair": {
    slug: "flooring-repair",
    title: "Flooring Repair",
    shortTitle: "Floor Repair",
    parentSlug: "flooring",
    description:
      "Flooring repair for damaged planks, cracked tiles, loose boards, scratches, gaps, soft spots, transitions, and localized floor problems.",
    commonProblems: [
      "Loose or broken planks",
      "Cracked floor tiles",
      "Scratched flooring",
      "Water-damaged flooring",
      "Gaps between boards",
      "Soft or uneven floor areas",
    ],
    priceMin: 150,
    priceMax: 2500,
    priceUnit: "flat",
    relatedSlugs: [
      "lvp-flooring-repair",
      "hardwood-floor-repair",
      "tile-flooring-repair",
      "subfloor-repair",
    ],
    formFields: [
      "flooring_type",
      "damage_type",
      "area_size",
      "matching_material_available",
      "description",
      "photos",
    ],
  },

  "lvp-flooring-installation": {
    slug: "lvp-flooring-installation",
    title: "LVP Flooring Installation",
    shortTitle: "LVP Install",
    parentSlug: "flooring",
    description:
      "Luxury vinyl plank flooring installation for kitchens, living rooms, bedrooms, basements, rentals, offices, and moisture-prone spaces.",
    commonProblems: [
      "Old carpet replacement",
      "Rental flooring upgrade",
      "Water-resistant flooring need",
      "Click-lock plank installation",
      "Uneven floor preparation",
      "Transition and trim installation",
    ],
    priceMin: 600,
    priceMax: 9000,
    priceUnit: "sqft",
    relatedSlugs: [
      "flooring-installation",
      "lvp-flooring-repair",
      "flooring-removal",
      "baseboard-trim-installation",
    ],
    formFields: [
      "area_sqft",
      "rooms",
      "material_provided",
      "existing_flooring",
      "subfloor_condition",
      "baseboards_needed",
      "description",
      "photos",
    ],
  },

  "lvp-flooring-repair": {
    slug: "lvp-flooring-repair",
    title: "LVP Flooring Repair",
    shortTitle: "LVP Repair",
    parentSlug: "flooring",
    description:
      "LVP flooring repair for separated planks, damaged boards, lifting edges, scratches, water damage, bad transitions, and click-lock floor issues.",
    commonProblems: [
      "Separated LVP planks",
      "Damaged vinyl plank",
      "Lifting floor edges",
      "Scratched LVP flooring",
      "Loose transition strip",
      "Water-damaged plank area",
    ],
    priceMin: 150,
    priceMax: 1800,
    priceUnit: "flat",
    relatedSlugs: [
      "flooring-repair",
      "lvp-flooring-installation",
      "flooring-removal",
      "subfloor-repair",
    ],
    formFields: [
      "damage_type",
      "plank_count",
      "matching_material_available",
      "room",
      "description",
      "photos",
    ],
  },

  "laminate-flooring-installation": {
    slug: "laminate-flooring-installation",
    title: "Laminate Flooring Installation",
    shortTitle: "Laminate Install",
    parentSlug: "flooring",
    description:
      "Laminate flooring installation for bedrooms, living rooms, rental homes, offices, and budget-friendly floor replacement projects.",
    commonProblems: [
      "Old carpet replacement",
      "Budget flooring upgrade",
      "Floating floor installation",
      "Underlayment installation",
      "Door clearance issue",
      "Room transition installation",
    ],
    priceMin: 500,
    priceMax: 8000,
    priceUnit: "sqft",
    relatedSlugs: [
      "flooring-installation",
      "flooring-removal",
      "baseboard-trim-installation",
      "subfloor-repair",
    ],
    formFields: [
      "area_sqft",
      "rooms",
      "material_provided",
      "underlayment_needed",
      "existing_flooring",
      "description",
      "photos",
    ],
  },

  "hardwood-flooring-installation": {
    slug: "hardwood-flooring-installation",
    title: "Hardwood Flooring Installation",
    shortTitle: "Hardwood Install",
    parentSlug: "flooring",
    description:
      "Hardwood flooring installation for solid wood, engineered wood, nail-down, glue-down, and floating hardwood floor projects.",
    commonProblems: [
      "New hardwood floor installation",
      "Engineered wood installation",
      "Old floor replacement",
      "Wood floor layout planning",
      "Moisture or subfloor concern",
      "Trim and transition work",
    ],
    priceMin: 1200,
    priceMax: 25000,
    priceUnit: "sqft",
    relatedSlugs: [
      "hardwood-floor-refinishing",
      "hardwood-floor-repair",
      "flooring-removal",
      "subfloor-repair",
    ],
    formFields: [
      "wood_type",
      "area_sqft",
      "installation_method",
      "material_provided",
      "subfloor_condition",
      "description",
      "photos",
    ],
  },

  "hardwood-floor-repair": {
    slug: "hardwood-floor-repair",
    title: "Hardwood Floor Repair",
    shortTitle: "Hardwood Repair",
    parentSlug: "flooring",
    description:
      "Hardwood floor repair for damaged boards, squeaks, gaps, scratches, stains, cupping, localized water damage, and transition issues.",
    commonProblems: [
      "Scratched hardwood",
      "Loose or squeaky boards",
      "Water-damaged wood floor",
      "Gaps between boards",
      "Cupping or warping",
      "Damaged transition area",
    ],
    priceMin: 250,
    priceMax: 4500,
    priceUnit: "flat",
    relatedSlugs: [
      "hardwood-floor-refinishing",
      "hardwood-flooring-installation",
      "flooring-repair",
      "subfloor-repair",
    ],
    formFields: [
      "damage_type",
      "wood_type",
      "area_size",
      "matching_material_available",
      "description",
      "photos",
    ],
  },

  "hardwood-floor-refinishing": {
    slug: "hardwood-floor-refinishing",
    title: "Hardwood Floor Refinishing",
    shortTitle: "Floor Refinishing",
    parentSlug: "flooring",
    description:
      "Hardwood floor sanding, staining, sealing, and refinishing for worn, scratched, dull, or discolored wood floors.",
    commonProblems: [
      "Dull hardwood floors",
      "Surface scratches",
      "Old stain color",
      "Worn protective finish",
      "Pet stains",
      "Uneven sheen",
    ],
    priceMin: 1200,
    priceMax: 9000,
    priceUnit: "sqft",
    relatedSlugs: [
      "hardwood-floor-repair",
      "hardwood-flooring-installation",
      "flooring-repair",
      "flooring-inspection",
    ],
    formFields: [
      "area_sqft",
      "wood_type",
      "current_condition",
      "stain_change",
      "furniture_moving",
      "description",
      "photos",
    ],
  },

  "tile-flooring-installation": {
    slug: "tile-flooring-installation",
    title: "Tile Flooring Installation",
    shortTitle: "Tile Install",
    parentSlug: "flooring",
    description:
      "Tile flooring installation for bathrooms, kitchens, laundry rooms, entries, patios, and other areas needing durable floor surfaces.",
    commonProblems: [
      "Bathroom floor tile installation",
      "Kitchen tile floor",
      "Laundry room tile",
      "Cracked old tile replacement",
      "Tile layout planning",
      "Grout and transition work",
    ],
    priceMin: 800,
    priceMax: 18000,
    priceUnit: "sqft",
    relatedSlugs: [
      "tile-flooring-repair",
      "flooring-removal",
      "subfloor-repair",
      "bathroom-remodeling",
    ],
    formFields: [
      "area_sqft",
      "tile_type",
      "rooms",
      "material_provided",
      "existing_flooring",
      "subfloor_condition",
      "description",
      "photos",
    ],
  },

  "tile-flooring-repair": {
    slug: "tile-flooring-repair",
    title: "Tile Flooring Repair",
    shortTitle: "Tile Repair",
    parentSlug: "flooring",
    description:
      "Tile flooring repair for cracked tiles, loose tiles, grout problems, uneven tiles, chipped tile edges, and small tile replacement projects.",
    commonProblems: [
      "Cracked floor tile",
      "Loose tile",
      "Missing grout",
      "Chipped tile",
      "Uneven tile area",
      "Small tile replacement",
    ],
    priceMin: 175,
    priceMax: 2500,
    priceUnit: "flat",
    relatedSlugs: [
      "tile-flooring-installation",
      "flooring-repair",
      "subfloor-repair",
      "bathroom-remodeling",
    ],
    formFields: [
      "damage_type",
      "tile_count",
      "matching_tile_available",
      "room",
      "description",
      "photos",
    ],
  },

  "carpet-installation-replacement": {
    slug: "carpet-installation-replacement",
    title: "Carpet Installation & Replacement",
    shortTitle: "Carpet Install",
    parentSlug: "flooring",
    description:
      "Carpet installation and replacement for bedrooms, stairs, living rooms, rental units, offices, and comfort-focused flooring updates.",
    commonProblems: [
      "Old carpet replacement",
      "Bedroom carpet installation",
      "Stair carpet replacement",
      "Rental unit carpet update",
      "Carpet padding replacement",
      "Carpet transition issue",
    ],
    priceMin: 500,
    priceMax: 7000,
    priceUnit: "sqft",
    relatedSlugs: [
      "carpet-repair-stretching",
      "flooring-removal",
      "baseboard-trim-installation",
      "flooring-installation",
    ],
    formFields: [
      "area_sqft",
      "rooms",
      "stairs",
      "material_provided",
      "padding_needed",
      "existing_flooring",
      "description",
      "photos",
    ],
  },

  "carpet-repair-stretching": {
    slug: "carpet-repair-stretching",
    title: "Carpet Repair & Stretching",
    shortTitle: "Carpet Repair",
    parentSlug: "flooring",
    description:
      "Carpet repair and stretching for ripples, loose carpet, seams, small damaged areas, pet damage, burns, and transition problems.",
    commonProblems: [
      "Carpet wrinkles",
      "Loose carpet",
      "Damaged carpet patch",
      "Pet-damaged carpet",
      "Open carpet seam",
      "Carpet transition issue",
    ],
    priceMin: 125,
    priceMax: 1500,
    priceUnit: "flat",
    relatedSlugs: [
      "carpet-installation-replacement",
      "flooring-repair",
      "flooring-removal",
      "baseboard-trim-installation",
    ],
    formFields: [
      "repair_type",
      "room",
      "area_size",
      "matching_carpet_available",
      "description",
      "photos",
    ],
  },

  "flooring-removal": {
    slug: "flooring-removal",
    title: "Flooring Removal",
    shortTitle: "Floor Removal",
    parentSlug: "flooring",
    description:
      "Flooring removal for carpet, tile, laminate, vinyl, LVP, hardwood, glue-down flooring, and preparation before new floor installation.",
    commonProblems: [
      "Old carpet removal",
      "Tile demolition",
      "Glue-down flooring removal",
      "Vinyl floor removal",
      "Hardwood floor tear-out",
      "Floor prep before installation",
    ],
    priceMin: 250,
    priceMax: 6000,
    priceUnit: "sqft",
    relatedSlugs: [
      "flooring-installation",
      "lvp-flooring-installation",
      "tile-flooring-installation",
      "subfloor-repair",
    ],
    formFields: [
      "flooring_type",
      "area_sqft",
      "rooms",
      "disposal_needed",
      "adhesive_removal",
      "description",
      "photos",
    ],
  },

  "subfloor-repair": {
    slug: "subfloor-repair",
    title: "Subfloor Repair",
    shortTitle: "Subfloor Repair",
    parentSlug: "flooring",
    description:
      "Subfloor repair for soft spots, squeaks, water damage, uneven areas, damaged plywood, floor leveling needs, and installation preparation.",
    commonProblems: [
      "Soft floor spot",
      "Squeaky floor",
      "Water-damaged subfloor",
      "Uneven floor",
      "Rotten plywood",
      "Floor leveling before installation",
    ],
    priceMin: 300,
    priceMax: 7000,
    priceUnit: "flat",
    relatedSlugs: [
      "flooring-repair",
      "flooring-installation",
      "lvp-flooring-installation",
      "tile-flooring-installation",
    ],
    formFields: [
      "damage_type",
      "area_size",
      "flooring_removed",
      "water_damage",
      "description",
      "photos",
    ],
  },

  "baseboard-trim-installation": {
    slug: "baseboard-trim-installation",
    title: "Baseboard & Trim Installation",
    shortTitle: "Baseboards",
    parentSlug: "flooring",
    description:
      "Baseboard, shoe molding, quarter round, transition strip, and trim installation after flooring projects or room updates.",
    commonProblems: [
      "Missing baseboards",
      "Quarter round installation",
      "Transition strip installation",
      "Damaged trim after flooring",
      "Room trim replacement",
      "Floor gap coverage",
    ],
    priceMin: 150,
    priceMax: 2500,
    priceUnit: "flat",
    relatedSlugs: [
      "flooring-installation",
      "lvp-flooring-installation",
      "laminate-flooring-installation",
      "hardwood-flooring-installation",
    ],
    formFields: [
      "trim_type",
      "linear_feet",
      "rooms",
      "material_provided",
      "painting_needed",
      "description",
      "photos",
    ],
  },

  "flooring-inspection": {
    slug: "flooring-inspection",
    title: "Flooring Inspection",
    shortTitle: "Floor Inspection",
    parentSlug: "flooring",
    description:
      "Flooring inspection for uneven floors, moisture concerns, installation problems, damaged flooring, subfloor concerns, and repair planning.",
    commonProblems: [
      "Uneven floor concern",
      "Moisture issue",
      "Installation defect",
      "Floor movement",
      "Cracks or gaps",
      "Repair estimate needed",
    ],
    priceMin: 100,
    priceMax: 750,
    priceUnit: "flat",
    relatedSlugs: [
      "flooring-repair",
      "subfloor-repair",
      "hardwood-floor-repair",
      "tile-flooring-repair",
    ],
    formFields: [
      "flooring_type",
      "concern_type",
      "property_type",
      "photos",
      "description",
    ],
  },
};