import type { SubcategoryMap } from "../types";

export const garageSubcategories: SubcategoryMap = {
  "garage-door-repair": {
    slug: "garage-door-repair",
    title: "Garage Door Repair",
    shortTitle: "Garage Door Repair",
    parentSlug: "garage",
    description:
      "Garage door repair for noisy doors, stuck doors, broken parts, alignment issues, and doors that will not open or close properly.",
    commonProblems: [
      "Garage door stuck open or closed",
      "Door is noisy or shaking",
      "Door comes off track",
      "Broken rollers, hinges, or cables",
      "Door closes unevenly",
      "Garage door opener works but door does not move",
    ],
    priceMin: 125,
    priceMax: 750,
    priceUnit: "flat",
    relatedSlugs: [
      "garage-door-opener-repair",
      "garage-door-spring-replacement",
      "garage-door-track-roller-repair",
    ],
    formFields: [
      "Door issue",
      "Door size",
      "Door material",
      "Opener brand if known",
      "Is the door stuck open or closed?",
      "Urgency",
    ],
  },

  "garage-door-installation": {
    slug: "garage-door-installation",
    title: "Garage Door Installation",
    shortTitle: "Garage Door Installation",
    parentSlug: "garage",
    description:
      "Garage door installation and replacement for single-car, double-car, insulated, steel, wood-look, carriage-style, and custom garage doors.",
    commonProblems: [
      "Old garage door needs replacement",
      "Damaged door panels",
      "Poor insulation",
      "Outdated exterior appearance",
      "Door is too heavy for the opener",
      "New construction garage door needed",
    ],
    priceMin: 900,
    priceMax: 4500,
    priceUnit: "flat",
    relatedSlugs: [
      "garage-door-replacement",
      "garage-door-panel-replacement",
      "garage-door-opener-installation",
    ],
    formFields: [
      "Door size",
      "Door style",
      "Insulated or non-insulated",
      "Existing door removal needed",
      "Opener needed",
      "Preferred timeline",
    ],
  },

  "garage-door-replacement": {
    slug: "garage-door-replacement",
    title: "Garage Door Replacement",
    shortTitle: "Garage Door Replacement",
    parentSlug: "garage",
    description:
      "Garage door replacement for damaged, outdated, unsafe, poorly insulated, or unreliable garage doors.",
    commonProblems: [
      "Door panels are badly damaged",
      "Door is rusted or warped",
      "Door is unsafe to operate",
      "Repeated repair issues",
      "Poor curb appeal",
      "Garage gets too hot or cold",
    ],
    priceMin: 950,
    priceMax: 5000,
    priceUnit: "flat",
    relatedSlugs: [
      "garage-door-installation",
      "garage-door-panel-replacement",
      "garage-door-opener-installation",
    ],
    formFields: [
      "Current door condition",
      "Door size",
      "Preferred replacement type",
      "Insulation preference",
      "Remove old door",
      "Timeline",
    ],
  },

  "garage-door-opener-repair": {
    slug: "garage-door-opener-repair",
    title: "Garage Door Opener Repair",
    shortTitle: "Opener Repair",
    parentSlug: "garage",
    description:
      "Garage door opener repair for motors, remotes, wall buttons, sensors, keypads, chains, belts, and opener troubleshooting.",
    commonProblems: [
      "Opener motor runs but door does not move",
      "Remote stopped working",
      "Wall button does not respond",
      "Door reverses before closing",
      "Safety sensors are blinking",
      "Opener makes grinding noise",
    ],
    priceMin: 95,
    priceMax: 550,
    priceUnit: "flat",
    relatedSlugs: [
      "garage-door-opener-installation",
      "garage-door-sensor-alignment",
      "garage-door-repair",
    ],
    formFields: [
      "Opener brand",
      "Remote or wall button issue",
      "Sensor light status",
      "Door movement",
      "Noise description",
      "Urgency",
    ],
  },

  "garage-door-opener-installation": {
    slug: "garage-door-opener-installation",
    title: "Garage Door Opener Installation",
    shortTitle: "Opener Installation",
    parentSlug: "garage",
    description:
      "Garage door opener installation and replacement for chain drive, belt drive, wall-mount, smart, and battery-backup garage door openers.",
    commonProblems: [
      "No opener installed",
      "Old opener is unreliable",
      "Need quieter opener",
      "Need smart garage access",
      "Need battery backup",
      "Existing opener is not strong enough",
    ],
    priceMin: 250,
    priceMax: 900,
    priceUnit: "flat",
    relatedSlugs: [
      "garage-door-opener-repair",
      "garage-door-sensor-alignment",
      "garage-door-repair",
    ],
    formFields: [
      "Opener type",
      "Door size",
      "Existing opener removal",
      "Smart opener needed",
      "Battery backup needed",
      "Preferred installation time",
    ],
  },

  "garage-door-spring-replacement": {
    slug: "garage-door-spring-replacement",
    title: "Garage Door Spring Replacement",
    shortTitle: "Spring Replacement",
    parentSlug: "garage",
    description:
      "Garage door spring replacement for broken torsion springs, extension springs, heavy doors, and doors that will not lift safely.",
    commonProblems: [
      "Broken spring",
      "Loud snap from garage",
      "Door is too heavy to lift",
      "Door opens a few inches then stops",
      "Crooked or uneven door movement",
      "Spring gap visible above the door",
    ],
    priceMin: 180,
    priceMax: 650,
    priceUnit: "flat",
    relatedSlugs: [
      "garage-door-repair",
      "garage-door-cable-replacement",
      "garage-door-track-roller-repair",
    ],
    formFields: [
      "Spring type if known",
      "Door size",
      "Door stuck open or closed",
      "Number of springs",
      "Any visible cable damage",
      "Urgency",
    ],
  },

  "garage-door-cable-replacement": {
    slug: "garage-door-cable-replacement",
    title: "Garage Door Cable Replacement",
    shortTitle: "Cable Replacement",
    parentSlug: "garage",
    description:
      "Garage door cable replacement and repair for frayed cables, snapped cables, uneven doors, and unsafe garage door movement.",
    commonProblems: [
      "Cable snapped",
      "Cable is frayed",
      "Door hangs crooked",
      "Door jammed on one side",
      "Door will not close evenly",
      "Cable came off drum",
    ],
    priceMin: 150,
    priceMax: 550,
    priceUnit: "flat",
    relatedSlugs: [
      "garage-door-spring-replacement",
      "garage-door-track-roller-repair",
      "garage-door-repair",
    ],
    formFields: [
      "Cable condition",
      "Door position",
      "Door size",
      "Spring condition",
      "Photos available",
      "Urgency",
    ],
  },

  "garage-door-track-roller-repair": {
    slug: "garage-door-track-roller-repair",
    title: "Garage Door Track & Roller Repair",
    shortTitle: "Track & Roller Repair",
    parentSlug: "garage",
    description:
      "Garage door track and roller repair for doors that are noisy, misaligned, off track, dragging, shaking, or not moving smoothly.",
    commonProblems: [
      "Door came off track",
      "Bent garage door track",
      "Broken rollers",
      "Loud scraping noise",
      "Door shakes while moving",
      "Door gets stuck halfway",
    ],
    priceMin: 125,
    priceMax: 650,
    priceUnit: "flat",
    relatedSlugs: [
      "garage-door-repair",
      "garage-door-cable-replacement",
      "garage-door-spring-replacement",
    ],
    formFields: [
      "Track condition",
      "Roller condition",
      "Door position",
      "Noise description",
      "Visible damage",
      "Urgency",
    ],
  },

  "garage-door-panel-replacement": {
    slug: "garage-door-panel-replacement",
    title: "Garage Door Panel Replacement",
    shortTitle: "Panel Replacement",
    parentSlug: "garage",
    description:
      "Garage door panel replacement for dented, cracked, rusted, damaged, or mismatched garage door sections.",
    commonProblems: [
      "Dented panel",
      "Cracked garage door section",
      "Vehicle impact damage",
      "Rusted lower panel",
      "Panel does not match",
      "Door still works but looks damaged",
    ],
    priceMin: 250,
    priceMax: 1200,
    priceUnit: "flat",
    relatedSlugs: [
      "garage-door-replacement",
      "garage-door-repair",
      "garage-door-installation",
    ],
    formFields: [
      "Panel damage",
      "Door brand if known",
      "Door size",
      "Number of damaged panels",
      "Photos available",
      "Color/style match needed",
    ],
  },

  "garage-door-sensor-alignment": {
    slug: "garage-door-sensor-alignment",
    title: "Garage Door Sensor Alignment",
    shortTitle: "Sensor Alignment",
    parentSlug: "garage",
    description:
      "Garage door sensor alignment, safety sensor troubleshooting, wiring checks, and opener safety reversal issue repair.",
    commonProblems: [
      "Garage door will not close",
      "Door reverses immediately",
      "Sensor lights blinking",
      "Sensor knocked out of alignment",
      "Wiring issue near sensor",
      "Opener clicks but door does not close",
    ],
    priceMin: 85,
    priceMax: 300,
    priceUnit: "flat",
    relatedSlugs: [
      "garage-door-opener-repair",
      "garage-door-opener-installation",
      "garage-door-repair",
    ],
    formFields: [
      "Sensor light color",
      "Door behavior",
      "Opener brand",
      "Any recent impact",
      "Wiring visible",
      "Urgency",
    ],
  },

  "garage-storage-installation": {
    slug: "garage-storage-installation",
    title: "Garage Storage Installation",
    shortTitle: "Garage Storage",
    parentSlug: "garage",
    description:
      "Garage storage installation for shelves, cabinets, overhead racks, wall systems, hooks, and storage organization upgrades.",
    commonProblems: [
      "Garage clutter",
      "Need overhead storage",
      "Need wall-mounted shelves",
      "Heavy items need safe storage",
      "No tool organization",
      "Need cabinets installed",
    ],
    priceMin: 150,
    priceMax: 2500,
    priceUnit: "flat",
    relatedSlugs: [
      "garage-shelving-installation",
      "garage-cabinet-installation",
      "overhead-garage-storage-installation",
    ],
    formFields: [
      "Storage type",
      "Garage size",
      "Wall or ceiling mounting",
      "Materials already purchased",
      "Weight requirements",
      "Preferred timeline",
    ],
  },

  "garage-shelving-installation": {
    slug: "garage-shelving-installation",
    title: "Garage Shelving Installation",
    shortTitle: "Garage Shelving",
    parentSlug: "garage",
    description:
      "Garage shelving installation for wall-mounted shelves, freestanding systems, heavy-duty storage shelves, and utility organization.",
    commonProblems: [
      "Need shelves mounted",
      "Need heavy-duty garage storage",
      "Shelves pulling from wall",
      "Poor garage organization",
      "Need tool and tote storage",
      "Need safe wall anchoring",
    ],
    priceMin: 120,
    priceMax: 1200,
    priceUnit: "flat",
    relatedSlugs: [
      "garage-storage-installation",
      "garage-cabinet-installation",
      "overhead-garage-storage-installation",
    ],
    formFields: [
      "Shelving type",
      "Wall type",
      "Number of shelves",
      "Materials purchased",
      "Expected load",
      "Garage access",
    ],
  },

  "garage-cabinet-installation": {
    slug: "garage-cabinet-installation",
    title: "Garage Cabinet Installation",
    shortTitle: "Garage Cabinets",
    parentSlug: "garage",
    description:
      "Garage cabinet installation for storage cabinets, wall-mounted cabinets, workbench cabinets, and garage organization systems.",
    commonProblems: [
      "Cabinets need assembly",
      "Cabinets need wall mounting",
      "Need more enclosed storage",
      "Garage tools need organization",
      "Existing cabinets are damaged",
      "Need workbench storage",
    ],
    priceMin: 250,
    priceMax: 3000,
    priceUnit: "flat",
    relatedSlugs: [
      "garage-storage-installation",
      "garage-shelving-installation",
      "overhead-garage-storage-installation",
    ],
    formFields: [
      "Cabinet type",
      "Number of cabinets",
      "Wall mounting needed",
      "Assembly needed",
      "Workbench included",
      "Materials purchased",
    ],
  },

  "overhead-garage-storage-installation": {
    slug: "overhead-garage-storage-installation",
    title: "Overhead Garage Storage Installation",
    shortTitle: "Overhead Storage",
    parentSlug: "garage",
    description:
      "Overhead garage storage rack installation for ceiling-mounted storage, seasonal items, totes, bikes, and bulky garage organization.",
    commonProblems: [
      "Need ceiling storage",
      "Floor space is limited",
      "Need storage for totes",
      "Need safe ceiling anchoring",
      "Rack installation seems unsafe",
      "Need seasonal storage",
    ],
    priceMin: 180,
    priceMax: 900,
    priceUnit: "flat",
    relatedSlugs: [
      "garage-storage-installation",
      "garage-shelving-installation",
      "garage-cabinet-installation",
    ],
    formFields: [
      "Rack size",
      "Ceiling height",
      "Ceiling type",
      "Number of racks",
      "Weight requirements",
      "Materials purchased",
    ],
  },
};