import type { SubcategoryMap } from "../types";

export const handymanSubcategories: SubcategoryMap = {
  "furniture-assembly": {
    slug: "furniture-assembly",
    title: "Furniture Assembly",
    shortTitle: "Furniture Assembly",
    parentSlug: "handyman",
    description:
      "Assembly help for flat-pack furniture, beds, desks, shelves, cabinets, patio furniture, and home office setups.",
    commonProblems: [
      "Flat-pack furniture assembly",
      "Bed frame assembly",
      "Desk and office furniture setup",
      "Bookshelf and cabinet assembly",
      "Patio furniture assembly",
      "Missing or confusing hardware",
    ],
    priceMin: 75,
    priceMax: 300,
    priceUnit: "flat",
    relatedSlugs: [
      "shelving-wall-mounting",
      "picture-mirror-hanging",
      "general-home-repairs",
    ],
    formFields: ["item_count", "brand", "room", "description", "photos"],
  },

  "tv-mounting": {
    slug: "tv-mounting",
    title: "TV Mounting",
    shortTitle: "TV Mounting",
    parentSlug: "handyman",
    description:
      "Wall mounting for TVs, soundbars, basic wire management, brackets, and room setup.",
    commonProblems: [
      "TV mounted on drywall",
      "TV mounted on brick or concrete",
      "Soundbar mounting",
      "Basic wire hiding",
      "Mount height planning",
      "Existing mount removal",
    ],
    priceMin: 90,
    priceMax: 300,
    priceUnit: "flat",
    relatedSlugs: [
      "shelving-wall-mounting",
      "picture-mirror-hanging",
      "fixture-hardware-installation",
    ],
    formFields: ["tv_size", "wall_type", "mount_available", "description", "photos"],
  },

  "drywall-repair-patching": {
    slug: "drywall-repair-patching",
    title: "Drywall Repair & Patching",
    shortTitle: "Drywall Repair",
    parentSlug: "handyman",
    description:
      "Small drywall repair, wall patching, nail pops, dents, holes, texture touch-ups, and paint-ready prep.",
    commonProblems: [
      "Small holes in drywall",
      "Door knob wall damage",
      "Nail pops",
      "Wall dents and cracks",
      "Drywall patch after leak repair",
      "Texture matching",
    ],
    priceMin: 125,
    priceMax: 650,
    priceUnit: "flat",
    relatedSlugs: [
      "interior-paint-touch-ups",
      "general-home-repairs",
      "caulking-sealing",
    ],
    formFields: ["damage_size", "wall_texture", "paint_needed", "description", "photos"],
  },

  "door-repair-installation": {
    slug: "door-repair-installation",
    title: "Door Repair & Installation",
    shortTitle: "Door Repair",
    parentSlug: "handyman",
    description:
      "Interior door repair, hardware replacement, sticking doors, hinge fixes, knobs, locks, and simple door installation.",
    commonProblems: [
      "Door will not close properly",
      "Loose hinges",
      "Sticking interior doors",
      "Door knob replacement",
      "Latch alignment",
      "Interior door installation",
    ],
    priceMin: 95,
    priceMax: 500,
    priceUnit: "flat",
    relatedSlugs: [
      "fixture-hardware-installation",
      "weatherstripping-installation",
      "general-home-repairs",
    ],
    formFields: ["door_type", "hardware_needed", "problem", "description", "photos"],
  },

  "window-repair": {
    slug: "window-repair",
    title: "Window Repair",
    shortTitle: "Window Repair",
    parentSlug: "handyman",
    description:
      "Minor window repairs, stuck windows, latches, screens, trim, sealing, and simple hardware fixes.",
    commonProblems: [
      "Window will not open",
      "Window latch repair",
      "Loose window trim",
      "Drafty window",
      "Screen repair",
      "Minor frame repairs",
    ],
    priceMin: 95,
    priceMax: 450,
    priceUnit: "flat",
    relatedSlugs: [
      "caulking-sealing",
      "weatherstripping-installation",
      "general-home-repairs",
    ],
    formFields: ["window_type", "problem", "count", "description", "photos"],
  },

  "shelving-wall-mounting": {
    slug: "shelving-wall-mounting",
    title: "Shelving & Wall Mounting",
    shortTitle: "Shelving",
    parentSlug: "handyman",
    description:
      "Installation of shelves, floating shelves, wall organizers, hooks, rails, and light storage systems.",
    commonProblems: [
      "Floating shelf installation",
      "Closet shelf mounting",
      "Garage wall storage",
      "Wall hooks and rails",
      "Heavy item mounting",
      "Finding studs safely",
    ],
    priceMin: 80,
    priceMax: 350,
    priceUnit: "flat",
    relatedSlugs: [
      "picture-mirror-hanging",
      "tv-mounting",
      "closet-system-installation",
    ],
    formFields: ["item_count", "wall_type", "weight", "description", "photos"],
  },

  "caulking-sealing": {
    slug: "caulking-sealing",
    title: "Caulking & Sealing",
    shortTitle: "Caulking",
    parentSlug: "handyman",
    description:
      "Caulking and sealing around tubs, showers, sinks, windows, doors, trim, gaps, and small exterior openings.",
    commonProblems: [
      "Old caulk removal",
      "Bathroom caulking",
      "Kitchen sink sealing",
      "Window gap sealing",
      "Trim gaps",
      "Draft reduction",
    ],
    priceMin: 90,
    priceMax: 450,
    priceUnit: "flat",
    relatedSlugs: [
      "weatherstripping-installation",
      "window-repair",
      "general-home-repairs",
    ],
    formFields: ["area", "linear_feet", "old_caulk_removal", "description", "photos"],
  },

  "fixture-hardware-installation": {
    slug: "fixture-hardware-installation",
    title: "Fixture & Hardware Installation",
    shortTitle: "Fixtures",
    parentSlug: "handyman",
    description:
      "Installation of towel bars, hooks, cabinet pulls, knobs, handles, house numbers, accessories, and small fixtures.",
    commonProblems: [
      "Bathroom accessory installation",
      "Cabinet handle installation",
      "Loose towel bars",
      "House number installation",
      "Wall hooks",
      "Hardware replacement",
    ],
    priceMin: 75,
    priceMax: 350,
    priceUnit: "flat",
    relatedSlugs: [
      "grab-bar-installation",
      "picture-mirror-hanging",
      "general-home-repairs",
    ],
    formFields: ["item_count", "wall_or_surface_type", "hardware_available", "description", "photos"],
  },

  "curtain-blinds-installation": {
    slug: "curtain-blinds-installation",
    title: "Curtain & Blinds Installation",
    shortTitle: "Curtains & Blinds",
    parentSlug: "handyman",
    description:
      "Curtain rods, blinds, shades, drapery hardware, brackets, and window treatment installation.",
    commonProblems: [
      "Curtain rod installation",
      "Blind installation",
      "Shade mounting",
      "Bracket alignment",
      "Multiple window setup",
      "Replacing old hardware",
    ],
    priceMin: 85,
    priceMax: 400,
    priceUnit: "flat",
    relatedSlugs: [
      "window-repair",
      "shelving-wall-mounting",
      "fixture-hardware-installation",
    ],
    formFields: ["window_count", "product_type", "mount_type", "description", "photos"],
  },

  "picture-mirror-hanging": {
    slug: "picture-mirror-hanging",
    title: "Picture & Mirror Hanging",
    shortTitle: "Picture Hanging",
    parentSlug: "handyman",
    description:
      "Hanging mirrors, framed art, gallery walls, clocks, decor, and wall-mounted accessories.",
    commonProblems: [
      "Heavy mirror hanging",
      "Gallery wall layout",
      "Picture frame hanging",
      "Clock mounting",
      "Wall decor installation",
      "Anchor selection",
    ],
    priceMin: 75,
    priceMax: 300,
    priceUnit: "flat",
    relatedSlugs: [
      "shelving-wall-mounting",
      "tv-mounting",
      "fixture-hardware-installation",
    ],
    formFields: ["item_count", "item_weight", "wall_type", "description", "photos"],
  },

  "small-carpentry-repairs": {
    slug: "small-carpentry-repairs",
    title: "Small Carpentry Repairs",
    shortTitle: "Carpentry Repairs",
    parentSlug: "handyman",
    description:
      "Minor carpentry repairs for trim, molding, baseboards, loose boards, small wood repairs, and finish details.",
    commonProblems: [
      "Loose trim",
      "Baseboard repair",
      "Small wood damage",
      "Molding installation",
      "Cabinet trim repair",
      "Minor finish carpentry",
    ],
    priceMin: 125,
    priceMax: 750,
    priceUnit: "flat",
    relatedSlugs: [
      "door-repair-installation",
      "deck-patio-minor-repairs",
      "general-home-repairs",
    ],
    formFields: ["repair_type", "material", "area_size", "description", "photos"],
  },

  "general-home-repairs": {
    slug: "general-home-repairs",
    title: "General Home Repairs",
    shortTitle: "Home Repairs",
    parentSlug: "handyman",
    description:
      "General handyman help for small repairs, punch lists, maintenance tasks, installations, and home upkeep.",
    commonProblems: [
      "Multiple small repairs",
      "Move-in punch list",
      "Rental turnover fixes",
      "Loose fixtures",
      "Minor wall or trim damage",
      "Home maintenance tasks",
    ],
    priceMin: 85,
    priceMax: 650,
    priceUnit: "hourly",
    relatedSlugs: [
      "drywall-repair-patching",
      "door-repair-installation",
      "fixture-hardware-installation",
    ],
    formFields: ["task_list", "priority", "timeline", "description", "photos"],
  },

  "closet-system-installation": {
    slug: "closet-system-installation",
    title: "Closet System Installation",
    shortTitle: "Closet Systems",
    parentSlug: "handyman",
    description:
      "Installation of closet shelves, rods, organizers, modular closet systems, and storage upgrades.",
    commonProblems: [
      "Closet shelf installation",
      "Closet rod mounting",
      "Modular closet setup",
      "Loose closet hardware",
      "Pantry shelving",
      "Storage upgrade",
    ],
    priceMin: 125,
    priceMax: 700,
    priceUnit: "flat",
    relatedSlugs: [
      "shelving-wall-mounting",
      "small-carpentry-repairs",
      "furniture-assembly",
    ],
    formFields: ["closet_size", "system_brand", "wall_type", "description", "photos"],
  },

  "grab-bar-installation": {
    slug: "grab-bar-installation",
    title: "Grab Bar Installation",
    shortTitle: "Grab Bars",
    parentSlug: "handyman",
    description:
      "Bathroom grab bar installation for showers, tubs, toilets, accessibility upgrades, and safer daily use.",
    commonProblems: [
      "Shower grab bar installation",
      "Toilet grab bar installation",
      "Tub safety support",
      "Senior safety upgrade",
      "Stud location",
      "Tile mounting",
    ],
    priceMin: 95,
    priceMax: 350,
    priceUnit: "flat",
    relatedSlugs: [
      "fixture-hardware-installation",
      "caulking-sealing",
      "general-home-repairs",
    ],
    formFields: ["bar_count", "surface_type", "location", "description", "photos"],
  },

  "weatherstripping-installation": {
    slug: "weatherstripping-installation",
    title: "Weatherstripping Installation",
    shortTitle: "Weatherstripping",
    parentSlug: "handyman",
    description:
      "Weatherstripping, door sweeps, draft reduction, small sealing work, and comfort-focused home fixes.",
    commonProblems: [
      "Drafty exterior door",
      "Door sweep replacement",
      "Air gaps",
      "Window draft reduction",
      "Loose weatherstripping",
      "Energy loss around openings",
    ],
    priceMin: 90,
    priceMax: 400,
    priceUnit: "flat",
    relatedSlugs: [
      "door-repair-installation",
      "window-repair",
      "caulking-sealing",
    ],
    formFields: ["opening_count", "door_or_window", "material_available", "description", "photos"],
  },

  "mailbox-installation": {
    slug: "mailbox-installation",
    title: "Mailbox Installation",
    shortTitle: "Mailbox",
    parentSlug: "handyman",
    description:
      "Mailbox replacement, post-mounted mailbox installation, wall-mounted mailbox setup, and minor mailbox repairs.",
    commonProblems: [
      "Mailbox replacement",
      "Post mailbox installation",
      "Wall-mounted mailbox",
      "Loose mailbox post",
      "Damaged mailbox",
      "Hardware replacement",
    ],
    priceMin: 95,
    priceMax: 450,
    priceUnit: "flat",
    relatedSlugs: [
      "fixture-hardware-installation",
      "small-carpentry-repairs",
      "general-home-repairs",
    ],
    formFields: ["mailbox_type", "post_needed", "old_mailbox_removal", "description", "photos"],
  },

  "gate-fence-hardware-repair": {
    slug: "gate-fence-hardware-repair",
    title: "Gate & Fence Hardware Repair",
    shortTitle: "Gate Hardware",
    parentSlug: "handyman",
    description:
      "Minor gate and fence hardware repairs, hinges, latches, alignment, handles, and simple outdoor fixes.",
    commonProblems: [
      "Gate latch repair",
      "Gate hinge replacement",
      "Fence hardware replacement",
      "Sagging gate",
      "Loose handle",
      "Minor outdoor hardware repair",
    ],
    priceMin: 95,
    priceMax: 500,
    priceUnit: "flat",
    relatedSlugs: [
      "small-carpentry-repairs",
      "deck-patio-minor-repairs",
      "general-home-repairs",
    ],
    formFields: ["gate_type", "hardware_needed", "problem", "description", "photos"],
  },

  "deck-patio-minor-repairs": {
    slug: "deck-patio-minor-repairs",
    title: "Deck & Patio Minor Repairs",
    shortTitle: "Deck Repairs",
    parentSlug: "handyman",
    description:
      "Minor deck, patio, railing, board, step, and outdoor surface repairs for small non-structural issues.",
    commonProblems: [
      "Loose deck board",
      "Minor railing repair",
      "Small step repair",
      "Patio hardware issue",
      "Outdoor trim damage",
      "Minor non-structural repair",
    ],
    priceMin: 150,
    priceMax: 900,
    priceUnit: "flat",
    relatedSlugs: [
      "small-carpentry-repairs",
      "gate-fence-hardware-repair",
      "general-home-repairs",
    ],
    formFields: ["repair_area", "material", "safety_issue", "description", "photos"],
  },

  "baby-proofing-installation": {
    slug: "baby-proofing-installation",
    title: "Baby Proofing Installation",
    shortTitle: "Baby Proofing",
    parentSlug: "handyman",
    description:
      "Installation of safety gates, cabinet locks, furniture anchors, outlet covers, corner guards, and child safety hardware.",
    commonProblems: [
      "Furniture anchoring",
      "Baby gate installation",
      "Cabinet lock installation",
      "Corner guards",
      "Safety hardware setup",
      "Room-by-room childproofing",
    ],
    priceMin: 95,
    priceMax: 500,
    priceUnit: "flat",
    relatedSlugs: [
      "fixture-hardware-installation",
      "furniture-assembly",
      "general-home-repairs",
    ],
    formFields: ["room_count", "items_to_install", "hardware_available", "description", "photos"],
  },
};