import type { SubcategoryMap } from "../types";

export const hvacSubcategories: SubcategoryMap = {
  "hvac-repair": {
    slug: "hvac-repair",
    title: "HVAC Repair",
    shortTitle: "HVAC Repair",
    parentSlug: "hvac",
    description:
      "Heating and cooling repair for homes and small businesses, including systems that do not turn on, blow weak air, make unusual noises, or fail to keep rooms comfortable.",
    commonProblems: [
      "System will not turn on",
      "Weak airflow from vents",
      "Uneven heating or cooling",
      "Strange noises or vibration",
      "Short cycling",
      "Thermostat not controlling the system",
    ],
    priceMin: 125,
    priceMax: 650,
    priceUnit: "flat",
    relatedSlugs: [
      "hvac-inspection-troubleshooting",
      "hvac-maintenance-tune-up",
      "thermostat-installation-repair",
    ],
    formFields: [
      "System type",
      "Problem description",
      "When issue started",
      "Home size",
      "Urgency",
      "Photos or videos",
    ],
  },

  "ac-repair": {
    slug: "ac-repair",
    title: "AC Repair",
    shortTitle: "AC Repair",
    parentSlug: "hvac",
    description:
      "Air conditioning repair for cooling issues, warm air, frozen lines, leaking units, poor airflow, electrical problems, and systems that stop working during hot weather.",
    commonProblems: [
      "AC blowing warm air",
      "AC not turning on",
      "Frozen evaporator coil",
      "Water leaking near indoor unit",
      "Outdoor condenser not running",
      "High indoor humidity",
    ],
    priceMin: 150,
    priceMax: 750,
    priceUnit: "flat",
    relatedSlugs: [
      "hvac-repair",
      "hvac-inspection-troubleshooting",
      "hvac-maintenance-tune-up",
    ],
    formFields: [
      "AC type",
      "Cooling issue",
      "Indoor symptoms",
      "Outdoor unit symptoms",
      "Last maintenance date",
      "Urgency",
    ],
  },

  "ac-installation-replacement": {
    slug: "ac-installation-replacement",
    title: "AC Installation & Replacement",
    shortTitle: "AC Install",
    parentSlug: "hvac",
    description:
      "Central air conditioning installation and replacement for old, undersized, inefficient, or failing cooling systems.",
    commonProblems: [
      "Old AC system needs replacement",
      "System cannot cool the home",
      "Frequent AC repairs",
      "High energy bills",
      "New construction cooling setup",
      "Replacing outdoor condenser or full system",
    ],
    priceMin: 3500,
    priceMax: 12500,
    priceUnit: "flat",
    relatedSlugs: [
      "hvac-inspection-troubleshooting",
      "ductwork-repair-installation",
      "thermostat-installation-repair",
    ],
    formFields: [
      "Home size",
      "Current system age",
      "Existing ductwork",
      "Preferred efficiency level",
      "Replacement or new install",
      "Timeline",
    ],
  },

  "furnace-repair": {
    slug: "furnace-repair",
    title: "Furnace Repair",
    shortTitle: "Furnace Repair",
    parentSlug: "hvac",
    description:
      "Gas and electric furnace repair for heating failures, ignition problems, airflow issues, unusual smells, and systems that cycle incorrectly.",
    commonProblems: [
      "Furnace not heating",
      "Pilot or ignition issue",
      "Burner not staying on",
      "Blower running constantly",
      "Unusual smell or noise",
      "System short cycling",
    ],
    priceMin: 150,
    priceMax: 800,
    priceUnit: "flat",
    relatedSlugs: [
      "hvac-repair",
      "hvac-inspection-troubleshooting",
      "hvac-maintenance-tune-up",
    ],
    formFields: [
      "Furnace type",
      "Heating issue",
      "Fuel type",
      "System age",
      "Error code if visible",
      "Urgency",
    ],
  },

  "furnace-installation-replacement": {
    slug: "furnace-installation-replacement",
    title: "Furnace Installation & Replacement",
    shortTitle: "Furnace Install",
    parentSlug: "hvac",
    description:
      "Furnace replacement and installation for aging, unsafe, inefficient, or unreliable heating systems.",
    commonProblems: [
      "Old furnace needs replacement",
      "Frequent breakdowns",
      "Poor heating performance",
      "High gas or electric bills",
      "Unsafe or outdated system",
      "New heating system needed",
    ],
    priceMin: 3200,
    priceMax: 10500,
    priceUnit: "flat",
    relatedSlugs: [
      "hvac-inspection-troubleshooting",
      "ductwork-repair-installation",
      "thermostat-installation-repair",
    ],
    formFields: [
      "Fuel type",
      "Home size",
      "Current furnace age",
      "Existing ductwork",
      "Efficiency preference",
      "Timeline",
    ],
  },

  "heat-pump-repair-installation": {
    slug: "heat-pump-repair-installation",
    title: "Heat Pump Repair & Installation",
    shortTitle: "Heat Pumps",
    parentSlug: "hvac",
    description:
      "Heat pump repair, replacement, and installation for homes using one system for both heating and cooling.",
    commonProblems: [
      "Heat pump not heating",
      "Heat pump not cooling",
      "Outdoor unit frozen",
      "Aux heat running too often",
      "Weak airflow",
      "System needs replacement",
    ],
    priceMin: 250,
    priceMax: 12000,
    priceUnit: "flat",
    relatedSlugs: [
      "hvac-repair",
      "ac-installation-replacement",
      "hvac-maintenance-tune-up",
    ],
    formFields: [
      "Heat pump issue",
      "Repair or replacement",
      "System age",
      "Home size",
      "Indoor and outdoor symptoms",
      "Urgency",
    ],
  },

  "mini-split-installation": {
    slug: "mini-split-installation",
    title: "Mini Split Installation",
    shortTitle: "Mini Splits",
    parentSlug: "hvac",
    description:
      "Ductless mini split installation and replacement for garages, additions, bedrooms, offices, workshops, and rooms without ductwork.",
    commonProblems: [
      "Room has no ductwork",
      "Garage or addition needs cooling",
      "Single room temperature problem",
      "Old window unit replacement",
      "Multi-zone ductless system needed",
      "Mini split replacement",
    ],
    priceMin: 2200,
    priceMax: 9500,
    priceUnit: "flat",
    relatedSlugs: [
      "heat-pump-repair-installation",
      "ac-installation-replacement",
      "electrical-panel-upgrade",
    ],
    formFields: [
      "Room type",
      "Number of zones",
      "Wall location",
      "Electrical access",
      "Cooling and heating needs",
      "Timeline",
    ],
  },

  "ductwork-repair-installation": {
    slug: "ductwork-repair-installation",
    title: "Ductwork Repair & Installation",
    shortTitle: "Ductwork",
    parentSlug: "hvac",
    description:
      "Duct repair, replacement, sealing, and new duct installation for airflow problems, energy loss, noisy ducts, and room comfort issues.",
    commonProblems: [
      "Weak airflow",
      "Leaky ducts",
      "Hot or cold rooms",
      "Damaged flexible duct",
      "Noisy ductwork",
      "New duct runs needed",
    ],
    priceMin: 350,
    priceMax: 6500,
    priceUnit: "flat",
    relatedSlugs: [
      "hvac-inspection-troubleshooting",
      "ac-installation-replacement",
      "indoor-air-quality",
    ],
    formFields: [
      "Ductwork issue",
      "Home size",
      "Access location",
      "Rooms affected",
      "Existing duct type",
      "Photos",
    ],
  },

  "thermostat-installation-repair": {
    slug: "thermostat-installation-repair",
    title: "Thermostat Installation & Repair",
    shortTitle: "Thermostats",
    parentSlug: "hvac",
    description:
      "Thermostat installation, replacement, smart thermostat setup, wiring checks, and troubleshooting for heating and cooling control problems.",
    commonProblems: [
      "Thermostat not working",
      "Smart thermostat installation",
      "System not responding",
      "Incorrect temperature reading",
      "Wiring compatibility issue",
      "Thermostat replacement",
    ],
    priceMin: 125,
    priceMax: 450,
    priceUnit: "flat",
    relatedSlugs: [
      "hvac-repair",
      "hvac-inspection-troubleshooting",
      "electrical-troubleshooting-repair",
    ],
    formFields: [
      "Thermostat model",
      "Current system type",
      "Wiring photos",
      "Issue description",
      "Smart thermostat brand",
      "Urgency",
    ],
  },

  "hvac-maintenance-tune-up": {
    slug: "hvac-maintenance-tune-up",
    title: "HVAC Maintenance & Tune-Up",
    shortTitle: "HVAC Tune-Up",
    parentSlug: "hvac",
    description:
      "Seasonal HVAC maintenance, tune-ups, cleaning, filter checks, performance checks, and preventive service for heating and cooling systems.",
    commonProblems: [
      "Seasonal maintenance needed",
      "System has not been serviced",
      "Reduced efficiency",
      "Dirty filters or coils",
      "Preparing for summer or winter",
      "Preventing breakdowns",
    ],
    priceMin: 90,
    priceMax: 350,
    priceUnit: "flat",
    relatedSlugs: [
      "hvac-repair",
      "ac-repair",
      "furnace-repair",
    ],
    formFields: [
      "System type",
      "Last service date",
      "Number of units",
      "Known issues",
      "Preferred date",
      "Maintenance goal",
    ],
  },

  "indoor-air-quality": {
    slug: "indoor-air-quality",
    title: "Indoor Air Quality Services",
    shortTitle: "Air Quality",
    parentSlug: "hvac",
    description:
      "Indoor air quality service for filtration, humidity control, ventilation, air purifiers, UV systems, and comfort-related air issues.",
    commonProblems: [
      "Dusty indoor air",
      "Humidity problems",
      "Allergy concerns",
      "Poor ventilation",
      "Odors from HVAC system",
      "Air purification needed",
    ],
    priceMin: 250,
    priceMax: 3500,
    priceUnit: "flat",
    relatedSlugs: [
      "ductwork-repair-installation",
      "hvac-maintenance-tune-up",
      "hvac-inspection-troubleshooting",
    ],
    formFields: [
      "Air quality concern",
      "Home size",
      "Current HVAC system",
      "Humidity issue",
      "Filter type",
      "Desired solution",
    ],
  },

  "hvac-inspection-troubleshooting": {
    slug: "hvac-inspection-troubleshooting",
    title: "HVAC Inspection & Troubleshooting",
    shortTitle: "HVAC Inspection",
    parentSlug: "hvac",
    description:
      "HVAC diagnostic inspections for heating, cooling, airflow, thermostat, ductwork, noise, efficiency, and system performance issues.",
    commonProblems: [
      "Unknown HVAC issue",
      "System performance problem",
      "Pre-purchase HVAC inspection",
      "High utility bills",
      "Recurring breakdowns",
      "Need second opinion",
    ],
    priceMin: 100,
    priceMax: 450,
    priceUnit: "flat",
    relatedSlugs: [
      "hvac-repair",
      "ac-repair",
      "furnace-repair",
    ],
    formFields: [
      "Main concern",
      "System type",
      "System age",
      "Symptoms",
      "Inspection purpose",
      "Photos or error codes",
    ],
  },

  "emergency-hvac-repair": {
    slug: "emergency-hvac-repair",
    title: "Emergency HVAC Repair",
    shortTitle: "Emergency HVAC",
    parentSlug: "hvac",
    description:
      "Urgent HVAC repair for no heat, no cooling, unsafe smells, electrical concerns, water leaks, and system failures that need fast attention.",
    commonProblems: [
      "No heat",
      "No AC",
      "Burning smell",
      "Water leaking from HVAC equipment",
      "System failure during extreme weather",
      "Breaker tripping repeatedly",
    ],
    priceMin: 200,
    priceMax: 1200,
    priceUnit: "flat",
    relatedSlugs: [
      "hvac-repair",
      "ac-repair",
      "furnace-repair",
    ],
    formFields: [
      "Emergency issue",
      "System type",
      "People affected",
      "Safety concerns",
      "When issue started",
      "Best contact method",
    ],
  },

  "commercial-hvac-service": {
    slug: "commercial-hvac-service",
    title: "Commercial HVAC Service",
    shortTitle: "Commercial HVAC",
    parentSlug: "hvac",
    description:
      "Commercial HVAC repair, maintenance, diagnostics, and replacement support for offices, retail spaces, restaurants, warehouses, and small commercial buildings.",
    commonProblems: [
      "Office HVAC not working",
      "Retail space comfort issue",
      "Rooftop unit problem",
      "Commercial maintenance needed",
      "Tenant comfort complaints",
      "Uneven temperatures in business space",
    ],
    priceMin: 250,
    priceMax: 15000,
    priceUnit: "flat",
    relatedSlugs: [
      "hvac-maintenance-tune-up",
      "hvac-inspection-troubleshooting",
      "emergency-hvac-repair",
    ],
    formFields: [
      "Business type",
      "System type",
      "Number of units",
      "Issue description",
      "Access instructions",
      "Urgency",
    ],
  },
};