export type Subcategory = {
  slug: string;
  title: string;
  shortTitle: string;
  parentSlug: string;
  description: string;
  commonProblems: string[];
  priceMin: number;
  priceMax: number;
  priceUnit: "flat" | "hourly" | "sqft";
  relatedSlugs: string[];
  formFields: string[];
};

export const subcategories: Record<string, Subcategory> = {
  // HANDYMAN
  "furniture-assembly": {
    slug: "furniture-assembly",
    title: "Furniture Assembly",
    shortTitle: "Furniture Assembly",
    parentSlug: "handyman",
    description: "Professional assembly of IKEA, Wayfair, and all flat-pack furniture.",
    commonProblems: [
      "IKEA furniture assembly",
      "Wayfair delivery assembly",
      "Office desk setup",
      "Bed frame assembly",
      "Bookshelf and storage units",
    ],
    priceMin: 60,
    priceMax: 250,
    priceUnit: "flat",
    relatedSlugs: ["tv-mounting-shelves", "general-maintenance"],
    formFields: ["brand", "item_count", "description", "photos"],
  },
  "drywall-repair": {
    slug: "drywall-repair",
    title: "Drywall Repair",
    shortTitle: "Drywall Repair",
    parentSlug: "handyman",
    description: "Patch holes, cracks, and water damage in drywall. Smooth finish guaranteed.",
    commonProblems: [
      "Hole in wall",
      "Crack repair",
      "Water damage patch",
      "Nail pops",
      "Corner bead damage",
    ],
    priceMin: 80,
    priceMax: 400,
    priceUnit: "flat",
    relatedSlugs: ["painting-touchups", "drywall-painting-texturing"],
    formFields: ["hole_size", "count", "description", "photos"],
  },
  "door-window-repair": {
    slug: "door-window-repair",
    title: "Door & Window Repair",
    shortTitle: "Door & Window",
    parentSlug: "handyman",
    description: "Fix sticking doors, broken locks, damaged frames, and window issues.",
    commonProblems: [
      "Door won't close",
      "Broken lock",
      "Sticking door",
      "Window won't open",
      "Damaged frame",
    ],
    priceMin: 75,
    priceMax: 300,
    priceUnit: "flat",
    relatedSlugs: ["general-maintenance"],
    formFields: ["door_type", "problem_type", "description", "photos"],
  },
  "painting-touchups": {
    slug: "painting-touchups",
    title: "Painting Touchups",
    shortTitle: "Paint Touchups",
    parentSlug: "handyman",
    description: "Small paint repairs, scuff touch-ups, and wall color matching.",
    commonProblems: [
      "Scuffs and scratches",
      "Nail holes to fill",
      "Color matching",
      "Small area repaint",
    ],
    priceMin: 60,
    priceMax: 200,
    priceUnit: "flat",
    relatedSlugs: ["drywall-repair", "interior-painting"],
    formFields: ["area_sqft", "description", "photos"],
  },
  "tv-mounting-shelves": {
    slug: "tv-mounting-shelves",
    title: "TV Mounting & Shelves",
    shortTitle: "TV Mounting",
    parentSlug: "handyman",
    description: "TV wall mounting, shelf installation, and wire concealment.",
    commonProblems: [
      "TV mount on drywall",
      "TV mount on brick/concrete",
      "Floating shelves",
      "Wire management",
    ],
    priceMin: 80,
    priceMax: 250,
    priceUnit: "flat",
    relatedSlugs: ["furniture-assembly", "general-maintenance"],
    formFields: ["tv_size", "wall_type", "description", "photos"],
  },
  "general-maintenance": {
    slug: "general-maintenance",
    title: "General Maintenance",
    shortTitle: "General Maintenance",
    parentSlug: "handyman",
    description: "Catch-all handyman tasks — minor repairs, installations, and home upkeep.",
    commonProblems: [
      "Miscellaneous repairs",
      "Caulking and sealing",
      "Weatherstripping",
      "Gutter cleaning",
      "Smoke detector install",
    ],
    priceMin: 75,
    priceMax: 350,
    priceUnit: "hourly",
    relatedSlugs: ["furniture-assembly", "door-window-repair"],
    formFields: ["task_list", "description", "photos"],
  },

  // APPLIANCES
  "garbage-disposal": {
    slug: "garbage-disposal",
    title: "Garbage Disposal Repair & Installation",
    shortTitle: "Garbage Disposal",
    parentSlug: "appliance-repair-installation",
    description: "Repair or replace garbage disposals — humming, not spinning, leaking, jammed.",
    commonProblems: [
      "Humming but not spinning",
      "Not turning on",
      "Leaking from bottom",
      "Jammed impeller",
      "Needs full replacement",
    ],
    priceMin: 120,
    priceMax: 380,
    priceUnit: "flat",
    relatedSlugs: ["dishwasher", "plumbing-fixtures", "leak-detection-repair"],
    formFields: ["brand", "model", "symptom", "description", "photos"],
  },
  "washer-dryer": {
    slug: "washer-dryer",
    title: "Washer & Dryer Repair",
    shortTitle: "Washer & Dryer",
    parentSlug: "appliance-repair-installation",
    description: "Diagnose and repair washers and dryers of all major brands.",
    commonProblems: [
      "Not spinning",
      "Won't drain",
      "Loud noise during cycle",
      "Not heating",
      "Door won't lock",
      "Error codes",
    ],
    priceMin: 100,
    priceMax: 350,
    priceUnit: "flat",
    relatedSlugs: ["refrigerator-freezer", "new-hookups"],
    formFields: ["appliance_type", "brand", "model", "symptom", "description", "photos"],
  },
  "refrigerator-freezer": {
    slug: "refrigerator-freezer",
    title: "Refrigerator & Freezer Repair",
    shortTitle: "Refrigerator",
    parentSlug: "appliance-repair-installation",
    description: "Fix refrigerators and freezers that aren't cooling, leaking, or making noise.",
    commonProblems: [
      "Not cooling",
      "Freezer not freezing",
      "Water leaking inside",
      "Ice maker not working",
      "Loud compressor",
    ],
    priceMin: 120,
    priceMax: 400,
    priceUnit: "flat",
    relatedSlugs: ["ice-maker-water-line", "washer-dryer"],
    formFields: ["brand", "model", "symptom", "description", "photos"],
  },
  dishwasher: {
    slug: "dishwasher",
    title: "Dishwasher Repair & Installation",
    shortTitle: "Dishwasher",
    parentSlug: "appliance-repair-installation",
    description: "Repair dishwashers that won't drain, clean, or start. Installation available.",
    commonProblems: [
      "Not draining",
      "Not cleaning dishes",
      "Leaking",
      "Won't start",
      "New installation",
    ],
    priceMin: 100,
    priceMax: 320,
    priceUnit: "flat",
    relatedSlugs: ["garbage-disposal", "plumbing-fixtures"],
    formFields: ["brand", "model", "symptom", "description", "photos"],
  },
  "oven-range-microwave": {
    slug: "oven-range-microwave",
    title: "Oven, Range & Microwave Repair",
    shortTitle: "Oven & Range",
    parentSlug: "appliance-repair-installation",
    description: "Repair ovens, ranges, and microwaves that won't heat, spark, or work properly.",
    commonProblems: [
      "Not heating",
      "Burner not working",
      "Door won't close",
      "Microwave sparking",
      "Error codes",
    ],
    priceMin: 100,
    priceMax: 350,
    priceUnit: "flat",
    relatedSlugs: ["washer-dryer", "new-hookups"],
    formFields: ["appliance_type", "brand", "model", "symptom", "description", "photos"],
  },
  "ice-maker-water-line": {
    slug: "ice-maker-water-line",
    title: "Ice Maker & Water Line",
    shortTitle: "Ice Maker",
    parentSlug: "appliance-repair-installation",
    description: "Ice maker repair and water line installation for refrigerators.",
    commonProblems: [
      "Ice maker not producing ice",
      "Slow ice production",
      "Water line install",
      "Leaking water line",
    ],
    priceMin: 80,
    priceMax: 280,
    priceUnit: "flat",
    relatedSlugs: ["refrigerator-freezer", "leak-detection-repair"],
    formFields: ["brand", "symptom", "description", "photos"],
  },
  "small-appliances": {
    slug: "small-appliances",
    title: "Small Appliance Repair",
    shortTitle: "Small Appliances",
    parentSlug: "appliance-repair-installation",
    description: "Repair of small kitchen and household appliances.",
    commonProblems: [
      "Coffee maker not working",
      "Blender repair",
      "Toaster oven",
      "Vacuum repair",
    ],
    priceMin: 50,
    priceMax: 180,
    priceUnit: "flat",
    relatedSlugs: ["oven-range-microwave"],
    formFields: ["appliance_type", "brand", "symptom", "description", "photos"],
  },
  "new-hookups": {
    slug: "new-hookups",
    title: "New Appliance Hookups",
    shortTitle: "New Hookups",
    parentSlug: "appliance-repair-installation",
    description: "Professional installation and hookup for new appliances.",
    commonProblems: [
      "Washer/dryer hookup",
      "Dishwasher install",
      "Gas range hookup",
      "Refrigerator water line",
    ],
    priceMin: 100,
    priceMax: 400,
    priceUnit: "flat",
    relatedSlugs: ["washer-dryer", "dishwasher", "oven-range-microwave"],
    formFields: ["appliance_type", "fuel_type", "description", "photos"],
  },
  "electric-fireplaces": {
    slug: "electric-fireplaces",
    title: "Electric Fireplace Installation",
    shortTitle: "Electric Fireplace",
    parentSlug: "appliance-repair-installation",
    description: "Install and repair electric fireplaces and fireplace inserts.",
    commonProblems: [
      "New installation",
      "Not heating",
      "Display not working",
      "Insert replacement",
    ],
    priceMin: 120,
    priceMax: 450,
    priceUnit: "flat",
    relatedSlugs: ["new-hookups", "lighting-electrical"],
    formFields: ["fireplace_type", "description", "photos"],
  },

  // PLUMBING
"leak-detection-repair": {
  slug: "leak-detection-repair",
  title: "Leak Detection & Repair",
  shortTitle: "Leak Repair",
  parentSlug: "plumbing",
  description: "Find and fix water leaks — pipes, fixtures, ceilings, walls, and hidden leaks.",
  commonProblems: [
    "Dripping faucet",
    "Pipe leak under sink",
    "Hidden wall leak",
    "Water meter running",
    "Ceiling water stain",
    "Water around toilet or fixtures",
  ],
  priceMin: 100,
  priceMax: 500,
  priceUnit: "flat",
  relatedSlugs: ["pipe-repair", "plumbing-fixtures", "toilet-repair-installation"],
  formFields: ["leak_location", "symptom", "description", "photos"],
},

"plumbing-fixtures": {
  slug: "plumbing-fixtures",
  title: "Plumbing Fixtures",
  shortTitle: "Fixtures",
  parentSlug: "plumbing",
  description: "Install, repair, or replace faucets, toilets, sinks, shower heads, and bathroom or kitchen fixtures.",
  commonProblems: [
    "Faucet replacement",
    "Toilet install",
    "Shower head replacement",
    "Sink install",
    "Running toilet",
    "Loose or leaking fixture",
  ],
  priceMin: 100,
  priceMax: 450,
  priceUnit: "flat",
  relatedSlugs: ["leak-detection-repair", "toilet-repair-installation", "garbage-disposal"],
  formFields: ["fixture_type", "description", "photos"],
},

"drain-cleaning": {
  slug: "drain-cleaning",
  title: "Drain Cleaning",
  shortTitle: "Drain Cleaning",
  parentSlug: "plumbing",
  description: "Clear clogged or slow drains in sinks, tubs, showers, kitchens, bathrooms, and laundry areas.",
  commonProblems: [
    "Slow sink drain",
    "Clogged shower drain",
    "Kitchen sink clog",
    "Standing water",
    "Drain odor",
    "Recurring drain blockage",
  ],
  priceMin: 100,
  priceMax: 350,
  priceUnit: "flat",
  relatedSlugs: ["pipe-repair", "garbage-disposal", "leak-detection-repair"],
  formFields: ["drain_location", "symptom", "description", "photos"],
},

"toilet-repair-installation": {
  slug: "toilet-repair-installation",
  title: "Toilet Repair & Installation",
  shortTitle: "Toilet Repair",
  parentSlug: "plumbing",
  description: "Fix running toilets, leaks, clogs, weak flushing, loose toilets, or install a new toilet.",
  commonProblems: [
    "Running toilet",
    "Toilet leaking at base",
    "Weak flush",
    "Frequent clogging",
    "Loose toilet",
    "New toilet installation",
  ],
  priceMin: 125,
  priceMax: 500,
  priceUnit: "flat",
  relatedSlugs: ["plumbing-fixtures", "leak-detection-repair", "drain-cleaning"],
  formFields: ["toilet_issue", "description", "photos"],
},

"water-heater-repair-installation": {
  slug: "water-heater-repair-installation",
  title: "Water Heater Repair & Installation",
  shortTitle: "Water Heater",
  parentSlug: "plumbing",
  description: "Get help with no hot water, leaking water heaters, tank or tankless units, repairs, and replacements.",
  commonProblems: [
    "No hot water",
    "Water heater leaking",
    "Hot water runs out quickly",
    "Strange noise from unit",
    "Tankless water heater issue",
    "Water heater replacement",
  ],
  priceMin: 150,
  priceMax: 1800,
  priceUnit: "flat",
  relatedSlugs: ["leak-detection-repair", "pipe-repair", "plumbing-fixtures"],
  formFields: ["water_heater_type", "symptom", "description", "photos"],
},

"garbage-disposal-plumbing": {
  slug: "garbage-disposal-plumbing",
  title: "Garbage Disposal Repair & Replacement",
  shortTitle: "Garbage Disposal",
  parentSlug: "plumbing",
  description: "Repair, replace, or troubleshoot garbage disposals that are leaking, jammed, humming, or not working.",
  commonProblems: [
    "Garbage disposal humming",
    "Disposal not turning on",
    "Disposal leaking",
    "Kitchen sink not draining",
    "Bad odor",
    "Garbage disposal replacement",
  ],
  priceMin: 100,
  priceMax: 400,
  priceUnit: "flat",
  relatedSlugs: ["drain-cleaning", "plumbing-fixtures", "leak-detection-repair"],
  formFields: ["disposal_issue", "description", "photos"],
},

"pipe-repair": {
  slug: "pipe-repair",
  title: "Pipe Repair",
  shortTitle: "Pipe Repair",
  parentSlug: "plumbing",
  description: "Repair leaking, damaged, cracked, corroded, or burst pipes under sinks, in walls, ceilings, basements, and utility areas.",
  commonProblems: [
    "Pipe leak",
    "Burst pipe",
    "Corroded pipe",
    "Under-sink pipe issue",
    "Water damage near pipe",
    "Low water pressure",
  ],
  priceMin: 150,
  priceMax: 900,
  priceUnit: "flat",
  relatedSlugs: ["leak-detection-repair", "drain-cleaning", "water-heater-repair-installation"],
  formFields: ["pipe_location", "symptom", "description", "photos"],
},

"sump-pump-repair": {
  slug: "sump-pump-repair",
  title: "Sump Pump Repair & Replacement",
  shortTitle: "Sump Pump",
  parentSlug: "plumbing",
  description: "Repair, replace, or troubleshoot sump pumps, backup pumps, float switches, and basement drainage issues.",
  commonProblems: [
    "Sump pump not working",
    "Pump running constantly",
    "Water in basement",
    "Float switch issue",
    "Backup pump needed",
    "Discharge line problem",
  ],
  priceMin: 150,
  priceMax: 900,
  priceUnit: "flat",
  relatedSlugs: ["pipe-repair", "leak-detection-repair", "drain-cleaning"],
  formFields: ["sump_pump_issue", "description", "photos"],
},

  // CLEANING
  "residential-cleaning": {
    slug: "residential-cleaning",
    title: "Residential Cleaning",
    shortTitle: "House Cleaning",
    parentSlug: "cleaning",
    description: "Regular home cleaning — weekly, bi-weekly, or one-time.",
    commonProblems: [
      "Weekly cleaning",
      "Bi-weekly service",
      "One-time clean",
      "Post-party cleanup",
    ],
    priceMin: 100,
    priceMax: 350,
    priceUnit: "flat",
    relatedSlugs: ["deep-cleaning", "move-out-cleaning"],
    formFields: ["home_size", "bedrooms", "bathrooms", "frequency", "description"],
  },
  "deep-cleaning": {
    slug: "deep-cleaning",
    title: "Deep Cleaning",
    shortTitle: "Deep Clean",
    parentSlug: "cleaning",
    description: "Thorough deep cleaning — inside appliances, baseboards, windows, and more.",
    commonProblems: [
      "First-time deep clean",
      "Spring cleaning",
      "Post-renovation cleanup",
      "Before guests arrive",
    ],
    priceMin: 180,
    priceMax: 500,
    priceUnit: "flat",
    relatedSlugs: ["residential-cleaning", "move-out-cleaning"],
    formFields: ["home_size", "bedrooms", "bathrooms", "extras", "description"],
  },
  "move-out-cleaning": {
    slug: "move-out-cleaning",
    title: "Move-Out Cleaning",
    shortTitle: "Move-Out Clean",
    parentSlug: "cleaning",
    description: "Get your full security deposit back with professional move-out cleaning.",
    commonProblems: [
      "End of lease clean",
      "Moving out of apartment",
      "Selling the house",
      "Tenant turnover",
    ],
    priceMin: 200,
    priceMax: 600,
    priceUnit: "flat",
    relatedSlugs: ["deep-cleaning", "residential-cleaning"],
    formFields: ["home_size", "bedrooms", "bathrooms", "move_date", "description"],
  },

  // PAINTING
  "interior-painting": {
    slug: "interior-painting",
    title: "Interior Painting",
    shortTitle: "Interior Paint",
    parentSlug: "painting",
    description: "Professional interior painting for rooms, ceilings, and trim.",
    commonProblems: [
      "Full room repaint",
      "Accent wall",
      "Ceiling paint",
      "Trim and baseboards",
      "Whole house interior",
    ],
    priceMin: 200,
    priceMax: 2000,
    priceUnit: "flat",
    relatedSlugs: ["exterior-painting", "drywall-repair"],
    formFields: ["room_count", "area_sqft", "description", "photos"],
  },
  "exterior-painting": {
    slug: "exterior-painting",
    title: "Exterior Painting",
    shortTitle: "Exterior Paint",
    parentSlug: "painting",
    description: "Exterior house painting — siding, trim, doors, and decks.",
    commonProblems: [
      "Full exterior repaint",
      "Siding paint",
      "Trim only",
      "Front door repaint",
      "Deck/fence staining",
    ],
    priceMin: 500,
    priceMax: 5000,
    priceUnit: "flat",
    relatedSlugs: ["interior-painting", "pressure-washing-exterior"],
    formFields: ["home_size", "stories", "description", "photos"],
  },
  "popcorn-ceiling": {
    slug: "popcorn-ceiling",
    title: "Popcorn Ceiling Removal",
    shortTitle: "Popcorn Ceiling",
    parentSlug: "painting",
    description: "Remove popcorn/acoustic ceiling texture and apply smooth finish.",
    commonProblems: [
      "Popcorn ceiling removal",
      "Smooth finish after removal",
      "Partial area removal",
    ],
    priceMin: 300,
    priceMax: 1800,
    priceUnit: "sqft",
    relatedSlugs: ["interior-painting", "drywall-painting-texturing"],
    formFields: ["area_sqft", "description", "photos"],
  },
  "fence-deck-painting": {
    slug: "fence-deck-painting",
    title: "Fence & Deck Painting",
    shortTitle: "Fence & Deck",
    parentSlug: "painting",
    description: "Staining and painting for fences and decks. Protection and beauty.",
    commonProblems: [
      "Deck staining",
      "Fence painting",
      "Deck repaint",
      "Wood preservation",
    ],
    priceMin: 200,
    priceMax: 1500,
    priceUnit: "flat",
    relatedSlugs: ["exterior-painting", "pressure-washing-exterior"],
    formFields: ["area_sqft", "description", "photos"],
  },

  // ROOFING
  "roof-repair": {
    slug: "roof-repair",
    title: "Roof Repair",
    shortTitle: "Roof Repair",
    parentSlug: "roofing",
    description: "Fix leaks, missing shingles, storm damage, and flashing issues.",
    commonProblems: [
      "Roof leak",
      "Missing shingles",
      "Storm damage",
      "Flashing repair",
      "Sagging area",
    ],
    priceMin: 300,
    priceMax: 2500,
    priceUnit: "flat",
    relatedSlugs: ["roof-replacement", "gutter-installation-repair"],
    formFields: ["roof_type", "damage_type", "description", "photos"],
  },
  "roof-replacement": {
    slug: "roof-replacement",
    title: "Roof Replacement",
    shortTitle: "Roof Replacement",
    parentSlug: "roofing",
    description: "Full roof replacement with quality materials and warranty.",
    commonProblems: [
      "Full replacement needed",
      "Old roof 20+ years",
      "Multiple leaks",
      "Storm total loss",
    ],
    priceMin: 5000,
    priceMax: 20000,
    priceUnit: "flat",
    relatedSlugs: ["roof-repair", "storm-damage-restoration"],
    formFields: ["home_size", "roof_type", "description", "photos"],
  },
  "roof-installation": {
    slug: "roof-installation",
    title: "Roof Installation",
    shortTitle: "Roof Install",
    parentSlug: "roofing",
    description: "New construction roof installation for homes and additions.",
    commonProblems: ["New construction", "Addition roof", "Garage roof"],
    priceMin: 4000,
    priceMax: 18000,
    priceUnit: "flat",
    relatedSlugs: ["roof-replacement"],
    formFields: ["home_size", "roof_type", "description", "photos"],
  },
  "storm-damage-restoration": {
    slug: "storm-damage-restoration",
    title: "Storm Damage Restoration",
    shortTitle: "Storm Damage",
    parentSlug: "roofing",
    description: "Emergency storm damage repair — hail, wind, fallen trees.",
    commonProblems: [
      "Hail damage",
      "Wind damage",
      "Tree fell on roof",
      "Insurance claim help",
    ],
    priceMin: 500,
    priceMax: 15000,
    priceUnit: "flat",
    relatedSlugs: ["roof-repair", "roof-replacement"],
    formFields: ["damage_type", "description", "photos"],
  },
  "gutter-installation-repair": {
    slug: "gutter-installation-repair",
    title: "Gutter Installation & Repair",
    shortTitle: "Gutters",
    parentSlug: "roofing",
    description: "Install, repair, and clean gutters to protect your home.",
    commonProblems: [
      "Gutter leak",
      "Sagging gutter",
      "New gutter install",
      "Gutter cleaning",
      "Downspout repair",
    ],
    priceMin: 150,
    priceMax: 2000,
    priceUnit: "flat",
    relatedSlugs: ["roof-repair", "pressure-washing-exterior"],
    formFields: ["linear_ft", "description", "photos"],
  },
  "roof-inspections-maintenance": {
    slug: "roof-inspections-maintenance",
    title: "Roof Inspections & Maintenance",
    shortTitle: "Roof Inspection",
    parentSlug: "roofing",
    description: "Annual roof inspections and preventive maintenance.",
    commonProblems: [
      "Annual inspection",
      "Pre-purchase inspection",
      "Insurance inspection",
      "Preventive maintenance",
    ],
    priceMin: 150,
    priceMax: 500,
    priceUnit: "flat",
    relatedSlugs: ["roof-repair", "gutter-installation-repair"],
    formFields: ["home_size", "description"],
  },

  // REMODELING
  "kitchen-remodeling": {
    slug: "kitchen-remodeling",
    title: "Kitchen Remodeling",
    shortTitle: "Kitchen Remodel",
    parentSlug: "remodeling",
    description: "Full kitchen renovations — cabinets, countertops, flooring, and more.",
    commonProblems: [
      "Full kitchen remodel",
      "Cabinet replacement",
      "Countertop upgrade",
      "Layout change",
    ],
    priceMin: 5000,
    priceMax: 50000,
    priceUnit: "flat",
    relatedSlugs: ["cabinets-countertops", "backsplash-installation", "plumbing-fixtures"],
    formFields: ["kitchen_size", "scope", "description", "photos"],
  },
  "bathroom-remodeling": {
    slug: "bathroom-remodeling",
    title: "Bathroom Remodeling",
    shortTitle: "Bathroom Remodel",
    parentSlug: "remodeling",
    description: "Bathroom renovations — tile, fixtures, vanity, walk-in showers.",
    commonProblems: [
      "Full bathroom remodel",
      "Tile replacement",
      "Vanity upgrade",
      "Walk-in shower",
      "Tub-to-shower conversion",
    ],
    priceMin: 3000,
    priceMax: 30000,
    priceUnit: "flat",
    relatedSlugs: ["plumbing-fixtures", "flooring"],
    formFields: ["bathroom_size", "scope", "description", "photos"],
  },
  "basement-remodeling": {
    slug: "basement-remodeling",
    title: "Basement Remodeling",
    shortTitle: "Basement Remodel",
    parentSlug: "remodeling",
    description: "Finish or remodel your basement into livable space.",
    commonProblems: [
      "Unfinished basement",
      "Add bedroom",
      "Home office",
      "Media room",
      "Waterproofing needed",
    ],
    priceMin: 8000,
    priceMax: 60000,
    priceUnit: "flat",
    relatedSlugs: ["flooring", "lighting-electrical"],
    formFields: ["basement_sqft", "scope", "description", "photos"],
  },
  "cabinets-countertops": {
    slug: "cabinets-countertops",
    title: "Cabinets & Countertops",
    shortTitle: "Cabinets",
    parentSlug: "remodeling",
    description: "Cabinet installation, refacing, and countertop replacement.",
    commonProblems: [
      "New cabinets",
      "Cabinet refacing",
      "Countertop replacement",
      "Granite install",
      "Quartz install",
    ],
    priceMin: 1500,
    priceMax: 20000,
    priceUnit: "flat",
    relatedSlugs: ["kitchen-remodeling", "backsplash-installation"],
    formFields: ["material", "linear_ft", "description", "photos"],
  },
  "backsplash-installation": {
    slug: "backsplash-installation",
    title: "Backsplash Installation",
    shortTitle: "Backsplash",
    parentSlug: "remodeling",
    description: "Kitchen and bathroom backsplash tile installation.",
    commonProblems: [
      "New backsplash",
      "Tile replacement",
      "Subway tile",
      "Mosaic tile",
    ],
    priceMin: 400,
    priceMax: 2500,
    priceUnit: "flat",
    relatedSlugs: ["kitchen-remodeling", "cabinets-countertops"],
    formFields: ["area_sqft", "material", "description", "photos"],
  },
};

export function getSubcategoryBySlug(slug: string): Subcategory | undefined {
  return subcategories[slug];
}

export function getSubcategoriesByParent(parentSlug: string): Subcategory[] {
  return Object.values(subcategories).filter(
    (s) => s.parentSlug === parentSlug
  );
}

export function formatPriceRange(sub: Subcategory): string {
  return `$${sub.priceMin}–$${sub.priceMax}`;
}