import type { SubcategoryMap } from "../types";

export const junkSubcategories: SubcategoryMap = {
  "household-junk-removal": {
    slug: "household-junk-removal",
    title: "Household Junk Removal",
    shortTitle: "Household Junk",
    parentSlug: "junk",
    description:
      "Household junk removal for unwanted clutter, boxes, small furniture, garage items, storage items, and general home cleanout needs.",
    commonProblems: [
      "Unwanted household clutter",
      "Boxes and bagged junk",
      "Garage or basement junk",
      "Old small furniture",
      "Storage area cleanup",
      "Need same-day junk pickup",
    ],
    priceMin: 100,
    priceMax: 900,
    priceUnit: "flat",
    relatedSlugs: [
      "furniture-junk-removal",
      "garage-cleanout-service",
      "attic-basement-cleanout",
    ],
    formFields: [
      "Items to remove",
      "Approximate volume",
      "Room or area",
      "Stairs",
      "Parking access",
      "Photos available",
      "Preferred pickup time",
      "Donation items",
    ],
  },

  "furniture-junk-removal": {
    slug: "furniture-junk-removal",
    title: "Furniture Junk Removal",
    shortTitle: "Furniture Removal",
    parentSlug: "junk",
    description:
      "Furniture removal for couches, mattresses, tables, chairs, dressers, bed frames, cabinets, and bulky household items.",
    commonProblems: [
      "Old couch removal",
      "Mattress disposal",
      "Heavy dresser removal",
      "Bed frame removal",
      "Bulky furniture pickup",
      "Furniture too heavy to move alone",
    ],
    priceMin: 120,
    priceMax: 800,
    priceUnit: "flat",
    relatedSlugs: [
      "mattress-disposal-service",
      "household-junk-removal",
      "apartment-junk-removal",
    ],
    formFields: [
      "Furniture type",
      "Number of items",
      "Item size",
      "Stairs or elevator",
      "Disassembly needed",
      "Donation condition",
      "Photos available",
      "Pickup deadline",
    ],
  },

  "mattress-disposal-service": {
    slug: "mattress-disposal-service",
    title: "Mattress Disposal Service",
    shortTitle: "Mattress Disposal",
    parentSlug: "junk",
    description:
      "Mattress disposal and pickup for mattresses, box springs, bed bases, frames, and bedroom furniture removal.",
    commonProblems: [
      "Old mattress needs removal",
      "Box spring disposal",
      "Bed base pickup",
      "Bedroom cleanout",
      "Move-out mattress removal",
      "Need proper disposal",
    ],
    priceMin: 90,
    priceMax: 450,
    priceUnit: "flat",
    relatedSlugs: [
      "furniture-junk-removal",
      "apartment-junk-removal",
      "household-junk-removal",
    ],
    formFields: [
      "Mattress size",
      "Box spring included",
      "Bed frame included",
      "Floor level",
      "Elevator access",
      "Pickup location",
      "Photos available",
      "Preferred date",
    ],
  },

  "appliance-junk-hauling": {
    slug: "appliance-junk-hauling",
    title: "Appliance Junk Hauling",
    shortTitle: "Appliance Hauling",
    parentSlug: "junk",
    description:
      "Appliance junk hauling for old refrigerators, washers, dryers, dishwashers, ovens, freezers, and other large appliances.",
    commonProblems: [
      "Old appliance removal",
      "Washer or dryer pickup",
      "Refrigerator hauling",
      "Dishwasher disposal",
      "Heavy appliance upstairs",
      "Replacement appliance left behind",
    ],
    priceMin: 120,
    priceMax: 700,
    priceUnit: "flat",
    relatedSlugs: [
      "appliance-installation",
      "appliance-repair",
      "household-junk-removal",
    ],
    formFields: [
      "Appliance type",
      "Appliance size",
      "Disconnected already",
      "Floor level",
      "Stairs",
      "Doorway access",
      "Recycling preference",
      "Photos available",
    ],
  },

  "garage-cleanout-service": {
    slug: "garage-cleanout-service",
    title: "Garage Cleanout Service",
    shortTitle: "Garage Cleanout",
    parentSlug: "junk",
    description:
      "Garage cleanout help for stored junk, old tools, boxes, furniture, yard equipment, trash, donation piles, and bulky items.",
    commonProblems: [
      "Garage full of clutter",
      "Old boxes and storage items",
      "Bulky items blocking parking",
      "Donation and trash piles",
      "Pre-sale garage cleanup",
      "Need garage cleared quickly",
    ],
    priceMin: 200,
    priceMax: 1500,
    priceUnit: "flat",
    relatedSlugs: [
      "household-junk-removal",
      "yard-waste-removal",
      "attic-basement-cleanout",
    ],
    formFields: [
      "Garage size",
      "Approximate volume",
      "Items to remove",
      "Heavy items",
      "Donation items",
      "Trash items",
      "Photos available",
      "Deadline",
    ],
  },

  "attic-basement-cleanout": {
    slug: "attic-basement-cleanout",
    title: "Attic & Basement Cleanout",
    shortTitle: "Attic & Basement",
    parentSlug: "junk",
    description:
      "Attic and basement cleanout for stored belongings, boxes, old furniture, seasonal items, trash, and heavy or dusty items.",
    commonProblems: [
      "Basement clutter removal",
      "Attic storage cleanup",
      "Old boxes and furniture",
      "Difficult stair access",
      "Dusty stored items",
      "Estate or move-out cleanout",
    ],
    priceMin: 250,
    priceMax: 1800,
    priceUnit: "flat",
    relatedSlugs: [
      "estate-cleanout-service",
      "garage-cleanout-service",
      "household-junk-removal",
    ],
    formFields: [
      "Area type",
      "Approximate volume",
      "Access details",
      "Stairs",
      "Heavy items",
      "Dust or condition issues",
      "Photos available",
      "Preferred timing",
    ],
  },

  "construction-debris-removal": {
    slug: "construction-debris-removal",
    title: "Construction Debris Removal",
    shortTitle: "Construction Debris",
    parentSlug: "junk",
    description:
      "Construction debris removal for renovation waste, drywall, wood, flooring scraps, packaging, cabinets, fixtures, and light demolition debris.",
    commonProblems: [
      "Renovation debris pile",
      "Drywall and wood scraps",
      "Old cabinet debris",
      "Flooring removal waste",
      "Packaging and material waste",
      "Need jobsite cleaned up",
    ],
    priceMin: 250,
    priceMax: 2500,
    priceUnit: "flat",
    relatedSlugs: [
      "demolition-debris-removal",
      "remodeling-cleanup",
      "dumpster-alternative-junk-removal",
    ],
    formFields: [
      "Debris type",
      "Approximate volume",
      "Material weight",
      "Pickup location",
      "Driveway access",
      "Bagged or loose",
      "Photos available",
      "Project deadline",
    ],
  },

  "yard-waste-removal": {
    slug: "yard-waste-removal",
    title: "Yard Waste Removal",
    shortTitle: "Yard Waste",
    parentSlug: "junk",
    description:
      "Yard waste removal for branches, leaves, storm debris, brush, small logs, garden waste, old planters, and outdoor cleanup piles.",
    commonProblems: [
      "Branches and brush pile",
      "Storm yard debris",
      "Leaves and garden waste",
      "Old outdoor items",
      "Post-landscaping cleanup",
      "Need curbside pickup",
    ],
    priceMin: 120,
    priceMax: 1200,
    priceUnit: "flat",
    relatedSlugs: [
      "lawn-cleanup",
      "tree-debris-removal",
      "pressure-washing",
    ],
    formFields: [
      "Yard waste type",
      "Approximate pile size",
      "Bagged or loose",
      "Curbside or backyard",
      "Heavy logs",
      "Access for truck",
      "Photos available",
      "Preferred pickup time",
    ],
  },

  "estate-cleanout-service": {
    slug: "estate-cleanout-service",
    title: "Estate Cleanout Service",
    shortTitle: "Estate Cleanout",
    parentSlug: "junk",
    description:
      "Estate cleanout support for furniture, household items, storage areas, donation piles, trash removal, and property clearing after transitions.",
    commonProblems: [
      "Estate property cleanout",
      "Large amount of household items",
      "Donation and disposal sorting",
      "Furniture removal",
      "Garage or basement cleanout",
      "Family coordinating cleanup",
    ],
    priceMin: 500,
    priceMax: 5000,
    priceUnit: "flat",
    relatedSlugs: [
      "attic-basement-cleanout",
      "furniture-junk-removal",
      "garage-cleanout-service",
    ],
    formFields: [
      "Property size",
      "Rooms involved",
      "Item volume",
      "Donation items",
      "Trash items",
      "Family contact",
      "Access instructions",
      "Timeline",
    ],
  },

  "commercial-junk-removal": {
    slug: "commercial-junk-removal",
    title: "Commercial Junk Removal",
    shortTitle: "Commercial Junk",
    parentSlug: "junk",
    description:
      "Commercial junk removal for offices, retail spaces, warehouses, rental properties, equipment, fixtures, furniture, and business cleanouts.",
    commonProblems: [
      "Office furniture removal",
      "Retail cleanout",
      "Warehouse junk pickup",
      "Tenant left items behind",
      "Old equipment removal",
      "After-hours cleanup needed",
    ],
    priceMin: 300,
    priceMax: 6000,
    priceUnit: "flat",
    relatedSlugs: [
      "office-moving-service",
      "property-cleanout-service",
      "construction-debris-removal",
    ],
    formFields: [
      "Business type",
      "Items to remove",
      "Approximate volume",
      "Building access",
      "Loading dock",
      "After-hours needed",
      "Photos available",
      "Deadline",
    ],
  },

  "hot-tub-removal": {
    slug: "hot-tub-removal",
    title: "Hot Tub Removal",
    shortTitle: "Hot Tub Removal",
    parentSlug: "junk",
    description:
      "Hot tub removal for old spas, above-ground hot tubs, patio tubs, covers, frames, and related debris when removal or cutting is needed.",
    commonProblems: [
      "Old hot tub needs removal",
      "Spa no longer works",
      "Backyard access is tight",
      "Tub may need cutting",
      "Heavy item on patio or deck",
      "Need full debris hauled away",
    ],
    priceMin: 300,
    priceMax: 1500,
    priceUnit: "flat",
    relatedSlugs: [
      "demolition-debris-removal",
      "yard-waste-removal",
      "household-junk-removal",
    ],
    formFields: [
      "Hot tub size",
      "Location",
      "Access width",
      "Electrical disconnected",
      "Cutting needed",
      "Deck or patio location",
      "Photos available",
      "Preferred removal date",
    ],
  },

  "dumpster-alternative-junk-removal": {
    slug: "dumpster-alternative-junk-removal",
    title: "Dumpster Alternative Junk Removal",
    shortTitle: "Dumpster Alternative",
    parentSlug: "junk",
    description:
      "Junk removal as a dumpster alternative for homeowners who want loading, hauling, and disposal handled without renting a dumpster.",
    commonProblems: [
      "Need junk removed without dumpster rental",
      "No driveway space for dumpster",
      "Small renovation cleanup",
      "Move-out cleanout",
      "Bulky items mixed with trash",
      "Need loading included",
    ],
    priceMin: 200,
    priceMax: 2500,
    priceUnit: "flat",
    relatedSlugs: [
      "construction-debris-removal",
      "garage-cleanout-service",
      "household-junk-removal",
    ],
    formFields: [
      "Project type",
      "Approximate volume",
      "Material type",
      "Pickup location",
      "Access details",
      "Loading help needed",
      "Photos available",
      "Timeline",
    ],
  },
};