import type { SubcategoryMap } from "../types";

export const lawnSubcategories: SubcategoryMap = {
  "lawn-mowing-service": {
    slug: "lawn-mowing-service",
    title: "Lawn Mowing Service",
    shortTitle: "Lawn Mowing",
    parentSlug: "lawn-care",
    description:
      "Routine lawn mowing, edging, trimming, and basic yard cleanup for residential and small commercial properties.",
    commonProblems: [
      "Overgrown grass",
      "Uneven mowing",
      "Missed edges",
      "Fast seasonal growth",
      "Rental property lawn upkeep",
    ],
    priceMin: 45,
    priceMax: 150,
    priceUnit: "flat",
    relatedSlugs: [
      "yard-cleanup-service",
      "weed-control-service",
      "lawn-maintenance-service",
    ],
    formFields: [
      "propertyType",
      "yardSize",
      "grassHeight",
      "serviceFrequency",
      "gateAccess",
      "preferredDate",
      "photos",
    ],
  },

  "lawn-maintenance-service": {
    slug: "lawn-maintenance-service",
    title: "Lawn Maintenance Service",
    shortTitle: "Lawn Maintenance",
    parentSlug: "lawn-care",
    description:
      "Ongoing lawn care help including mowing, edging, trimming, light cleanup, seasonal care, and recurring property upkeep.",
    commonProblems: [
      "Lawn needs recurring care",
      "Busy homeowner schedule",
      "Rental or vacant property upkeep",
      "HOA lawn appearance issues",
      "Seasonal growth control",
    ],
    priceMin: 75,
    priceMax: 300,
    priceUnit: "flat",
    relatedSlugs: [
      "lawn-mowing-service",
      "weed-control-service",
      "seasonal-lawn-care",
    ],
    formFields: [
      "propertyType",
      "yardSize",
      "serviceFrequency",
      "currentCondition",
      "preferredSchedule",
      "photos",
    ],
  },

  "yard-cleanup-service": {
    slug: "yard-cleanup-service",
    title: "Yard Cleanup Service",
    shortTitle: "Yard Cleanup",
    parentSlug: "lawn-care",
    description:
      "One-time or seasonal yard cleanup for leaves, branches, weeds, storm debris, overgrowth, and general outdoor clutter.",
    commonProblems: [
      "Leaves covering yard",
      "Branches and debris",
      "Overgrown areas",
      "Move-out yard cleanup",
      "Storm cleanup needs",
    ],
    priceMin: 150,
    priceMax: 650,
    priceUnit: "flat",
    relatedSlugs: [
      "leaf-removal-service",
      "brush-removal-service",
      "lawn-mowing-service",
    ],
    formFields: [
      "yardSize",
      "debrisType",
      "debrisAmount",
      "haulAwayNeeded",
      "accessNotes",
      "preferredDate",
      "photos",
    ],
  },

  "leaf-removal-service": {
    slug: "leaf-removal-service",
    title: "Leaf Removal Service",
    shortTitle: "Leaf Removal",
    parentSlug: "lawn-care",
    description:
      "Leaf blowing, bagging, curbside pickup preparation, and seasonal leaf cleanup for yards, beds, patios, and driveways.",
    commonProblems: [
      "Heavy leaf buildup",
      "Leaves in flower beds",
      "Blocked walkways",
      "Wet packed leaves",
      "Seasonal fall cleanup",
    ],
    priceMin: 120,
    priceMax: 500,
    priceUnit: "flat",
    relatedSlugs: [
      "yard-cleanup-service",
      "gutter-cleaning",
      "lawn-maintenance-service",
    ],
    formFields: [
      "yardSize",
      "leafVolume",
      "baggingNeeded",
      "haulAwayNeeded",
      "preferredDate",
      "photos",
    ],
  },

  "weed-control-service": {
    slug: "weed-control-service",
    title: "Weed Control Service",
    shortTitle: "Weed Control",
    parentSlug: "lawn-care",
    description:
      "Weed removal, prevention, spot treatment coordination, and lawn or bed cleanup for unwanted growth.",
    commonProblems: [
      "Weeds spreading through lawn",
      "Weeds in beds or walkways",
      "Crabgrass or broadleaf weeds",
      "HOA appearance concerns",
      "Recurring weed growth",
    ],
    priceMin: 75,
    priceMax: 350,
    priceUnit: "flat",
    relatedSlugs: [
      "lawn-maintenance-service",
      "flower-bed-maintenance",
      "mulch-installation-service",
    ],
    formFields: [
      "areaType",
      "yardSize",
      "weedSeverity",
      "treatmentPreference",
      "petsOrChildren",
      "photos",
    ],
  },

  "mulch-installation-service": {
    slug: "mulch-installation-service",
    title: "Mulch Installation Service",
    shortTitle: "Mulch Installation",
    parentSlug: "lawn-care",
    description:
      "Mulch delivery coordination, bed preparation, weed barrier discussion, edging cleanup, and mulch spreading.",
    commonProblems: [
      "Old faded mulch",
      "Bare planting beds",
      "Weeds in beds",
      "Poor curb appeal",
      "Mulch washed away",
    ],
    priceMin: 250,
    priceMax: 1200,
    priceUnit: "flat",
    relatedSlugs: [
      "flower-bed-maintenance",
      "weed-control-service",
      "landscape-edging-service",
    ],
    formFields: [
      "bedArea",
      "mulchType",
      "mulchColor",
      "materialProvided",
      "weedBarrierNeeded",
      "photos",
    ],
  },

  "flower-bed-maintenance": {
    slug: "flower-bed-maintenance",
    title: "Flower Bed Maintenance",
    shortTitle: "Flower Bed Care",
    parentSlug: "lawn-care",
    description:
      "Flower bed weeding, cleanup, edging, trimming, mulch refresh, and general landscape bed maintenance.",
    commonProblems: [
      "Weeds in flower beds",
      "Overgrown plants",
      "Messy bed edges",
      "Old mulch",
      "Seasonal cleanup needed",
    ],
    priceMin: 150,
    priceMax: 700,
    priceUnit: "flat",
    relatedSlugs: [
      "mulch-installation-service",
      "weed-control-service",
      "landscape-edging-service",
    ],
    formFields: [
      "bedCount",
      "bedCondition",
      "weedingNeeded",
      "trimmingNeeded",
      "mulchNeeded",
      "photos",
    ],
  },

  "landscape-edging-service": {
    slug: "landscape-edging-service",
    title: "Landscape Edging Service",
    shortTitle: "Landscape Edging",
    parentSlug: "lawn-care",
    description:
      "Clean edging along beds, driveways, sidewalks, patios, and lawn borders for a sharper outdoor appearance.",
    commonProblems: [
      "Grass growing into beds",
      "Messy borders",
      "Overgrown sidewalk edges",
      "Poor curb appeal",
      "Need clean lawn lines",
    ],
    priceMin: 100,
    priceMax: 500,
    priceUnit: "flat",
    relatedSlugs: [
      "lawn-mowing-service",
      "flower-bed-maintenance",
      "mulch-installation-service",
    ],
    formFields: [
      "edgeAreas",
      "linearFeet",
      "overgrowthLevel",
      "materialEdgingNeeded",
      "photos",
    ],
  },

  "sod-installation-service": {
    slug: "sod-installation-service",
    title: "Sod Installation Service",
    shortTitle: "Sod Installation",
    parentSlug: "lawn-care",
    description:
      "Sod installation for bare yards, damaged grass areas, new lawns, patches, and curb appeal improvements.",
    commonProblems: [
      "Bare lawn areas",
      "Dead grass",
      "Patchy yard",
      "New construction yard",
      "Erosion or muddy areas",
    ],
    priceMin: 900,
    priceMax: 6500,
    priceUnit: "sqft",
    relatedSlugs: [
      "lawn-repair-service",
      "lawn-grading-leveling",
      "sprinkler-repair-service",
    ],
    formFields: [
      "areaSquareFeet",
      "currentSurface",
      "sodType",
      "soilPrepNeeded",
      "irrigationAvailable",
      "photos",
    ],
  },

  "lawn-repair-service": {
    slug: "lawn-repair-service",
    title: "Lawn Repair Service",
    shortTitle: "Lawn Repair",
    parentSlug: "lawn-care",
    description:
      "Repair help for patchy lawns, bare spots, thinning grass, pet damage, erosion, and damaged turf areas.",
    commonProblems: [
      "Bare spots",
      "Pet damage",
      "Thin grass",
      "Dead patches",
      "Washed-out lawn areas",
    ],
    priceMin: 150,
    priceMax: 1200,
    priceUnit: "flat",
    relatedSlugs: [
      "grass-seeding-overseeding",
      "sod-installation-service",
      "lawn-aeration-service",
    ],
    formFields: [
      "damageType",
      "affectedArea",
      "grassType",
      "wateringAvailable",
      "repairPreference",
      "photos",
    ],
  },

  "grass-seeding-overseeding": {
    slug: "grass-seeding-overseeding",
    title: "Grass Seeding and Overseeding",
    shortTitle: "Seeding",
    parentSlug: "lawn-care",
    description:
      "Grass seeding and overseeding for thin lawns, bare spots, seasonal lawn improvement, and turf recovery.",
    commonProblems: [
      "Thin lawn",
      "Bare spots",
      "Seasonal lawn decline",
      "Poor grass density",
      "Patchy growth",
    ],
    priceMin: 200,
    priceMax: 1500,
    priceUnit: "flat",
    relatedSlugs: [
      "lawn-aeration-service",
      "lawn-repair-service",
      "lawn-fertilization-service",
    ],
    formFields: [
      "yardSize",
      "grassType",
      "bareSpotSeverity",
      "aerationNeeded",
      "wateringPlan",
      "photos",
    ],
  },

  "lawn-aeration-service": {
    slug: "lawn-aeration-service",
    title: "Lawn Aeration Service",
    shortTitle: "Lawn Aeration",
    parentSlug: "lawn-care",
    description:
      "Core aeration service to reduce soil compaction and support healthier grass growth, often paired with overseeding.",
    commonProblems: [
      "Compacted soil",
      "Thin grass",
      "Poor water absorption",
      "Heavy foot traffic",
      "Seasonal lawn stress",
    ],
    priceMin: 100,
    priceMax: 400,
    priceUnit: "flat",
    relatedSlugs: [
      "grass-seeding-overseeding",
      "lawn-fertilization-service",
      "lawn-repair-service",
    ],
    formFields: [
      "yardSize",
      "soilCondition",
      "overseedingNeeded",
      "gateAccess",
      "preferredDate",
      "photos",
    ],
  },

  "lawn-fertilization-service": {
    slug: "lawn-fertilization-service",
    title: "Lawn Fertilization Service",
    shortTitle: "Fertilization",
    parentSlug: "lawn-care",
    description:
      "Lawn fertilization coordination for healthier turf, seasonal growth support, and improved grass color.",
    commonProblems: [
      "Pale grass",
      "Slow growth",
      "Thin lawn",
      "Seasonal lawn stress",
      "Uneven lawn color",
    ],
    priceMin: 75,
    priceMax: 300,
    priceUnit: "flat",
    relatedSlugs: [
      "weed-control-service",
      "grass-seeding-overseeding",
      "lawn-aeration-service",
    ],
    formFields: [
      "yardSize",
      "grassCondition",
      "treatmentFrequency",
      "petsOrChildren",
      "preferredDate",
      "photos",
    ],
  },

  "brush-removal-service": {
    slug: "brush-removal-service",
    title: "Brush Removal Service",
    shortTitle: "Brush Removal",
    parentSlug: "lawn-care",
    description:
      "Brush clearing, vine removal, small overgrowth cleanup, and outdoor debris removal for yards and property edges.",
    commonProblems: [
      "Overgrown brush",
      "Vines taking over",
      "Blocked property edges",
      "Small unwanted growth",
      "Yard debris piles",
    ],
    priceMin: 250,
    priceMax: 1500,
    priceUnit: "flat",
    relatedSlugs: [
      "yard-cleanup-service",
      "hedge-trimming-service",
      "small-tree-shrub-removal",
    ],
    formFields: [
      "areaSize",
      "brushDensity",
      "haulAwayNeeded",
      "accessNotes",
      "equipmentAccess",
      "photos",
    ],
  },

  "hedge-trimming-service": {
    slug: "hedge-trimming-service",
    title: "Hedge Trimming Service",
    shortTitle: "Hedge Trimming",
    parentSlug: "lawn-care",
    description:
      "Hedge trimming, shrub shaping, light pruning, and cleanup for landscape borders and curb appeal.",
    commonProblems: [
      "Overgrown hedges",
      "Uneven shrubs",
      "Blocked windows or walkways",
      "Messy landscape appearance",
      "Seasonal trimming needed",
    ],
    priceMin: 100,
    priceMax: 600,
    priceUnit: "flat",
    relatedSlugs: [
      "flower-bed-maintenance",
      "brush-removal-service",
      "yard-cleanup-service",
    ],
    formFields: [
      "hedgeCount",
      "hedgeHeight",
      "trimmingGoal",
      "haulAwayNeeded",
      "photos",
    ],
  },

  "small-tree-shrub-removal": {
    slug: "small-tree-shrub-removal",
    title: "Small Tree and Shrub Removal",
    shortTitle: "Shrub Removal",
    parentSlug: "lawn-care",
    description:
      "Removal of small shrubs, bushes, saplings, and light yard growth that does not require large tree equipment.",
    commonProblems: [
      "Dead shrubs",
      "Unwanted bushes",
      "Small saplings",
      "Roots near beds",
      "Overgrown landscape areas",
    ],
    priceMin: 150,
    priceMax: 900,
    priceUnit: "flat",
    relatedSlugs: [
      "brush-removal-service",
      "yard-cleanup-service",
      "flower-bed-maintenance",
    ],
    formFields: [
      "itemCount",
      "itemHeight",
      "rootRemovalNeeded",
      "haulAwayNeeded",
      "accessNotes",
      "photos",
    ],
  },

  "lawn-grading-leveling": {
    slug: "lawn-grading-leveling",
    title: "Lawn Grading and Leveling",
    shortTitle: "Lawn Leveling",
    parentSlug: "lawn-care",
    description:
      "Light lawn grading, leveling, low spot correction, soil spreading, and yard surface improvement.",
    commonProblems: [
      "Uneven lawn",
      "Low spots",
      "Standing water",
      "Bumpy grass",
      "Soil washout",
    ],
    priceMin: 400,
    priceMax: 3500,
    priceUnit: "flat",
    relatedSlugs: [
      "sod-installation-service",
      "lawn-repair-service",
      "drainage-solutions",
    ],
    formFields: [
      "areaSize",
      "gradingIssue",
      "soilNeeded",
      "drainageConcern",
      "equipmentAccess",
      "photos",
    ],
  },

  "seasonal-lawn-care": {
    slug: "seasonal-lawn-care",
    title: "Seasonal Lawn Care",
    shortTitle: "Seasonal Lawn Care",
    parentSlug: "lawn-care",
    description:
      "Seasonal lawn care for spring cleanup, summer growth, fall leaves, winter prep, and recurring outdoor maintenance.",
    commonProblems: [
      "Spring cleanup needed",
      "Summer growth control",
      "Fall leaves",
      "Winter yard prep",
      "Seasonal curb appeal",
    ],
    priceMin: 150,
    priceMax: 900,
    priceUnit: "flat",
    relatedSlugs: [
      "yard-cleanup-service",
      "leaf-removal-service",
      "lawn-maintenance-service",
    ],
    formFields: [
      "season",
      "yardSize",
      "servicesNeeded",
      "serviceFrequency",
      "preferredDate",
      "photos",
    ],
  },

  "sprinkler-repair-service": {
    slug: "sprinkler-repair-service",
    title: "Sprinkler Repair Service",
    shortTitle: "Sprinkler Repair",
    parentSlug: "lawn-care",
    description:
      "Sprinkler troubleshooting, broken head repair coordination, coverage issues, leaks, and irrigation zone problems.",
    commonProblems: [
      "Broken sprinkler head",
      "Dry lawn spots",
      "Leaking sprinkler",
      "Zone not working",
      "Uneven water coverage",
    ],
    priceMin: 100,
    priceMax: 600,
    priceUnit: "flat",
    relatedSlugs: [
      "lawn-repair-service",
      "sod-installation-service",
      "lawn-maintenance-service",
    ],
    formFields: [
      "systemType",
      "issueType",
      "zoneCount",
      "visibleLeak",
      "controllerAccess",
      "photos",
    ],
  },
};