import type { SubcategoryMap } from "../types";

export const maintenanceSubcategories: SubcategoryMap = {
  "home-maintenance-services": {
    slug: "home-maintenance-services",
    title: "Home Maintenance Services",
    shortTitle: "Home Maintenance",
    parentSlug: "maintenance",
    description:
      "General home maintenance, small repairs, seasonal upkeep, fixture checks, and punch list support for homeowners.",
    commonProblems: [
      "Multiple small maintenance tasks around the house",
      "Loose fixtures, doors, or hardware",
      "Seasonal home upkeep needed",
      "Small repairs before guests or sale",
      "Preventive maintenance tasks piling up",
      "General home punch list needs help",
    ],
    priceMin: 120,
    priceMax: 900,
    priceUnit: "flat",
    relatedSlugs: [
      "seasonal-home-maintenance",
      "preventive-home-maintenance",
      "handyman-maintenance-repairs",
    ],
    formFields: [
      "Property type",
      "Task list",
      "Photos",
      "Preferred timing",
      "Access notes",
      "Urgency",
    ],
  },

  "seasonal-home-maintenance": {
    slug: "seasonal-home-maintenance",
    title: "Seasonal Home Maintenance",
    shortTitle: "Seasonal Maintenance",
    parentSlug: "maintenance",
    description:
      "Seasonal maintenance for homes, including inspection, exterior checks, weather preparation, cleanup coordination, and minor repairs.",
    commonProblems: [
      "Home needs spring or fall maintenance",
      "Exterior needs checking before weather changes",
      "Gutters, vents, doors, or seals need attention",
      "Small seasonal repairs are overdue",
      "Property needs preparation before storms or cold weather",
      "Owner wants a preventive seasonal checklist completed",
    ],
    priceMin: 150,
    priceMax: 1200,
    priceUnit: "flat",
    relatedSlugs: [
      "home-maintenance-services",
      "gutter-cleaning-maintenance",
      "exterior-property-maintenance",
    ],
    formFields: [
      "Season",
      "Property size",
      "Main concerns",
      "Exterior access",
      "Photos",
      "Preferred service date",
    ],
  },

  "preventive-home-maintenance": {
    slug: "preventive-home-maintenance",
    title: "Preventive Home Maintenance",
    shortTitle: "Preventive Maintenance",
    parentSlug: "maintenance",
    description:
      "Preventive maintenance services to help catch small home issues before they become larger repairs.",
    commonProblems: [
      "Owner wants routine home checks",
      "Small issues keep coming back",
      "Doors, fixtures, drains, or exterior areas need inspection",
      "Property needs maintenance before listing or renting",
      "Minor leaks, cracks, or wear need early attention",
      "Home has not had maintenance in a long time",
    ],
    priceMin: 175,
    priceMax: 1500,
    priceUnit: "flat",
    relatedSlugs: [
      "home-maintenance-services",
      "property-inspection-maintenance",
      "handyman-maintenance-repairs",
    ],
    formFields: [
      "Property age",
      "Areas to check",
      "Known issues",
      "Photos",
      "Preferred timing",
      "Access details",
    ],
  },

  "rental-property-maintenance": {
    slug: "rental-property-maintenance",
    title: "Rental Property Maintenance",
    shortTitle: "Rental Maintenance",
    parentSlug: "maintenance",
    description:
      "Maintenance support for rental homes, apartments, turnovers, tenant repair requests, and landlord punch lists.",
    commonProblems: [
      "Tenant reported repair or maintenance issue",
      "Rental needs turnover repairs",
      "Move-in or move-out punch list needs completion",
      "Small repairs needed between tenants",
      "Landlord needs local maintenance support",
      "Vacant rental needs inspection or cleanup coordination",
    ],
    priceMin: 150,
    priceMax: 2500,
    priceUnit: "flat",
    relatedSlugs: [
      "move-in-move-out-maintenance",
      "property-inspection-maintenance",
      "handyman-maintenance-repairs",
    ],
    formFields: [
      "Rental type",
      "Tenant access status",
      "Task list",
      "Photos",
      "Deadline",
      "Property access instructions",
    ],
  },

  "move-in-move-out-maintenance": {
    slug: "move-in-move-out-maintenance",
    title: "Move-In and Move-Out Maintenance",
    shortTitle: "Move-In / Move-Out",
    parentSlug: "maintenance",
    description:
      "Maintenance help before or after a move, including small repairs, fixture checks, wall touch-ups, hardware, and punch list tasks.",
    commonProblems: [
      "Home needs repairs before move-in",
      "Move-out punch list needs completion",
      "Small wall, door, fixture, or hardware issues",
      "Rental or sale prep maintenance needed",
      "Previous occupant left minor damage",
      "Property needs quick readiness work",
    ],
    priceMin: 175,
    priceMax: 1800,
    priceUnit: "flat",
    relatedSlugs: [
      "rental-property-maintenance",
      "home-maintenance-services",
      "handyman-maintenance-repairs",
    ],
    formFields: [
      "Move type",
      "Deadline",
      "Task list",
      "Photos",
      "Access details",
      "Materials needed",
    ],
  },

  "handyman-maintenance-repairs": {
    slug: "handyman-maintenance-repairs",
    title: "Handyman Maintenance Repairs",
    shortTitle: "Maintenance Repairs",
    parentSlug: "maintenance",
    description:
      "Small repair and maintenance help for doors, hardware, drywall patches, fixtures, caulking, shelves, cabinets, and home punch lists.",
    commonProblems: [
      "Multiple small repairs need one visit",
      "Door, cabinet, or fixture is loose",
      "Drywall patch or caulking needs attention",
      "Shelves, hardware, or trim need repair",
      "Home inspection punch list has minor items",
      "Owner needs a practical maintenance pro",
    ],
    priceMin: 125,
    priceMax: 1200,
    priceUnit: "flat",
    relatedSlugs: [
      "home-maintenance-services",
      "preventive-home-maintenance",
      "move-in-move-out-maintenance",
    ],
    formFields: [
      "Repair list",
      "Photos",
      "Materials on site",
      "Access notes",
      "Preferred timing",
      "Urgency",
    ],
  },

  "exterior-property-maintenance": {
    slug: "exterior-property-maintenance",
    title: "Exterior Property Maintenance",
    shortTitle: "Exterior Maintenance",
    parentSlug: "maintenance",
    description:
      "Exterior maintenance for siding, trim, walkways, doors, outdoor fixtures, light cleanup, and curb appeal preparation.",
    commonProblems: [
      "Exterior areas need cleanup or minor repair",
      "Trim, doors, or outdoor fixtures need attention",
      "Walkway or entry area needs maintenance",
      "Curb appeal needs improvement before sale or rent",
      "Small exterior repairs are overdue",
      "Property needs weather-related exterior checks",
    ],
    priceMin: 180,
    priceMax: 2500,
    priceUnit: "flat",
    relatedSlugs: [
      "seasonal-home-maintenance",
      "gutter-cleaning-maintenance",
      "pressure-washing-maintenance",
    ],
    formFields: [
      "Exterior areas",
      "Property type",
      "Photos",
      "Access notes",
      "Height or ladder needs",
      "Preferred timing",
    ],
  },

  "gutter-cleaning-maintenance": {
    slug: "gutter-cleaning-maintenance",
    title: "Gutter Cleaning and Maintenance",
    shortTitle: "Gutter Maintenance",
    parentSlug: "maintenance",
    description:
      "Gutter cleaning, minor gutter maintenance, downspout checks, and drainage issue support for residential properties.",
    commonProblems: [
      "Gutters are clogged",
      "Water is overflowing near the roofline",
      "Downspouts are blocked or disconnected",
      "Leaves and debris are collecting in gutters",
      "Drainage is causing water near the foundation",
      "Seasonal gutter maintenance is overdue",
    ],
    priceMin: 125,
    priceMax: 850,
    priceUnit: "flat",
    relatedSlugs: [
      "seasonal-home-maintenance",
      "exterior-property-maintenance",
      "preventive-home-maintenance",
    ],
    formFields: [
      "Number of stories",
      "Gutter condition",
      "Downspout issues",
      "Photos",
      "Ladder access",
      "Preferred timing",
    ],
  },

  "property-inspection-maintenance": {
    slug: "property-inspection-maintenance",
    title: "Property Inspection Maintenance",
    shortTitle: "Inspection Maintenance",
    parentSlug: "maintenance",
    description:
      "Maintenance walk-throughs, issue documentation, repair prioritization, and punch list support for homes, rentals, and small properties.",
    commonProblems: [
      "Owner needs a maintenance walk-through",
      "Property has unknown repair issues",
      "Rental or vacant home needs condition check",
      "Inspection report has repair items",
      "Maintenance priorities need sorting",
      "Photos and notes are needed before repairs",
    ],
    priceMin: 150,
    priceMax: 900,
    priceUnit: "flat",
    relatedSlugs: [
      "preventive-home-maintenance",
      "rental-property-maintenance",
      "home-maintenance-services",
    ],
    formFields: [
      "Inspection reason",
      "Property type",
      "Areas to check",
      "Photos requested",
      "Access details",
      "Report needs",
    ],
  },

  "commercial-property-maintenance": {
    slug: "commercial-property-maintenance",
    title: "Commercial Property Maintenance",
    shortTitle: "Commercial Maintenance",
    parentSlug: "maintenance",
    description:
      "Maintenance support for small commercial spaces, offices, retail units, common areas, fixtures, doors, and recurring repair needs.",
    commonProblems: [
      "Office or retail space needs maintenance",
      "Common area has repair issues",
      "Door, fixture, restroom, or hardware needs attention",
      "Tenant improvement punch list needs completion",
      "Business needs after-hours maintenance",
      "Small commercial property needs recurring support",
    ],
    priceMin: 250,
    priceMax: 5000,
    priceUnit: "flat",
    relatedSlugs: [
      "handyman-maintenance-repairs",
      "preventive-home-maintenance",
      "property-inspection-maintenance",
    ],
    formFields: [
      "Business type",
      "Maintenance issue",
      "Photos",
      "Access hours",
      "Insurance or COI requirements",
      "Urgency",
    ],
  },
};