import type { SubcategoryMap } from "../types";

export const movingSubcategories: SubcategoryMap = {
  "local-moving-service": {
    slug: "local-moving-service",
    title: "Local Moving Service",
    shortTitle: "Local Moving",
    parentSlug: "moving",
    description:
      "Local moving help for homes, apartments, condos, townhomes, and small moves within the same city or nearby area.",
    commonProblems: [
      "Need movers for a local move",
      "Moving from one home to another nearby",
      "Apartment move with stairs or elevator access",
      "Short-distance furniture and box transport",
      "Need same-day local moving help",
      "Need help moving without renting a large crew",
    ],
    priceMin: 250,
    priceMax: 1800,
    priceUnit: "flat",
    relatedSlugs: [
      "apartment-moving-service",
      "packing-unpacking-service",
      "loading-unloading-service",
    ],
    formFields: [
      "Move date",
      "Pickup address type",
      "Drop-off address type",
      "Number of rooms",
      "Stairs or elevator",
      "Large items",
      "Packing needed",
      "Preferred time window",
    ],
  },

  "long-distance-moving-service": {
    slug: "long-distance-moving-service",
    title: "Long Distance Moving Service",
    shortTitle: "Long Distance Moving",
    parentSlug: "moving",
    description:
      "Long-distance moving support for interstate, cross-state, and larger relocation projects that need planning, loading, transport coordination, and delivery timing.",
    commonProblems: [
      "Moving to another city or state",
      "Need long-distance movers",
      "Need help coordinating pickup and delivery",
      "Large home relocation",
      "Furniture and boxes need protected transport",
      "Need move estimate before choosing a pro",
    ],
    priceMin: 1200,
    priceMax: 9000,
    priceUnit: "flat",
    relatedSlugs: [
      "packing-unpacking-service",
      "loading-unloading-service",
      "storage-moving-service",
    ],
    formFields: [
      "Pickup city",
      "Delivery city",
      "Move date",
      "Home size",
      "Inventory list",
      "Packing needed",
      "Storage needed",
      "Delivery flexibility",
    ],
  },

  "apartment-moving-service": {
    slug: "apartment-moving-service",
    title: "Apartment Moving Service",
    shortTitle: "Apartment Moving",
    parentSlug: "moving",
    description:
      "Apartment moving help for studios, one-bedroom units, multi-bedroom apartments, condos, and buildings with elevators, stairs, parking limits, or move-in rules.",
    commonProblems: [
      "Moving out of an apartment",
      "Elevator reservation required",
      "Limited parking for moving truck",
      "Need movers for stairs",
      "Small apartment move",
      "Move-in or move-out deadline",
    ],
    priceMin: 250,
    priceMax: 1600,
    priceUnit: "flat",
    relatedSlugs: [
      "local-moving-service",
      "furniture-moving-service",
      "packing-unpacking-service",
    ],
    formFields: [
      "Apartment size",
      "Floor level",
      "Elevator access",
      "Parking details",
      "Move date",
      "Large items",
      "Building requirements",
      "Packing needed",
    ],
  },

  "furniture-moving-service": {
    slug: "furniture-moving-service",
    title: "Furniture Moving Service",
    shortTitle: "Furniture Moving",
    parentSlug: "moving",
    description:
      "Furniture moving help for couches, beds, dressers, tables, cabinets, patio furniture, office furniture, and heavy household items.",
    commonProblems: [
      "Need couch moved",
      "Heavy furniture upstairs",
      "Furniture pickup and delivery",
      "Need help rearranging large items",
      "Furniture will not fit through doorway",
      "Need two-person lifting help",
    ],
    priceMin: 120,
    priceMax: 900,
    priceUnit: "flat",
    relatedSlugs: [
      "labor-only-moving-help",
      "loading-unloading-service",
      "local-moving-service",
    ],
    formFields: [
      "Item list",
      "Item size",
      "Pickup location",
      "Drop-off location",
      "Stairs",
      "Disassembly needed",
      "Assembly needed",
      "Preferred timing",
    ],
  },

  "packing-unpacking-service": {
    slug: "packing-unpacking-service",
    title: "Packing and Unpacking Service",
    shortTitle: "Packing & Unpacking",
    parentSlug: "moving",
    description:
      "Packing and unpacking help for boxes, fragile items, kitchens, closets, bedrooms, offices, and move preparation.",
    commonProblems: [
      "Need boxes packed before move",
      "Fragile items need protection",
      "Kitchen packing takes too long",
      "Need unpacking after move",
      "Need help organizing boxes",
      "Short timeline before moving day",
    ],
    priceMin: 150,
    priceMax: 1500,
    priceUnit: "flat",
    relatedSlugs: [
      "local-moving-service",
      "long-distance-moving-service",
      "senior-moving-service",
    ],
    formFields: [
      "Rooms to pack",
      "Fragile items",
      "Packing supplies available",
      "Unpacking needed",
      "Move date",
      "Number of boxes",
      "Organization preferences",
      "Time window",
    ],
  },

  "labor-only-moving-help": {
    slug: "labor-only-moving-help",
    title: "Labor Only Moving Help",
    shortTitle: "Labor Only Moving",
    parentSlug: "moving",
    description:
      "Moving labor help when you already have a truck, trailer, container, storage unit, or rental vehicle and only need movers for lifting, carrying, loading, or unloading.",
    commonProblems: [
      "Already rented a truck",
      "Need help loading a moving container",
      "Need movers without a truck",
      "Heavy items need lifting",
      "Need help for a few hours",
      "Need same-day moving labor",
    ],
    priceMin: 120,
    priceMax: 800,
    priceUnit: "hourly",
    relatedSlugs: [
      "loading-unloading-service",
      "furniture-moving-service",
      "storage-moving-service",
    ],
    formFields: [
      "Labor needed",
      "Estimated hours",
      "Number of movers",
      "Truck or container type",
      "Stairs",
      "Heavy items",
      "Date and time",
      "Location access",
    ],
  },

  "loading-unloading-service": {
    slug: "loading-unloading-service",
    title: "Loading and Unloading Service",
    shortTitle: "Loading & Unloading",
    parentSlug: "moving",
    description:
      "Loading and unloading help for rental trucks, moving containers, trailers, storage units, garages, apartments, and homes.",
    commonProblems: [
      "Need truck loaded safely",
      "Need moving container unloaded",
      "Storage unit loading",
      "Items need to be stacked correctly",
      "Heavy furniture needs two-person handling",
      "Need help unloading after arrival",
    ],
    priceMin: 150,
    priceMax: 900,
    priceUnit: "hourly",
    relatedSlugs: [
      "labor-only-moving-help",
      "furniture-moving-service",
      "storage-moving-service",
    ],
    formFields: [
      "Load or unload",
      "Truck or container size",
      "Number of rooms",
      "Heavy items",
      "Stairs",
      "Distance from parking",
      "Preferred date",
      "Estimated hours",
    ],
  },

  "office-moving-service": {
    slug: "office-moving-service",
    title: "Office Moving Service",
    shortTitle: "Office Moving",
    parentSlug: "moving",
    description:
      "Office moving help for desks, chairs, conference rooms, file cabinets, small business equipment, retail spaces, and commercial relocations.",
    commonProblems: [
      "Business relocation",
      "Office furniture move",
      "Need weekend or after-hours move",
      "File cabinets and desks need moving",
      "Retail or small office move",
      "Need limited downtime",
    ],
    priceMin: 500,
    priceMax: 6000,
    priceUnit: "flat",
    relatedSlugs: [
      "furniture-moving-service",
      "packing-unpacking-service",
      "loading-unloading-service",
    ],
    formFields: [
      "Business type",
      "Office size",
      "Furniture list",
      "Equipment list",
      "Move date",
      "After-hours needed",
      "Building access",
      "Downtime limits",
    ],
  },

  "piano-moving-service": {
    slug: "piano-moving-service",
    title: "Piano Moving Service",
    shortTitle: "Piano Moving",
    parentSlug: "moving",
    description:
      "Piano moving help for upright pianos, baby grand pianos, digital pianos, and heavy specialty instruments that need careful handling.",
    commonProblems: [
      "Need piano moved safely",
      "Piano must go up or down stairs",
      "Heavy specialty item",
      "Need protection for floors and walls",
      "Piano pickup and delivery",
      "Need experienced movers for fragile item",
    ],
    priceMin: 250,
    priceMax: 1800,
    priceUnit: "flat",
    relatedSlugs: [
      "furniture-moving-service",
      "labor-only-moving-help",
      "local-moving-service",
    ],
    formFields: [
      "Piano type",
      "Pickup floor",
      "Drop-off floor",
      "Stairs",
      "Distance",
      "Tight turns",
      "Preferred date",
      "Photos available",
    ],
  },

  "senior-moving-service": {
    slug: "senior-moving-service",
    title: "Senior Moving Service",
    shortTitle: "Senior Moving",
    parentSlug: "moving",
    description:
      "Senior moving help for downsizing, assisted living moves, family-supported relocations, packing, unpacking, organization, and careful handling of belongings.",
    commonProblems: [
      "Downsizing from a larger home",
      "Moving to assisted living",
      "Need patient packing help",
      "Family coordinating the move",
      "Need unpacking and setup",
      "Important items need careful handling",
    ],
    priceMin: 300,
    priceMax: 2500,
    priceUnit: "flat",
    relatedSlugs: [
      "packing-unpacking-service",
      "local-moving-service",
      "moving-junk-removal",
    ],
    formFields: [
      "Move type",
      "Rooms involved",
      "Packing needed",
      "Unpacking needed",
      "Donation or disposal items",
      "Family contact",
      "Move date",
      "Special handling needs",
    ],
  },

  "moving-junk-removal": {
    slug: "moving-junk-removal",
    title: "Moving Junk Removal",
    shortTitle: "Moving Junk Removal",
    parentSlug: "moving",
    description:
      "Junk removal before, during, or after a move for unwanted furniture, boxes, garage items, donation piles, trash, and move-out cleanout needs.",
    commonProblems: [
      "Unwanted items before moving",
      "Old furniture left behind",
      "Garage cleanout before move",
      "Donation and disposal piles",
      "Move-out junk removal",
      "Need property cleared before deadline",
    ],
    priceMin: 150,
    priceMax: 1200,
    priceUnit: "flat",
    relatedSlugs: [
      "senior-moving-service",
      "packing-unpacking-service",
      "local-moving-service",
    ],
    formFields: [
      "Items to remove",
      "Approximate volume",
      "Stairs",
      "Donation items",
      "Disposal items",
      "Move-out deadline",
      "Photos available",
      "Preferred timing",
    ],
  },

  "storage-moving-service": {
    slug: "storage-moving-service",
    title: "Storage Moving Service",
    shortTitle: "Storage Moving",
    parentSlug: "moving",
    description:
      "Storage moving help for loading, unloading, organizing, or relocating items into or out of storage units, garages, pods, and moving containers.",
    commonProblems: [
      "Moving items into storage",
      "Storage unit needs unloading",
      "Need storage unit organized",
      "Container loading for storage",
      "Furniture needs protection in storage",
      "Need help moving items between storage and home",
    ],
    priceMin: 150,
    priceMax: 1200,
    priceUnit: "flat",
    relatedSlugs: [
      "loading-unloading-service",
      "labor-only-moving-help",
      "furniture-moving-service",
    ],
    formFields: [
      "Storage type",
      "Load or unload",
      "Unit size",
      "Item list",
      "Stairs or elevator",
      "Truck available",
      "Organization needed",
      "Preferred date",
    ],
  },
};