import type { SubcategoryMap } from "../types";

export const paintingSubcategories: SubcategoryMap = {
  // PAINTING
  "interior-painting": {
    slug: "interior-painting",
    title: "Interior Painting",
    shortTitle: "Interior Paint",
    parentSlug: "painting",
    description: "Professional interior painting for rooms, ceilings, and trim.",
    commonProblems: [
      "Full room repaint",
      "Accent wall",
      "Ceiling paint",
      "Trim and baseboards",
      "Whole house interior",
    ],
    priceMin: 200,
    priceMax: 2000,
    priceUnit: "flat",
    relatedSlugs: ["exterior-painting", "drywall-repair"],
    formFields: ["room_count", "area_sqft", "description", "photos"],
  },
  "exterior-painting": {
    slug: "exterior-painting",
    title: "Exterior Painting",
    shortTitle: "Exterior Paint",
    parentSlug: "painting",
    description: "Exterior house painting — siding, trim, doors, and decks.",
    commonProblems: [
      "Full exterior repaint",
      "Siding paint",
      "Trim only",
      "Front door repaint",
      "Deck/fence staining",
    ],
    priceMin: 500,
    priceMax: 5000,
    priceUnit: "flat",
    relatedSlugs: ["interior-painting", "pressure-washing-exterior"],
    formFields: ["home_size", "stories", "description", "photos"],
  },
  "popcorn-ceiling": {
    slug: "popcorn-ceiling",
    title: "Popcorn Ceiling Removal",
    shortTitle: "Popcorn Ceiling",
    parentSlug: "painting",
    description: "Remove popcorn/acoustic ceiling texture and apply smooth finish.",
    commonProblems: [
      "Popcorn ceiling removal",
      "Smooth finish after removal",
      "Partial area removal",
    ],
    priceMin: 300,
    priceMax: 1800,
    priceUnit: "sqft",
    relatedSlugs: ["interior-painting", "drywall-painting-texturing"],
    formFields: ["area_sqft", "description", "photos"],
  },
  "fence-deck-painting": {
    slug: "fence-deck-painting",
    title: "Fence & Deck Painting",
    shortTitle: "Fence & Deck",
    parentSlug: "painting",
    description: "Staining and painting for fences and decks. Protection and beauty.",
    commonProblems: [
      "Deck staining",
      "Fence painting",
      "Deck repaint",
      "Wood preservation",
    ],
    priceMin: 200,
    priceMax: 1500,
    priceUnit: "flat",
    relatedSlugs: ["exterior-painting", "pressure-washing-exterior"],
    formFields: ["area_sqft", "description", "photos"],
  },
};