import type { SubcategoryMap } from "../types";

export const pestSubcategories: SubcategoryMap = {
  "pest-inspection": {
    slug: "pest-inspection",
    title: "Pest Inspection",
    shortTitle: "Pest Inspection",
    parentSlug: "pest",
    description:
      "Pest inspections for homes, rentals, commercial spaces, visible activity, suspected infestations, and prevention planning.",
    commonProblems: [
      "Unknown pest activity",
      "Droppings or pest trails",
      "Bites or skin irritation",
      "Noises in walls or attic",
      "Home sale or rental inspection",
    ],
    priceMin: 75,
    priceMax: 250,
    priceUnit: "flat",
    relatedSlugs: [
      "general-pest-control",
      "termite-inspection-treatment",
      "rodent-control",
    ],
    formFields: [
      "propertyType",
      "pestSigns",
      "affectedAreas",
      "inspectionReason",
      "urgency",
      "photos",
    ],
  },

  "general-pest-control": {
    slug: "general-pest-control",
    title: "General Pest Control",
    shortTitle: "Pest Control",
    parentSlug: "pest",
    description:
      "General pest control for common household pests, prevention treatments, recurring service, and indoor or outdoor pest problems.",
    commonProblems: [
      "Recurring bugs inside",
      "Pests around entry points",
      "Garage or basement pest activity",
      "Seasonal pest increase",
      "Ongoing prevention needed",
    ],
    priceMin: 100,
    priceMax: 450,
    priceUnit: "flat",
    relatedSlugs: [
      "pest-inspection",
      "ant-extermination",
      "cockroach-extermination",
    ],
    formFields: [
      "propertyType",
      "pestType",
      "affectedAreas",
      "serviceFrequency",
      "petsOrChildren",
      "photos",
    ],
  },

  "ant-extermination": {
    slug: "ant-extermination",
    title: "Ant Extermination",
    shortTitle: "Ant Control",
    parentSlug: "pest",
    description:
      "Ant control for indoor trails, outdoor nests, kitchen activity, bathroom ants, carpenter ants, and recurring ant problems.",
    commonProblems: [
      "Ant trails in kitchen",
      "Ants near windows or doors",
      "Outdoor ant mounds",
      "Carpenter ant concern",
      "Recurring ants after cleaning",
    ],
    priceMin: 125,
    priceMax: 500,
    priceUnit: "flat",
    relatedSlugs: [
      "general-pest-control",
      "pest-inspection",
      "termite-inspection-treatment",
    ],
    formFields: [
      "antLocation",
      "antTypeIfKnown",
      "indoorOutdoor",
      "recurringIssue",
      "petsOrChildren",
      "photos",
    ],
  },

  "cockroach-extermination": {
    slug: "cockroach-extermination",
    title: "Cockroach Extermination",
    shortTitle: "Roach Control",
    parentSlug: "pest",
    description:
      "Cockroach control for kitchens, bathrooms, apartments, rental units, commercial spaces, and recurring roach activity.",
    commonProblems: [
      "Roaches in kitchen",
      "Roaches near appliances",
      "Bathroom roach activity",
      "Apartment infestation",
      "Recurring nighttime activity",
    ],
    priceMin: 150,
    priceMax: 650,
    priceUnit: "flat",
    relatedSlugs: [
      "general-pest-control",
      "pest-inspection",
      "commercial-pest-control",
    ],
    formFields: [
      "propertyType",
      "roachActivityLevel",
      "affectedRooms",
      "multiUnitBuilding",
      "sanitationConcern",
      "photos",
    ],
  },

  "rodent-control": {
    slug: "rodent-control",
    title: "Rodent Control",
    shortTitle: "Rodent Control",
    parentSlug: "pest",
    description:
      "Rodent control for mice, rats, attic activity, garage entry points, crawlspace issues, trapping, exclusion, and prevention.",
    commonProblems: [
      "Mouse or rat sightings",
      "Droppings found",
      "Scratching in walls",
      "Attic or crawlspace activity",
      "Chewed wires or insulation",
    ],
    priceMin: 175,
    priceMax: 900,
    priceUnit: "flat",
    relatedSlugs: [
      "pest-inspection",
      "wildlife-removal-exclusion",
      "general-pest-control",
    ],
    formFields: [
      "rodentType",
      "activityLocation",
      "entryPointsVisible",
      "atticOrCrawlspace",
      "damageObserved",
      "photos",
    ],
  },

  "termite-inspection-treatment": {
    slug: "termite-inspection-treatment",
    title: "Termite Inspection and Treatment",
    shortTitle: "Termite Service",
    parentSlug: "pest",
    description:
      "Termite inspections, treatment planning, visible damage review, swarm concerns, wood-destroying insect checks, and prevention.",
    commonProblems: [
      "Termite swarmers",
      "Mud tubes",
      "Soft or damaged wood",
      "Home sale inspection",
      "Preventive treatment needed",
    ],
    priceMin: 150,
    priceMax: 2500,
    priceUnit: "flat",
    relatedSlugs: [
      "pest-inspection",
      "ant-extermination",
      "general-pest-control",
    ],
    formFields: [
      "inspectionOrTreatment",
      "damageVisible",
      "affectedAreas",
      "homeSaleRelated",
      "foundationType",
      "photos",
    ],
  },

  "bed-bug-treatment": {
    slug: "bed-bug-treatment",
    title: "Bed Bug Treatment",
    shortTitle: "Bed Bug Treatment",
    parentSlug: "pest",
    description:
      "Bed bug inspections and treatment coordination for bedrooms, mattresses, apartments, hotels, rental units, and recurring bites.",
    commonProblems: [
      "Possible bed bug bites",
      "Spots on mattress",
      "Bugs near bed frame",
      "Travel-related infestation",
      "Apartment or rental unit concern",
    ],
    priceMin: 300,
    priceMax: 1800,
    priceUnit: "flat",
    relatedSlugs: [
      "pest-inspection",
      "flea-tick-treatment",
      "general-pest-control",
    ],
    formFields: [
      "roomsAffected",
      "bitesPresent",
      "bugsSeen",
      "multiUnitBuilding",
      "treatmentHistory",
      "photos",
    ],
  },

  "mosquito-control": {
    slug: "mosquito-control",
    title: "Mosquito Control",
    shortTitle: "Mosquito Control",
    parentSlug: "pest",
    description:
      "Mosquito control for yards, patios, pools, outdoor events, standing water concerns, and recurring seasonal mosquito activity.",
    commonProblems: [
      "Mosquitoes in yard",
      "Patio unusable",
      "Standing water nearby",
      "Pool area mosquitoes",
      "Outdoor event pest concern",
    ],
    priceMin: 85,
    priceMax: 400,
    priceUnit: "flat",
    relatedSlugs: [
      "general-pest-control",
      "flea-tick-treatment",
      "pest-inspection",
    ],
    formFields: [
      "yardSize",
      "standingWater",
      "serviceFrequency",
      "eventDate",
      "petsOrChildren",
      "photos",
    ],
  },

  "wasp-hornet-removal": {
    slug: "wasp-hornet-removal",
    title: "Wasp and Hornet Removal",
    shortTitle: "Wasp Removal",
    parentSlug: "pest",
    description:
      "Wasp, hornet, and yellow jacket nest removal for eaves, trees, garages, sheds, wall voids, and high-traffic outdoor areas.",
    commonProblems: [
      "Visible wasp nest",
      "Hornets near entry",
      "Yellow jackets in ground",
      "Nest near children or pets",
      "Stinging insects by doorway",
    ],
    priceMin: 150,
    priceMax: 650,
    priceUnit: "flat",
    relatedSlugs: [
      "pest-inspection",
      "general-pest-control",
      "wildlife-removal-exclusion",
    ],
    formFields: [
      "nestLocation",
      "nestHeight",
      "insectTypeIfKnown",
      "trafficArea",
      "urgentRisk",
      "photos",
    ],
  },

  "flea-tick-treatment": {
    slug: "flea-tick-treatment",
    title: "Flea and Tick Treatment",
    shortTitle: "Flea & Tick",
    parentSlug: "pest",
    description:
      "Flea and tick treatment for homes, yards, pet areas, carpets, furniture, rental units, and recurring pest activity.",
    commonProblems: [
      "Fleas inside home",
      "Ticks in yard",
      "Pet-related pest issue",
      "Bites on family members",
      "Recurring carpet activity",
    ],
    priceMin: 125,
    priceMax: 600,
    priceUnit: "flat",
    relatedSlugs: [
      "bed-bug-treatment",
      "mosquito-control",
      "general-pest-control",
    ],
    formFields: [
      "indoorOutdoor",
      "petsInHome",
      "roomsAffected",
      "yardSize",
      "recentTreatment",
      "photos",
    ],
  },

  "wildlife-removal-exclusion": {
    slug: "wildlife-removal-exclusion",
    title: "Wildlife Removal and Exclusion",
    shortTitle: "Wildlife Removal",
    parentSlug: "pest",
    description:
      "Wildlife removal and exclusion support for squirrels, raccoons, opossums, birds, attic entry points, vents, and crawlspaces.",
    commonProblems: [
      "Animal in attic",
      "Entry hole near roofline",
      "Noises at night",
      "Nesting in vent",
      "Wildlife damage around home",
    ],
    priceMin: 250,
    priceMax: 1500,
    priceUnit: "flat",
    relatedSlugs: [
      "rodent-control",
      "pest-inspection",
      "wasp-hornet-removal",
    ],
    formFields: [
      "animalTypeIfKnown",
      "activityLocation",
      "entryPointVisible",
      "atticOrCrawlspace",
      "damageObserved",
      "photos",
    ],
  },

  "commercial-pest-control": {
    slug: "commercial-pest-control",
    title: "Commercial Pest Control",
    shortTitle: "Commercial Pest",
    parentSlug: "pest",
    description:
      "Commercial pest control for offices, restaurants, retail spaces, warehouses, rental properties, and recurring prevention plans.",
    commonProblems: [
      "Pests in business space",
      "Health inspection concern",
      "Recurring commercial issue",
      "Warehouse pest activity",
      "Tenant or customer complaints",
    ],
    priceMin: 150,
    priceMax: 1200,
    priceUnit: "flat",
    relatedSlugs: [
      "general-pest-control",
      "cockroach-extermination",
      "rodent-control",
    ],
    formFields: [
      "businessType",
      "propertySize",
      "pestType",
      "serviceFrequency",
      "inspectionDeadline",
      "photos",
    ],
  },
};