import type { Subcategory } from "../types";

export const plumbingSubcategories: Record<string, Subcategory> = {
   // PLUMBING
"leak-detection-repair": {
  slug: "leak-detection-repair",
  title: "Leak Detection & Repair",
  shortTitle: "Leak Repair",
  parentSlug: "plumbing",
  description: "Find and fix water leaks — pipes, fixtures, ceilings, walls, and hidden leaks.",
  commonProblems: [
    "Dripping faucet",
    "Pipe leak under sink",
    "Hidden wall leak",
    "Water meter running",
    "Ceiling water stain",
    "Water around toilet or fixtures",
  ],
  priceMin: 100,
  priceMax: 500,
  priceUnit: "flat",
  relatedSlugs: ["pipe-repair", "plumbing-fixtures", "toilet-repair-installation"],
  formFields: ["leak_location", "symptom", "description", "photos"],
},

"plumbing-fixtures": {
  slug: "plumbing-fixtures",
  title: "Plumbing Fixtures",
  shortTitle: "Fixtures",
  parentSlug: "plumbing",
  description: "Install, repair, or replace faucets, toilets, sinks, shower heads, and bathroom or kitchen fixtures.",
  commonProblems: [
    "Faucet replacement",
    "Toilet install",
    "Shower head replacement",
    "Sink install",
    "Running toilet",
    "Loose or leaking fixture",
  ],
  priceMin: 100,
  priceMax: 450,
  priceUnit: "flat",
  relatedSlugs: ["leak-detection-repair", "toilet-repair-installation", "garbage-disposal-plumbing"],
  formFields: ["fixture_type", "description", "photos"],
},

"drain-cleaning": {
  slug: "drain-cleaning",
  title: "Drain Cleaning",
  shortTitle: "Drain Cleaning",
  parentSlug: "plumbing",
  description: "Clear clogged or slow drains in sinks, tubs, showers, kitchens, bathrooms, and laundry areas.",
  commonProblems: [
    "Slow sink drain",
    "Clogged shower drain",
    "Kitchen sink clog",
    "Standing water",
    "Drain odor",
    "Recurring drain blockage",
  ],
  priceMin: 100,
  priceMax: 350,
  priceUnit: "flat",
  relatedSlugs: ["pipe-repair", "garbage-disposal", "leak-detection-repair"],
  formFields: ["drain_location", "symptom", "description", "photos"],
},

"toilet-repair-installation": {
  slug: "toilet-repair-installation",
  title: "Toilet Repair & Installation",
  shortTitle: "Toilet Repair",
  parentSlug: "plumbing",
  description: "Fix running toilets, leaks, clogs, weak flushing, loose toilets, or install a new toilet.",
  commonProblems: [
    "Running toilet",
    "Toilet leaking at base",
    "Weak flush",
    "Frequent clogging",
    "Loose toilet",
    "New toilet installation",
  ],
  priceMin: 125,
  priceMax: 500,
  priceUnit: "flat",
  relatedSlugs: ["plumbing-fixtures", "leak-detection-repair", "drain-cleaning"],
  formFields: ["toilet_issue", "description", "photos"],
},

"water-heater-repair-installation": {
  slug: "water-heater-repair-installation",
  title: "Water Heater Repair & Installation",
  shortTitle: "Water Heater",
  parentSlug: "plumbing",
  description: "Get help with no hot water, leaking water heaters, tank or tankless units, repairs, and replacements.",
  commonProblems: [
    "No hot water",
    "Water heater leaking",
    "Hot water runs out quickly",
    "Strange noise from unit",
    "Tankless water heater issue",
    "Water heater replacement",
  ],
  priceMin: 150,
  priceMax: 1800,
  priceUnit: "flat",
  relatedSlugs: ["leak-detection-repair", "pipe-repair", "plumbing-fixtures"],
  formFields: ["water_heater_type", "symptom", "description", "photos"],
},

"garbage-disposal-plumbing": {
  slug: "garbage-disposal-plumbing",
  title: "Garbage Disposal Repair & Replacement",
  shortTitle: "Garbage Disposal",
  parentSlug: "plumbing",
  description: "Repair, replace, or troubleshoot garbage disposals that are leaking, jammed, humming, or not working.",
  commonProblems: [
    "Garbage disposal humming",
    "Disposal not turning on",
    "Disposal leaking",
    "Kitchen sink not draining",
    "Bad odor",
    "Garbage disposal replacement",
  ],
  priceMin: 100,
  priceMax: 400,
  priceUnit: "flat",
  relatedSlugs: ["drain-cleaning", "plumbing-fixtures", "leak-detection-repair"],
  formFields: ["disposal_issue", "description", "photos"],
},

"pipe-repair": {
  slug: "pipe-repair",
  title: "Pipe Repair",
  shortTitle: "Pipe Repair",
  parentSlug: "plumbing",
  description: "Repair leaking, damaged, cracked, corroded, or burst pipes under sinks, in walls, ceilings, basements, and utility areas.",
  commonProblems: [
    "Pipe leak",
    "Burst pipe",
    "Corroded pipe",
    "Under-sink pipe issue",
    "Water damage near pipe",
    "Low water pressure",
  ],
  priceMin: 150,
  priceMax: 900,
  priceUnit: "flat",
  relatedSlugs: ["leak-detection-repair", "drain-cleaning", "water-heater-repair-installation"],
  formFields: ["pipe_location", "symptom", "description", "photos"],
},

"sump-pump-repair": {
  slug: "sump-pump-repair",
  title: "Sump Pump Repair & Replacement",
  shortTitle: "Sump Pump",
  parentSlug: "plumbing",
  description: "Repair, replace, or troubleshoot sump pumps, backup pumps, float switches, and basement drainage issues.",
  commonProblems: [
    "Sump pump not working",
    "Pump running constantly",
    "Water in basement",
    "Float switch issue",
    "Backup pump needed",
    "Discharge line problem",
  ],
  priceMin: 150,
  priceMax: 900,
  priceUnit: "flat",
  relatedSlugs: ["pipe-repair", "leak-detection-repair", "drain-cleaning"],
  formFields: ["sump_pump_issue", "description", "photos"],
},
};