import type { SubcategoryMap } from "../types";

export const plumbingSubcategories: SubcategoryMap = {
  "leak-detection-repair": {
    slug: "leak-detection-repair",
    title: "Leak Detection & Repair",
    shortTitle: "Leak Repair",
    parentSlug: "plumbing",
    description:
      "Find and repair visible, hidden, ceiling, wall, slab, fixture, and pipe leaks before they cause more damage.",
    commonProblems: [
      "Water stains on ceilings or walls",
      "Dripping faucets or supply lines",
      "Running water meter",
      "Moist cabinets or flooring",
      "Hidden pipe leaks",
      "Water around fixtures",
    ],
    priceMin: 125,
    priceMax: 750,
    priceUnit: "flat",
    relatedSlugs: [
      "pipe-repair-replacement",
      "faucet-sink-repair-installation",
      "toilet-repair-installation",
    ],
    formFields: ["leak_location", "symptom", "urgency", "description", "photos"],
  },

  "emergency-plumbing-repair": {
    slug: "emergency-plumbing-repair",
    title: "Emergency Plumbing Repair",
    shortTitle: "Emergency Plumbing",
    parentSlug: "plumbing",
    description:
      "Urgent plumbing help for active leaks, backups, burst pipes, overflowing toilets, and water heater problems.",
    commonProblems: [
      "Burst pipe",
      "Active water leak",
      "Overflowing toilet",
      "Sewer backup",
      "No hot water",
      "Water shutoff needed",
    ],
    priceMin: 175,
    priceMax: 1200,
    priceUnit: "flat",
    relatedSlugs: [
      "leak-detection-repair",
      "pipe-repair-replacement",
      "drain-cleaning",
    ],
    formFields: ["emergency_type", "water_shutoff_status", "description", "photos"],
  },

  "drain-cleaning": {
    slug: "drain-cleaning",
    title: "Drain Cleaning",
    shortTitle: "Drain Cleaning",
    parentSlug: "plumbing",
    description:
      "Clear clogged or slow drains in kitchens, bathrooms, tubs, showers, laundry rooms, and utility areas.",
    commonProblems: [
      "Slow sink drain",
      "Clogged shower drain",
      "Standing water",
      "Kitchen sink clog",
      "Drain odor",
      "Recurring drain backup",
    ],
    priceMin: 125,
    priceMax: 450,
    priceUnit: "flat",
    relatedSlugs: [
      "garbage-disposal-plumbing",
      "sewer-line-repair-inspection",
      "pipe-repair-replacement",
    ],
    formFields: ["drain_location", "symptom", "description", "photos"],
  },

  "sewer-line-repair-inspection": {
    slug: "sewer-line-repair-inspection",
    title: "Sewer Line Inspection & Repair",
    shortTitle: "Sewer Line",
    parentSlug: "plumbing",
    description:
      "Inspect, diagnose, and repair sewer line problems, recurring backups, main line clogs, and underground drain issues.",
    commonProblems: [
      "Multiple drains backing up",
      "Sewage smell outside or indoors",
      "Recurring main line clog",
      "Wet spots in yard",
      "Gurgling toilets",
      "Camera inspection needed",
    ],
    priceMin: 250,
    priceMax: 4500,
    priceUnit: "flat",
    relatedSlugs: [
      "drain-cleaning",
      "pipe-repair-replacement",
      "emergency-plumbing-repair",
    ],
    formFields: ["backup_location", "property_type", "description", "photos"],
  },

  "toilet-repair-installation": {
    slug: "toilet-repair-installation",
    title: "Toilet Repair & Installation",
    shortTitle: "Toilet Plumbing",
    parentSlug: "plumbing",
    description:
      "Repair running, leaking, clogged, loose, or constantly filling toilets and install new toilet units.",
    commonProblems: [
      "Running toilet",
      "Toilet not flushing",
      "Leaking toilet base",
      "Loose toilet",
      "Clogged toilet",
      "Toilet replacement",
    ],
    priceMin: 125,
    priceMax: 650,
    priceUnit: "flat",
    relatedSlugs: [
      "leak-detection-repair",
      "drain-cleaning",
      "plumbing-fixtures",
    ],
    formFields: ["toilet_issue", "fixture_count", "description", "photos"],
  },

  "water-heater-repair-installation": {
    slug: "water-heater-repair-installation",
    title: "Water Heater Repair & Installation",
    shortTitle: "Water Heater",
    parentSlug: "plumbing",
    description:
      "Repair, replace, or install standard tank water heaters for homes, rentals, and small commercial spaces.",
    commonProblems: [
      "No hot water",
      "Water heater leaking",
      "Pilot light issue",
      "Rusty water",
      "Strange noises",
      "Water heater replacement",
    ],
    priceMin: 225,
    priceMax: 2800,
    priceUnit: "flat",
    relatedSlugs: [
      "tankless-water-heater-service",
      "leak-detection-repair",
      "gas-line-plumbing",
    ],
    formFields: ["water_heater_type", "fuel_type", "issue", "description", "photos"],
  },

  "tankless-water-heater-service": {
    slug: "tankless-water-heater-service",
    title: "Tankless Water Heater Service",
    shortTitle: "Tankless Heater",
    parentSlug: "plumbing",
    description:
      "Service, flush, repair, or install tankless water heaters, including performance troubleshooting and maintenance.",
    commonProblems: [
      "Tankless unit not heating",
      "Error code on unit",
      "Low hot water flow",
      "Annual flush needed",
      "Mineral buildup",
      "Tankless installation",
    ],
    priceMin: 175,
    priceMax: 3500,
    priceUnit: "flat",
    relatedSlugs: [
      "water-heater-repair-installation",
      "gas-line-plumbing",
      "pipe-repair-replacement",
    ],
    formFields: ["unit_brand", "fuel_type", "issue", "description", "photos"],
  },

  "faucet-sink-repair-installation": {
    slug: "faucet-sink-repair-installation",
    title: "Faucet & Sink Repair Installation",
    shortTitle: "Faucets & Sinks",
    parentSlug: "plumbing",
    description:
      "Repair or install faucets, sinks, supply lines, shutoff valves, drains, and kitchen or bathroom plumbing fixtures.",
    commonProblems: [
      "Dripping faucet",
      "Low water pressure",
      "Sink leak",
      "Faucet replacement",
      "Loose fixture",
      "Shutoff valve problem",
    ],
    priceMin: 125,
    priceMax: 850,
    priceUnit: "flat",
    relatedSlugs: [
      "leak-detection-repair",
      "plumbing-fixtures",
      "garbage-disposal-plumbing",
    ],
    formFields: ["fixture_type", "room", "description", "photos"],
  },

  "shower-bathtub-plumbing": {
    slug: "shower-bathtub-plumbing",
    title: "Shower & Bathtub Plumbing",
    shortTitle: "Shower Plumbing",
    parentSlug: "plumbing",
    description:
      "Repair shower valves, tub drains, leaks, low pressure, fixture replacements, and bathroom plumbing issues.",
    commonProblems: [
      "Shower leak",
      "Tub drain clog",
      "Low shower pressure",
      "Broken shower valve",
      "Tub spout issue",
      "Fixture replacement",
    ],
    priceMin: 150,
    priceMax: 1500,
    priceUnit: "flat",
    relatedSlugs: [
      "leak-detection-repair",
      "drain-cleaning",
      "plumbing-fixtures",
    ],
    formFields: ["fixture_type", "issue", "description", "photos"],
  },

  "garbage-disposal-plumbing": {
    slug: "garbage-disposal-plumbing",
    title: "Garbage Disposal Plumbing",
    shortTitle: "Garbage Disposal",
    parentSlug: "plumbing",
    description:
      "Repair, unclog, replace, or install garbage disposals and related sink drain plumbing.",
    commonProblems: [
      "Disposal jammed",
      "Disposal leaking",
      "Unit not turning on",
      "Bad odor",
      "Sink backing up",
      "Garbage disposal replacement",
    ],
    priceMin: 125,
    priceMax: 650,
    priceUnit: "flat",
    relatedSlugs: [
      "drain-cleaning",
      "faucet-sink-repair-installation",
      "leak-detection-repair",
    ],
    formFields: ["disposal_issue", "unit_available", "description", "photos"],
  },

  "pipe-repair-replacement": {
    slug: "pipe-repair-replacement",
    title: "Pipe Repair & Replacement",
    shortTitle: "Pipe Repair",
    parentSlug: "plumbing",
    description:
      "Repair or replace damaged, leaking, corroded, frozen, cracked, or outdated water and drain pipes.",
    commonProblems: [
      "Leaking pipe",
      "Corroded pipe",
      "Burst pipe",
      "Low water pressure",
      "Pipe replacement",
      "Old plumbing lines",
    ],
    priceMin: 175,
    priceMax: 5000,
    priceUnit: "flat",
    relatedSlugs: [
      "leak-detection-repair",
      "emergency-plumbing-repair",
      "sewer-line-repair-inspection",
    ],
    formFields: ["pipe_location", "pipe_material", "symptom", "description", "photos"],
  },

  "sump-pump-repair": {
    slug: "sump-pump-repair",
    title: "Sump Pump Repair & Installation",
    shortTitle: "Sump Pump",
    parentSlug: "plumbing",
    description:
      "Repair, replace, or install sump pumps, backup pumps, float switches, discharge lines, and drainage protection.",
    commonProblems: [
      "Sump pump not running",
      "Basement water",
      "Float switch problem",
      "Backup pump needed",
      "Discharge line issue",
      "Pump replacement",
    ],
    priceMin: 175,
    priceMax: 1800,
    priceUnit: "flat",
    relatedSlugs: [
      "emergency-plumbing-repair",
      "pipe-repair-replacement",
      "leak-detection-repair",
    ],
    formFields: ["basement_status", "pump_type", "issue", "description", "photos"],
  },

  "gas-line-plumbing": {
    slug: "gas-line-plumbing",
    title: "Gas Line Plumbing",
    shortTitle: "Gas Line",
    parentSlug: "plumbing",
    description:
      "Gas line installation, repair, appliance hookup, leak concerns, and code-aware plumbing support.",
    commonProblems: [
      "Gas appliance hookup",
      "Gas line extension",
      "Suspected gas leak",
      "Outdoor grill line",
      "Water heater gas connection",
      "Gas shutoff valve issue",
    ],
    priceMin: 225,
    priceMax: 2500,
    priceUnit: "flat",
    relatedSlugs: [
      "water-heater-repair-installation",
      "tankless-water-heater-service",
      "emergency-plumbing-repair",
    ],
    formFields: ["gas_service_type", "appliance_type", "description", "photos"],
  },

  "dishwasher-refrigerator-water-line-installation": {
    slug: "dishwasher-refrigerator-water-line-installation",
    title: "Dishwasher & Refrigerator Water Line Installation",
    shortTitle: "Appliance Water Lines",
    parentSlug: "plumbing",
    description:
      "Install or repair dishwasher connections, refrigerator water lines, ice maker lines, and appliance shutoff valves.",
    commonProblems: [
      "New dishwasher hookup",
      "Refrigerator water line needed",
      "Ice maker line leak",
      "Appliance shutoff valve",
      "Dishwasher drain issue",
      "Supply line replacement",
    ],
    priceMin: 125,
    priceMax: 900,
    priceUnit: "flat",
    relatedSlugs: [
      "faucet-sink-repair-installation",
      "leak-detection-repair",
      "garbage-disposal-plumbing",
    ],
    formFields: ["appliance_type", "connection_status", "description", "photos"],
  },

  "backflow-prevention-testing": {
    slug: "backflow-prevention-testing",
    title: "Backflow Prevention Testing",
    shortTitle: "Backflow Testing",
    parentSlug: "plumbing",
    description:
      "Backflow preventer inspection, testing, repair coordination, and replacement support for residential and commercial properties.",
    commonProblems: [
      "Annual backflow test",
      "Failed backflow inspection",
      "Irrigation backflow issue",
      "Commercial compliance need",
      "Backflow valve repair",
      "Replacement required",
    ],
    priceMin: 125,
    priceMax: 1200,
    priceUnit: "flat",
    relatedSlugs: [
      "pipe-repair-replacement",
      "plumbing-fixtures",
      "commercial-plumbing-maintenance",
    ],
    formFields: ["property_type", "device_type", "deadline", "description", "photos"],
  },

  "commercial-plumbing-maintenance": {
    slug: "commercial-plumbing-maintenance",
    title: "Commercial Plumbing Maintenance",
    shortTitle: "Commercial Plumbing",
    parentSlug: "plumbing",
    description:
      "Plumbing repair, inspection, maintenance, drain service, fixture support, and urgent response for small businesses and commercial spaces.",
    commonProblems: [
      "Restroom plumbing issue",
      "Commercial drain clog",
      "Fixture replacement",
      "Preventive maintenance",
      "Tenant improvement plumbing",
      "Urgent business plumbing repair",
    ],
    priceMin: 175,
    priceMax: 5000,
    priceUnit: "flat",
    relatedSlugs: [
      "drain-cleaning",
      "backflow-prevention-testing",
      "pipe-repair-replacement",
    ],
    formFields: ["business_type", "issue", "urgency", "description", "photos"],
  },

  "plumbing-fixtures": {
    slug: "plumbing-fixtures",
    title: "Plumbing Fixtures",
    shortTitle: "Fixtures",
    parentSlug: "plumbing",
    description:
      "Install, repair, or replace faucets, toilets, sinks, shower heads, shutoff valves, and kitchen or bathroom fixtures.",
    commonProblems: [
      "Fixture replacement",
      "Loose fixture",
      "Fixture leak",
      "Low water pressure",
      "Bathroom fixture install",
      "Kitchen fixture install",
    ],
    priceMin: 125,
    priceMax: 900,
    priceUnit: "flat",
    relatedSlugs: [
      "faucet-sink-repair-installation",
      "toilet-repair-installation",
      "shower-bathtub-plumbing",
    ],
    formFields: ["fixture_type", "room", "description", "photos"],
  },
};