import type { SubcategoryMap } from "../types";

export const remodelingSubcategories: SubcategoryMap = {
  // REMODELING
  "kitchen-remodeling": {
    slug: "kitchen-remodeling",
    title: "Kitchen Remodeling",
    shortTitle: "Kitchen Remodel",
    parentSlug: "remodeling",
    description: "Full kitchen renovations — cabinets, countertops, flooring, and more.",
    commonProblems: [
      "Full kitchen remodel",
      "Cabinet replacement",
      "Countertop upgrade",
      "Layout change",
    ],
    priceMin: 5000,
    priceMax: 50000,
    priceUnit: "flat",
    relatedSlugs: ["cabinets-countertops", "backsplash-installation", "plumbing-fixtures"],
    formFields: ["kitchen_size", "scope", "description", "photos"],
  },
  "bathroom-remodeling": {
    slug: "bathroom-remodeling",
    title: "Bathroom Remodeling",
    shortTitle: "Bathroom Remodel",
    parentSlug: "remodeling",
    description: "Bathroom renovations — tile, fixtures, vanity, walk-in showers.",
    commonProblems: [
      "Full bathroom remodel",
      "Tile replacement",
      "Vanity upgrade",
      "Walk-in shower",
      "Tub-to-shower conversion",
    ],
    priceMin: 3000,
    priceMax: 30000,
    priceUnit: "flat",
    relatedSlugs: ["plumbing-fixtures", "flooring"],
    formFields: ["bathroom_size", "scope", "description", "photos"],
  },
  "basement-remodeling": {
    slug: "basement-remodeling",
    title: "Basement Remodeling",
    shortTitle: "Basement Remodel",
    parentSlug: "remodeling",
    description: "Finish or remodel your basement into livable space.",
    commonProblems: [
      "Unfinished basement",
      "Add bedroom",
      "Home office",
      "Media room",
      "Waterproofing needed",
    ],
    priceMin: 8000,
    priceMax: 60000,
    priceUnit: "flat",
    relatedSlugs: ["flooring", "lighting-electrical"],
    formFields: ["basement_sqft", "scope", "description", "photos"],
  },
  "cabinets-countertops": {
    slug: "cabinets-countertops",
    title: "Cabinets & Countertops",
    shortTitle: "Cabinets",
    parentSlug: "remodeling",
    description: "Cabinet installation, refacing, and countertop replacement.",
    commonProblems: [
      "New cabinets",
      "Cabinet refacing",
      "Countertop replacement",
      "Granite install",
      "Quartz install",
    ],
    priceMin: 1500,
    priceMax: 20000,
    priceUnit: "flat",
    relatedSlugs: ["kitchen-remodeling", "backsplash-installation"],
    formFields: ["material", "linear_ft", "description", "photos"],
  },
  "backsplash-installation": {
    slug: "backsplash-installation",
    title: "Backsplash Installation",
    shortTitle: "Backsplash",
    parentSlug: "remodeling",
    description: "Kitchen and bathroom backsplash tile installation.",
    commonProblems: [
      "New backsplash",
      "Tile replacement",
      "Subway tile",
      "Mosaic tile",
    ],
    priceMin: 400,
    priceMax: 2500,
    priceUnit: "flat",
    relatedSlugs: ["kitchen-remodeling", "cabinets-countertops"],
    formFields: ["area_sqft", "material", "description", "photos"],
  },

};