import type { SubcategoryMap } from "../types";

export const remodelingSubcategories: SubcategoryMap = {
  "kitchen-remodeling": {
    slug: "kitchen-remodeling",
    title: "Kitchen Remodeling",
    shortTitle: "Kitchen Remodel",
    parentSlug: "remodeling",
    description:
      "Kitchen remodeling for layout updates, cabinets, countertops, backsplashes, islands, lighting coordination, and full kitchen renovation planning.",
    commonProblems: [
      "Outdated kitchen",
      "Poor kitchen layout",
      "Damaged cabinets",
      "Old countertops",
      "Need more storage",
      "Kitchen remodel before selling",
    ],
    priceMin: 5000,
    priceMax: 60000,
    priceUnit: "flat",
    relatedSlugs: [
      "cabinets-countertops",
      "interior-remodeling",
      "open-concept-remodeling",
    ],
    formFields: [
      "project_scope",
      "kitchen_size",
      "current_condition",
      "materials_needed",
      "timeline",
      "description",
      "photos",
    ],
  },

  "bathroom-remodeling": {
    slug: "bathroom-remodeling",
    title: "Bathroom Remodeling",
    shortTitle: "Bathroom Remodel",
    parentSlug: "remodeling",
    description:
      "Bathroom remodeling for shower updates, tub replacement, vanities, tile, fixtures, layout changes, accessibility updates, and full bathroom renovation.",
    commonProblems: [
      "Old bathroom",
      "Leaking shower area",
      "Cracked tile",
      "Outdated vanity",
      "Small bathroom layout",
      "Bathroom remodel before listing",
    ],
    priceMin: 3500,
    priceMax: 35000,
    priceUnit: "flat",
    relatedSlugs: [
      "shower-tub-remodeling",
      "tile-backsplash-remodeling",
      "interior-remodeling",
    ],
    formFields: [
      "project_scope",
      "bathroom_type",
      "current_condition",
      "fixtures_needed",
      "timeline",
      "description",
      "photos",
    ],
  },

  "basement-remodeling": {
    slug: "basement-remodeling",
    title: "Basement Remodeling & Finishing",
    shortTitle: "Basement Remodel",
    parentSlug: "remodeling",
    description:
      "Basement remodeling and finishing for unused basements, entertainment rooms, guest suites, home offices, storage areas, and moisture-aware renovation planning.",
    commonProblems: [
      "Unfinished basement",
      "Cold basement space",
      "Poor lighting",
      "Moisture concerns",
      "Need extra living space",
      "Basement layout planning",
    ],
    priceMin: 8000,
    priceMax: 75000,
    priceUnit: "flat",
    relatedSlugs: [
      "whole-house-renovation",
      "interior-remodeling",
      "home-office-remodeling",
    ],
    formFields: [
      "basement_size",
      "project_scope",
      "moisture_concerns",
      "rooms_needed",
      "timeline",
      "description",
      "photos",
    ],
  },

  "whole-house-renovation": {
    slug: "whole-house-renovation",
    title: "Whole House Renovation",
    shortTitle: "Whole House Renovation",
    parentSlug: "remodeling",
    description:
      "Whole house renovation for major updates across kitchens, bathrooms, living areas, bedrooms, flooring coordination, layout changes, and phased remodel planning.",
    commonProblems: [
      "Outdated entire home",
      "Multiple rooms need remodeling",
      "Old house renovation",
      "Renovation before moving in",
      "Renovation before selling",
      "Investor property renovation",
    ],
    priceMin: 25000,
    priceMax: 250000,
    priceUnit: "flat",
    relatedSlugs: [
      "kitchen-remodeling",
      "bathroom-remodeling",
      "interior-remodeling",
    ],
    formFields: [
      "home_size",
      "project_scope",
      "rooms_included",
      "current_condition",
      "budget_range",
      "timeline",
      "description",
      "photos",
    ],
  },

  "cabinets-countertops": {
    slug: "cabinets-countertops",
    title: "Cabinets & Countertops",
    shortTitle: "Cabinets & Counters",
    parentSlug: "remodeling",
    description:
      "Cabinet and countertop remodeling for kitchens, bathrooms, laundry rooms, islands, built-ins, replacement surfaces, storage upgrades, and finish updates.",
    commonProblems: [
      "Old cabinets",
      "Damaged countertops",
      "Need more storage",
      "Kitchen island update",
      "Bathroom vanity replacement",
      "Countertop replacement",
    ],
    priceMin: 1500,
    priceMax: 30000,
    priceUnit: "flat",
    relatedSlugs: [
      "kitchen-remodeling",
      "bathroom-remodeling",
      "tile-backsplash-remodeling",
    ],
    formFields: [
      "room_type",
      "cabinet_scope",
      "countertop_material",
      "linear_feet",
      "timeline",
      "description",
      "photos",
    ],
  },

  "shower-tub-remodeling": {
    slug: "shower-tub-remodeling",
    title: "Shower & Tub Remodeling",
    shortTitle: "Shower & Tub",
    parentSlug: "remodeling",
    description:
      "Shower and tub remodeling for walk-in showers, tub-to-shower conversions, tile surrounds, glass doors, waterproofing coordination, and bathroom upgrades.",
    commonProblems: [
      "Old shower",
      "Tub-to-shower conversion",
      "Cracked shower tile",
      "Leaking shower area",
      "Need walk-in shower",
      "Outdated bathtub",
    ],
    priceMin: 2500,
    priceMax: 25000,
    priceUnit: "flat",
    relatedSlugs: [
      "bathroom-remodeling",
      "tile-backsplash-remodeling",
      "accessibility-remodeling",
    ],
    formFields: [
      "bathroom_type",
      "shower_or_tub_scope",
      "current_condition",
      "materials_needed",
      "timeline",
      "description",
      "photos",
    ],
  },

  "tile-backsplash-remodeling": {
    slug: "tile-backsplash-remodeling",
    title: "Tile & Backsplash Remodeling",
    shortTitle: "Tile & Backsplash",
    parentSlug: "remodeling",
    description:
      "Tile and backsplash remodeling for kitchens, bathrooms, showers, laundry rooms, accent walls, grout updates, and surface refresh projects.",
    commonProblems: [
      "Cracked tile",
      "Old backsplash",
      "Damaged grout",
      "Shower tile update",
      "Kitchen backsplash install",
      "Laundry room tile update",
    ],
    priceMin: 800,
    priceMax: 15000,
    priceUnit: "flat",
    relatedSlugs: [
      "kitchen-remodeling",
      "bathroom-remodeling",
      "shower-tub-remodeling",
    ],
    formFields: [
      "room_type",
      "tile_area",
      "surface_condition",
      "material_preference",
      "timeline",
      "description",
      "photos",
    ],
  },

  "interior-remodeling": {
    slug: "interior-remodeling",
    title: "Interior Remodeling",
    shortTitle: "Interior Remodel",
    parentSlug: "remodeling",
    description:
      "Interior remodeling for living rooms, bedrooms, hallways, dining rooms, entryways, trim, walls, built-ins, layouts, and general home updates.",
    commonProblems: [
      "Outdated interior",
      "Damaged walls",
      "Poor room flow",
      "Old trim or finishes",
      "Need modern updates",
      "Remodel before moving in",
    ],
    priceMin: 2500,
    priceMax: 80000,
    priceUnit: "flat",
    relatedSlugs: [
      "whole-house-renovation",
      "open-concept-remodeling",
      "living-room-remodeling",
    ],
    formFields: [
      "rooms_included",
      "project_scope",
      "current_condition",
      "finish_preferences",
      "timeline",
      "description",
      "photos",
    ],
  },

  "open-concept-remodeling": {
    slug: "open-concept-remodeling",
    title: "Open Concept Remodeling",
    shortTitle: "Open Concept",
    parentSlug: "remodeling",
    description:
      "Open concept remodeling for layout changes, wall removal planning, kitchen-to-living transitions, structural coordination, and modern interior flow.",
    commonProblems: [
      "Closed-off floor plan",
      "Kitchen feels isolated",
      "Need wall removal",
      "Poor living room flow",
      "Dark interior layout",
      "Old compartmentalized home",
    ],
    priceMin: 4000,
    priceMax: 80000,
    priceUnit: "flat",
    relatedSlugs: [
      "wall-removal-structural-remodeling",
      "kitchen-remodeling",
      "interior-remodeling",
    ],
    formFields: [
      "rooms_included",
      "wall_removal_needed",
      "structural_concerns",
      "project_scope",
      "timeline",
      "description",
      "photos",
    ],
  },

  "wall-removal-structural-remodeling": {
    slug: "wall-removal-structural-remodeling",
    title: "Wall Removal & Structural Remodeling",
    shortTitle: "Wall Removal",
    parentSlug: "remodeling",
    description:
      "Wall removal and structural remodeling for layout changes, load-bearing wall review, beam coordination, room opening, and safe renovation planning.",
    commonProblems: [
      "Need wall removed",
      "Possible load-bearing wall",
      "Open kitchen layout",
      "Structural beam needed",
      "Poor room connection",
      "DIY demolition concern",
    ],
    priceMin: 2500,
    priceMax: 50000,
    priceUnit: "flat",
    relatedSlugs: [
      "open-concept-remodeling",
      "whole-house-renovation",
      "interior-remodeling",
    ],
    formFields: [
      "wall_location",
      "wall_type",
      "structural_concerns",
      "rooms_affected",
      "timeline",
      "description",
      "photos",
    ],
  },

  "room-additions": {
    slug: "room-additions",
    title: "Room Additions",
    shortTitle: "Room Addition",
    parentSlug: "remodeling",
    description:
      "Room addition planning for bedrooms, family rooms, home offices, in-law suites, sunrooms, expanded living areas, and added square footage.",
    commonProblems: [
      "Need more living space",
      "Adding a bedroom",
      "Adding home office",
      "Expanding family room",
      "In-law suite planning",
      "Need extra square footage",
    ],
    priceMin: 20000,
    priceMax: 200000,
    priceUnit: "flat",
    relatedSlugs: [
      "home-office-remodeling",
      "whole-house-renovation",
      "garage-conversion",
    ],
    formFields: [
      "addition_type",
      "estimated_square_feet",
      "foundation_needed",
      "utilities_needed",
      "timeline",
      "description",
      "photos",
    ],
  },

  "garage-conversion": {
    slug: "garage-conversion",
    title: "Garage Conversion",
    shortTitle: "Garage Conversion",
    parentSlug: "remodeling",
    description:
      "Garage conversion remodeling for home offices, guest rooms, gyms, studios, storage upgrades, rental use, and added living space planning.",
    commonProblems: [
      "Unused garage",
      "Need home office",
      "Need guest room",
      "Garage needs insulation",
      "Convert garage to living space",
      "Need more usable square footage",
    ],
    priceMin: 8000,
    priceMax: 75000,
    priceUnit: "flat",
    relatedSlugs: [
      "room-additions",
      "home-office-remodeling",
      "interior-remodeling",
    ],
    formFields: [
      "garage_size",
      "conversion_goal",
      "insulation_needed",
      "utilities_needed",
      "timeline",
      "description",
      "photos",
    ],
  },

  "attic-remodeling": {
    slug: "attic-remodeling",
    title: "Attic Remodeling",
    shortTitle: "Attic Remodel",
    parentSlug: "remodeling",
    description:
      "Attic remodeling for storage upgrades, loft spaces, bedrooms, offices, insulation coordination, access improvements, and usable space conversion.",
    commonProblems: [
      "Unused attic",
      "Need storage space",
      "Attic access issue",
      "Poor insulation",
      "Convert attic to room",
      "Need more home office space",
    ],
    priceMin: 5000,
    priceMax: 70000,
    priceUnit: "flat",
    relatedSlugs: [
      "home-office-remodeling",
      "room-additions",
      "interior-remodeling",
    ],
    formFields: [
      "attic_size",
      "conversion_goal",
      "access_type",
      "insulation_needed",
      "timeline",
      "description",
      "photos",
    ],
  },

  "home-office-remodeling": {
    slug: "home-office-remodeling",
    title: "Home Office Remodeling",
    shortTitle: "Home Office",
    parentSlug: "remodeling",
    description:
      "Home office remodeling for remote work rooms, built-ins, sound control, lighting, storage, desk areas, guest-office combinations, and productivity upgrades.",
    commonProblems: [
      "Need remote work space",
      "Poor lighting",
      "No built-in storage",
      "Bedroom to office conversion",
      "Garage office conversion",
      "Need quiet workspace",
    ],
    priceMin: 1500,
    priceMax: 30000,
    priceUnit: "flat",
    relatedSlugs: [
      "garage-conversion",
      "attic-remodeling",
      "interior-remodeling",
    ],
    formFields: [
      "room_type",
      "office_goal",
      "built_ins_needed",
      "lighting_needs",
      "timeline",
      "description",
      "photos",
    ],
  },

  "living-room-remodeling": {
    slug: "living-room-remodeling",
    title: "Living Room Remodeling",
    shortTitle: "Living Room",
    parentSlug: "remodeling",
    description:
      "Living room remodeling for fireplaces, built-ins, entertainment walls, layout updates, trim, wall changes, lighting coordination, and modern interior finishes.",
    commonProblems: [
      "Outdated living room",
      "Old fireplace area",
      "Need built-ins",
      "Poor TV wall layout",
      "Dark living space",
      "Damaged walls or trim",
    ],
    priceMin: 2000,
    priceMax: 50000,
    priceUnit: "flat",
    relatedSlugs: [
      "interior-remodeling",
      "open-concept-remodeling",
      "wall-removal-structural-remodeling",
    ],
    formFields: [
      "room_size",
      "project_scope",
      "fireplace_or_builtins",
      "finish_preferences",
      "timeline",
      "description",
      "photos",
    ],
  },

  "laundry-room-remodeling": {
    slug: "laundry-room-remodeling",
    title: "Laundry Room Remodeling",
    shortTitle: "Laundry Room",
    parentSlug: "remodeling",
    description:
      "Laundry room remodeling for cabinets, counters, storage, sinks, utility layouts, tile, appliance space planning, and compact room improvements.",
    commonProblems: [
      "No laundry storage",
      "Poor laundry layout",
      "Need utility sink",
      "Old laundry room",
      "Washer dryer space issue",
      "Need cabinets or countertop",
    ],
    priceMin: 1500,
    priceMax: 25000,
    priceUnit: "flat",
    relatedSlugs: [
      "cabinets-countertops",
      "tile-backsplash-remodeling",
      "interior-remodeling",
    ],
    formFields: [
      "room_size",
      "project_scope",
      "storage_needed",
      "utility_sink_needed",
      "timeline",
      "description",
      "photos",
    ],
  },

  "accessibility-remodeling": {
    slug: "accessibility-remodeling",
    title: "Accessibility Remodeling",
    shortTitle: "Accessibility",
    parentSlug: "remodeling",
    description:
      "Accessibility remodeling for safer bathrooms, wider access, walk-in showers, grab bars, ramps, aging-in-place updates, and mobility-friendly home changes.",
    commonProblems: [
      "Need safer bathroom",
      "Walk-in shower needed",
      "Aging-in-place updates",
      "Mobility access issue",
      "Trip hazard concerns",
      "Need wider access",
    ],
    priceMin: 1200,
    priceMax: 60000,
    priceUnit: "flat",
    relatedSlugs: [
      "bathroom-remodeling",
      "shower-tub-remodeling",
      "interior-remodeling",
    ],
    formFields: [
      "accessibility_goal",
      "rooms_included",
      "mobility_needs",
      "safety_features",
      "timeline",
      "description",
      "photos",
    ],
  },

  "rental-property-remodeling": {
    slug: "rental-property-remodeling",
    title: "Rental Property Remodeling",
    shortTitle: "Rental Remodel",
    parentSlug: "remodeling",
    description:
      "Rental property remodeling for tenant turnover, durable finishes, quick refreshes, damaged interiors, investor updates, and rent-ready improvements.",
    commonProblems: [
      "Tenant damage",
      "Turnover renovation",
      "Outdated rental unit",
      "Need durable finishes",
      "Fast rent-ready remodel",
      "Investor property update",
    ],
    priceMin: 1500,
    priceMax: 75000,
    priceUnit: "flat",
    relatedSlugs: [
      "interior-remodeling",
      "kitchen-remodeling",
      "bathroom-remodeling",
    ],
    formFields: [
      "property_type",
      "turnover_timeline",
      "rooms_included",
      "damage_level",
      "budget_range",
      "description",
      "photos",
    ],
  },

  "commercial-remodeling": {
    slug: "commercial-remodeling",
    title: "Commercial Remodeling",
    shortTitle: "Commercial Remodel",
    parentSlug: "remodeling",
    description:
      "Commercial remodeling for offices, retail spaces, small business interiors, tenant improvements, buildout updates, customer areas, and back-of-house spaces.",
    commonProblems: [
      "Office needs update",
      "Retail buildout",
      "Tenant improvement",
      "Damaged commercial interior",
      "Need customer area remodel",
      "Business expansion",
    ],
    priceMin: 5000,
    priceMax: 250000,
    priceUnit: "flat",
    relatedSlugs: [
      "interior-remodeling",
      "cabinets-countertops",
      "whole-house-renovation",
    ],
    formFields: [
      "business_type",
      "project_scope",
      "square_feet",
      "work_hours_constraints",
      "timeline",
      "description",
      "photos",
    ],
  },

  "remodeling-estimate-consultation": {
    slug: "remodeling-estimate-consultation",
    title: "Remodeling Estimate & Consultation",
    shortTitle: "Remodel Estimate",
    parentSlug: "remodeling",
    description:
      "Remodeling estimate and consultation requests for project planning, budget ranges, scope review, contractor matching, and renovation next steps.",
    commonProblems: [
      "Need remodel estimate",
      "Not sure where to start",
      "Need budget guidance",
      "Planning renovation",
      "Comparing remodel options",
      "Need contractor consultation",
    ],
    priceMin: 0,
    priceMax: 500,
    priceUnit: "flat",
    relatedSlugs: [
      "whole-house-renovation",
      "kitchen-remodeling",
      "bathroom-remodeling",
    ],
    formFields: [
      "project_scope",
      "rooms_included",
      "budget_range",
      "timeline",
      "decision_stage",
      "description",
      "photos",
    ],
  },
};