import type { SubcategoryMap } from "../types";

export const remodelingSubcategories: SubcategoryMap = {
  "bathroom-remodeling": {
    slug: "bathroom-remodeling",
    title: "Bathroom Remodeling",
    shortTitle: "Bathroom Remodel",
    parentSlug: "remodeling",
    description:
      "Bathroom remodeling for layout updates, tile, vanities, showers, tubs, lighting, fixtures, and full bathroom renovation projects.",
    commonProblems: [
      "Outdated bathroom layout",
      "Old shower or tub",
      "Damaged tile or grout",
      "Poor storage",
      "Water damage",
      "Low lighting",
    ],
    priceMin: 2500,
    priceMax: 25000,
    priceUnit: "flat",
    relatedSlugs: [
      "shower-remodeling",
      "bathtub-replacement",
      "tile-installation",
      "vanity-installation",
    ],
    formFields: [
      "bathroom_type",
      "project_scope",
      "fixtures_needed",
      "tile_work",
      "plumbing_changes",
      "timeline",
    ],
  },

  "kitchen-remodeling": {
    slug: "kitchen-remodeling",
    title: "Kitchen Remodeling",
    shortTitle: "Kitchen Remodel",
    parentSlug: "remodeling",
    description:
      "Kitchen remodeling for cabinets, countertops, backsplash, flooring, lighting, layout changes, appliance spaces, and full kitchen upgrades.",
    commonProblems: [
      "Outdated cabinets",
      "Limited counter space",
      "Poor kitchen flow",
      "Old flooring",
      "Damaged backsplash",
      "Insufficient lighting",
    ],
    priceMin: 5000,
    priceMax: 60000,
    priceUnit: "flat",
    relatedSlugs: [
      "cabinet-installation",
      "countertop-installation",
      "backsplash-installation",
      "kitchen-island-installation",
    ],
    formFields: [
      "kitchen_size",
      "project_scope",
      "cabinet_work",
      "countertop_work",
      "layout_changes",
      "appliance_changes",
    ],
  },

  "basement-remodeling": {
    slug: "basement-remodeling",
    title: "Basement Remodeling",
    shortTitle: "Basement Remodel",
    parentSlug: "remodeling",
    description:
      "Basement remodeling for finishing, flooring, drywall, lighting, moisture-resistant upgrades, entertainment rooms, bedrooms, offices, and usable living space.",
    commonProblems: [
      "Unfinished basement",
      "Moisture concerns",
      "Poor lighting",
      "Exposed framing",
      "Cold flooring",
      "Unused square footage",
    ],
    priceMin: 8000,
    priceMax: 70000,
    priceUnit: "flat",
    relatedSlugs: [
      "drywall-installation",
      "flooring-installation",
      "interior-painting",
      "home-office-remodeling",
    ],
    formFields: [
      "basement_size",
      "current_condition",
      "desired_rooms",
      "moisture_issues",
      "electrical_needs",
      "timeline",
    ],
  },

  "room-additions": {
    slug: "room-additions",
    title: "Room Additions",
    shortTitle: "Room Addition",
    parentSlug: "remodeling",
    description:
      "Room addition services for expanding living space, bedrooms, offices, family rooms, attached additions, and layout extensions.",
    commonProblems: [
      "Not enough living space",
      "Need extra bedroom",
      "Growing household",
      "Remote work space needed",
      "Poor existing layout",
      "Limited storage",
    ],
    priceMin: 20000,
    priceMax: 150000,
    priceUnit: "flat",
    relatedSlugs: [
      "home-office-remodeling",
      "garage-conversion",
      "whole-home-remodeling",
      "interior-remodeling",
    ],
    formFields: [
      "addition_type",
      "approx_square_feet",
      "foundation_needed",
      "utility_changes",
      "permit_status",
      "timeline",
    ],
  },

  "garage-conversion": {
    slug: "garage-conversion",
    title: "Garage Conversion",
    shortTitle: "Garage Conversion",
    parentSlug: "remodeling",
    description:
      "Garage conversion services for turning garage space into offices, bedrooms, studios, gyms, living areas, storage rooms, or flexible usable space.",
    commonProblems: [
      "Unused garage space",
      "Need home office",
      "Need guest room",
      "Poor insulation",
      "Concrete floor",
      "No finished walls",
    ],
    priceMin: 8000,
    priceMax: 60000,
    priceUnit: "flat",
    relatedSlugs: [
      "home-office-remodeling",
      "flooring-installation",
      "drywall-installation",
      "interior-painting",
    ],
    formFields: [
      "garage_size",
      "conversion_goal",
      "insulation_needed",
      "flooring_needed",
      "hvac_needed",
      "timeline",
    ],
  },

  "whole-home-remodeling": {
    slug: "whole-home-remodeling",
    title: "Whole Home Remodeling",
    shortTitle: "Whole Home Remodel",
    parentSlug: "remodeling",
    description:
      "Whole home remodeling for major renovations, layout updates, multi-room upgrades, interior modernization, flooring, paint, kitchens, bathrooms, and finish work.",
    commonProblems: [
      "Outdated home",
      "Multiple rooms need work",
      "Poor layout",
      "Old finishes",
      "Pre-sale renovation",
      "Recent home purchase",
    ],
    priceMin: 25000,
    priceMax: 250000,
    priceUnit: "flat",
    relatedSlugs: [
      "interior-remodeling",
      "bathroom-remodeling",
      "kitchen-remodeling",
      "flooring-installation",
    ],
    formFields: [
      "home_size",
      "rooms_included",
      "project_scope",
      "layout_changes",
      "move_in_status",
      "timeline",
    ],
  },

  "interior-remodeling": {
    slug: "interior-remodeling",
    title: "Interior Remodeling",
    shortTitle: "Interior Remodel",
    parentSlug: "remodeling",
    description:
      "Interior remodeling for living rooms, bedrooms, hallways, open layouts, trim, flooring, drywall, paint, lighting, and finish upgrades.",
    commonProblems: [
      "Old interior finishes",
      "Damaged walls",
      "Poor room flow",
      "Outdated trim",
      "Dark rooms",
      "Worn flooring",
    ],
    priceMin: 2000,
    priceMax: 50000,
    priceUnit: "flat",
    relatedSlugs: [
      "drywall-installation",
      "interior-painting",
      "flooring-installation",
      "trim-molding-installation",
    ],
    formFields: [
      "rooms_included",
      "project_scope",
      "wall_work",
      "flooring_work",
      "paint_needed",
      "timeline",
    ],
  },

  "home-office-remodeling": {
    slug: "home-office-remodeling",
    title: "Home Office Remodeling",
    shortTitle: "Home Office Remodel",
    parentSlug: "remodeling",
    description:
      "Home office remodeling for dedicated workspaces, built-ins, lighting, sound control, flooring, paint, storage, and productivity-focused room upgrades.",
    commonProblems: [
      "No dedicated workspace",
      "Poor lighting",
      "No storage",
      "Noise issues",
      "Uncomfortable layout",
      "Visible clutter",
    ],
    priceMin: 1500,
    priceMax: 25000,
    priceUnit: "flat",
    relatedSlugs: [
      "interior-remodeling",
      "built-in-shelving",
      "interior-painting",
      "lighting-installation",
    ],
    formFields: [
      "room_size",
      "workspace_goal",
      "built_ins_needed",
      "lighting_needed",
      "sound_control_needed",
      "timeline",
    ],
  },

  "shower-remodeling": {
    slug: "shower-remodeling",
    title: "Shower Remodeling",
    shortTitle: "Shower Remodel",
    parentSlug: "remodeling",
    description:
      "Shower remodeling for walk-in showers, tile showers, glass doors, waterproofing, fixture upgrades, shower pans, niches, and modern bathroom improvements.",
    commonProblems: [
      "Old shower",
      "Leaking shower area",
      "Cracked tile",
      "Moldy grout",
      "Hard-to-clean surfaces",
      "Poor accessibility",
    ],
    priceMin: 2500,
    priceMax: 18000,
    priceUnit: "flat",
    relatedSlugs: [
      "bathroom-remodeling",
      "tile-installation",
      "bathtub-replacement",
      "plumbing-fixture-installation",
    ],
    formFields: [
      "shower_type",
      "tile_needed",
      "glass_door_needed",
      "waterproofing_needed",
      "fixture_changes",
      "timeline",
    ],
  },

  "bathtub-replacement": {
    slug: "bathtub-replacement",
    title: "Bathtub Replacement",
    shortTitle: "Tub Replacement",
    parentSlug: "remodeling",
    description:
      "Bathtub replacement for old tubs, damaged tubs, tub-to-shower conversions, alcove tubs, soaking tubs, and bathroom upgrade projects.",
    commonProblems: [
      "Cracked tub",
      "Stained tub",
      "Hard-to-step-over tub",
      "Water damage nearby",
      "Old fixtures",
      "Poor bathroom function",
    ],
    priceMin: 1200,
    priceMax: 12000,
    priceUnit: "flat",
    relatedSlugs: [
      "bathroom-remodeling",
      "shower-remodeling",
      "tile-installation",
      "plumbing-fixture-installation",
    ],
    formFields: [
      "current_tub_type",
      "replacement_type",
      "tile_repair_needed",
      "plumbing_changes",
      "accessibility_needs",
      "timeline",
    ],
  },

  "cabinet-installation": {
    slug: "cabinet-installation",
    title: "Cabinet Installation",
    shortTitle: "Cabinet Install",
    parentSlug: "remodeling",
    description:
      "Cabinet installation for kitchens, bathrooms, laundry rooms, storage areas, built-ins, cabinet replacement, hardware, and finish upgrades.",
    commonProblems: [
      "Old cabinets",
      "Poor storage",
      "Damaged cabinet boxes",
      "Loose doors",
      "Bad layout",
      "Outdated hardware",
    ],
    priceMin: 1500,
    priceMax: 25000,
    priceUnit: "flat",
    relatedSlugs: [
      "kitchen-remodeling",
      "bathroom-remodeling",
      "countertop-installation",
      "backsplash-installation",
    ],
    formFields: [
      "cabinet_location",
      "cabinet_count",
      "new_or_replacement",
      "hardware_needed",
      "demo_needed",
      "timeline",
    ],
  },

  "countertop-installation": {
    slug: "countertop-installation",
    title: "Countertop Installation",
    shortTitle: "Countertops",
    parentSlug: "remodeling",
    description:
      "Countertop installation for kitchens, bathrooms, islands, vanities, laminate, quartz, granite, butcher block, and surface replacement projects.",
    commonProblems: [
      "Damaged countertops",
      "Outdated surfaces",
      "Need more prep space",
      "Old vanity top",
      "Poor kitchen look",
      "Stained counters",
    ],
    priceMin: 1000,
    priceMax: 20000,
    priceUnit: "flat",
    relatedSlugs: [
      "kitchen-remodeling",
      "bathroom-remodeling",
      "cabinet-installation",
      "backsplash-installation",
    ],
    formFields: [
      "countertop_location",
      "material_preference",
      "approx_square_feet",
      "sink_cutout_needed",
      "demo_needed",
      "timeline",
    ],
  },

  "backsplash-installation": {
    slug: "backsplash-installation",
    title: "Backsplash Installation",
    shortTitle: "Backsplash",
    parentSlug: "remodeling",
    description:
      "Backsplash installation for kitchens, bathrooms, laundry rooms, tile backsplash, accent walls, surface prep, grout, and finish upgrades.",
    commonProblems: [
      "Outdated backsplash",
      "Damaged wall behind counter",
      "Hard-to-clean surface",
      "Kitchen needs refresh",
      "Missing backsplash",
      "Stained drywall",
    ],
    priceMin: 500,
    priceMax: 5000,
    priceUnit: "flat",
    relatedSlugs: [
      "kitchen-remodeling",
      "tile-installation",
      "countertop-installation",
      "cabinet-installation",
    ],
    formFields: [
      "backsplash_area",
      "tile_type",
      "approx_square_feet",
      "wall_prep_needed",
      "grout_preference",
      "timeline",
    ],
  },

  "tile-installation": {
    slug: "tile-installation",
    title: "Tile Installation",
    shortTitle: "Tile Install",
    parentSlug: "remodeling",
    description:
      "Tile installation for bathrooms, kitchens, showers, floors, backsplashes, laundry rooms, fireplace surrounds, and remodeling upgrades.",
    commonProblems: [
      "Cracked tile",
      "Old tile",
      "Loose grout",
      "Water-prone areas",
      "Uneven surfaces",
      "Outdated flooring",
    ],
    priceMin: 700,
    priceMax: 20000,
    priceUnit: "sqft",
    relatedSlugs: [
      "bathroom-remodeling",
      "shower-remodeling",
      "backsplash-installation",
      "flooring-installation",
    ],
    formFields: [
      "tile_location",
      "approx_square_feet",
      "tile_material",
      "demo_needed",
      "waterproofing_needed",
      "timeline",
    ],
  },

  "flooring-installation": {
    slug: "flooring-installation",
    title: "Flooring Installation",
    shortTitle: "Flooring",
    parentSlug: "remodeling",
    description:
      "Flooring installation for remodeling projects, including vinyl plank, laminate, hardwood, tile, carpet replacement, subfloor prep, and multi-room flooring upgrades.",
    commonProblems: [
      "Worn flooring",
      "Water-damaged floors",
      "Uneven floor",
      "Old carpet",
      "Outdated style",
      "Noisy or loose boards",
    ],
    priceMin: 800,
    priceMax: 30000,
    priceUnit: "sqft",
    relatedSlugs: [
      "interior-remodeling",
      "basement-remodeling",
      "tile-installation",
      "whole-home-remodeling",
    ],
    formFields: [
      "flooring_type",
      "rooms_included",
      "approx_square_feet",
      "demo_needed",
      "subfloor_issues",
      "timeline",
    ],
  },

  "drywall-installation": {
    slug: "drywall-installation",
    title: "Drywall Installation and Repair",
    shortTitle: "Drywall",
    parentSlug: "remodeling",
    description:
      "Drywall installation and repair for remodels, room additions, basement finishing, wall damage, ceiling patches, texture matching, and finish preparation.",
    commonProblems: [
      "Wall damage",
      "Unfinished walls",
      "Ceiling cracks",
      "Water-damaged drywall",
      "Room addition walls",
      "Poor texture match",
    ],
    priceMin: 300,
    priceMax: 15000,
    priceUnit: "flat",
    relatedSlugs: [
      "interior-remodeling",
      "basement-remodeling",
      "interior-painting",
      "room-additions",
    ],
    formFields: [
      "drywall_location",
      "repair_or_installation",
      "approx_square_feet",
      "texture_matching",
      "paint_needed",
      "timeline",
    ],
  },

  "trim-molding-installation": {
    slug: "trim-molding-installation",
    title: "Trim and Molding Installation",
    shortTitle: "Trim & Molding",
    parentSlug: "remodeling",
    description:
      "Trim and molding installation for baseboards, crown molding, casing, accent walls, wainscoting, door trim, window trim, and interior finish upgrades.",
    commonProblems: [
      "Missing trim",
      "Damaged baseboards",
      "Outdated molding",
      "Poor finish detail",
      "Gaps after flooring",
      "Plain interior walls",
    ],
    priceMin: 400,
    priceMax: 10000,
    priceUnit: "flat",
    relatedSlugs: [
      "interior-remodeling",
      "interior-painting",
      "flooring-installation",
      "drywall-installation",
    ],
    formFields: [
      "trim_type",
      "rooms_included",
      "linear_feet_estimate",
      "paint_or_stain",
      "old_trim_removal",
      "timeline",
    ],
  },

  "kitchen-island-installation": {
    slug: "kitchen-island-installation",
    title: "Kitchen Island Installation",
    shortTitle: "Kitchen Island",
    parentSlug: "remodeling",
    description:
      "Kitchen island installation for added storage, seating, prep space, countertop upgrades, electrical planning, and kitchen layout improvement.",
    commonProblems: [
      "Limited counter space",
      "No seating area",
      "Poor kitchen workflow",
      "Need more storage",
      "Unused center space",
      "Outdated kitchen layout",
    ],
    priceMin: 1500,
    priceMax: 25000,
    priceUnit: "flat",
    relatedSlugs: [
      "kitchen-remodeling",
      "cabinet-installation",
      "countertop-installation",
      "lighting-installation",
    ],
    formFields: [
      "island_type",
      "storage_needed",
      "seating_needed",
      "countertop_material",
      "electrical_needed",
      "timeline",
    ],
  },

  "load-bearing-wall-removal": {
    slug: "load-bearing-wall-removal",
    title: "Load-Bearing Wall Removal",
    shortTitle: "Wall Removal",
    parentSlug: "remodeling",
    description:
      "Load-bearing wall removal planning for open-concept remodels, structural support, beam installation coordination, permits, and safe layout changes.",
    commonProblems: [
      "Closed-off layout",
      "Need open kitchen",
      "Poor room flow",
      "Structural wall concerns",
      "Permit questions",
      "Ceiling support changes",
    ],
    priceMin: 3000,
    priceMax: 30000,
    priceUnit: "flat",
    relatedSlugs: [
      "interior-remodeling",
      "kitchen-remodeling",
      "whole-home-remodeling",
      "room-additions",
    ],
    formFields: [
      "wall_location",
      "wall_length",
      "structural_assessment_done",
      "permit_status",
      "beam_needed",
      "timeline",
    ],
  },
};