import type { SubcategoryMap } from "../types";

export const roofingSubcategories: SubcategoryMap = {
  "roof-repair": {
    slug: "roof-repair",
    title: "Roof Repair",
    shortTitle: "Roof Repair",
    parentSlug: "roofing",
    description:
      "Repair roof leaks, missing shingles, flashing problems, storm damage, and localized roof issues before they spread.",
    commonProblems: [
      "Missing or lifted shingles",
      "Water stains on ceilings",
      "Small roof leaks during rain",
      "Damaged flashing",
      "Granule loss",
      "Localized storm damage",
    ],
    priceMin: 250,
    priceMax: 2500,
    priceUnit: "flat",
    relatedSlugs: [
      "roof-leak-repair",
      "emergency-roof-repair",
      "shingle-roof-repair",
      "roof-inspections-maintenance",
    ],
    formFields: [
      "roofType",
      "issueDescription",
      "leakLocation",
      "roofAge",
      "numberOfStories",
      "photos",
      "urgency",
    ],
  },

  "emergency-roof-repair": {
    slug: "emergency-roof-repair",
    title: "Emergency Roof Repair",
    shortTitle: "Emergency Repair",
    parentSlug: "roofing",
    description:
      "Urgent roofing help for active leaks, storm openings, exposed decking, missing shingles, and temporary roof protection.",
    commonProblems: [
      "Active water intrusion",
      "Storm-created roof opening",
      "Exposed underlayment or decking",
      "Wind-damaged shingles",
      "Roof tarp needed",
      "Unsafe leak spread",
    ],
    priceMin: 350,
    priceMax: 3500,
    priceUnit: "flat",
    relatedSlugs: [
      "roof-leak-repair",
      "storm-damage-restoration",
      "roof-repair",
      "roof-inspections-maintenance",
    ],
    formFields: [
      "emergencyType",
      "activeLeak",
      "stormDamage",
      "roofType",
      "numberOfStories",
      "photos",
      "preferredTiming",
    ],
  },

  "roof-leak-repair": {
    slug: "roof-leak-repair",
    title: "Roof Leak Repair",
    shortTitle: "Leak Repair",
    parentSlug: "roofing",
    description:
      "Find and repair roof leaks around shingles, flashing, vents, skylights, chimneys, valleys, and roof penetrations.",
    commonProblems: [
      "Ceiling stains",
      "Dripping during rain",
      "Leaks near vents",
      "Leaks around skylights",
      "Chimney flashing leaks",
      "Difficult-to-find water entry",
    ],
    priceMin: 250,
    priceMax: 2800,
    priceUnit: "flat",
    relatedSlugs: [
      "chimney-flashing-repair",
      "skylight-leak-repair",
      "roof-vent-repair-installation",
      "roof-repair",
    ],
    formFields: [
      "leakLocation",
      "whenLeakOccurs",
      "roofType",
      "roofAge",
      "interiorDamage",
      "photos",
      "urgency",
    ],
  },

  "roof-replacement": {
    slug: "roof-replacement",
    title: "Roof Replacement",
    shortTitle: "Replacement",
    parentSlug: "roofing",
    description:
      "Replace aging, damaged, or failing roofs with new roofing materials, underlayment, flashing, ventilation, and cleanup.",
    commonProblems: [
      "Old roof near end of life",
      "Frequent recurring leaks",
      "Widespread shingle damage",
      "Storm or hail damage",
      "Decking concerns",
      "Insurance replacement review",
    ],
    priceMin: 6500,
    priceMax: 35000,
    priceUnit: "flat",
    relatedSlugs: [
      "roof-installation",
      "storm-damage-restoration",
      "roof-inspections-maintenance",
      "shingle-roof-repair",
    ],
    formFields: [
      "roofSize",
      "roofType",
      "currentMaterial",
      "desiredMaterial",
      "roofAge",
      "numberOfStories",
      "insuranceClaim",
      "photos",
    ],
  },

  "roof-installation": {
    slug: "roof-installation",
    title: "Roof Installation",
    shortTitle: "Installation",
    parentSlug: "roofing",
    description:
      "Install roofing for new builds, additions, detached structures, garages, porches, and major exterior projects.",
    commonProblems: [
      "New construction roofing",
      "Addition roof installation",
      "Garage roof installation",
      "Porch or patio roof installation",
      "Material selection",
      "Ventilation planning",
    ],
    priceMin: 4500,
    priceMax: 30000,
    priceUnit: "flat",
    relatedSlugs: [
      "roof-replacement",
      "metal-roof-installation-repair",
      "commercial-roofing",
      "roof-vent-repair-installation",
    ],
    formFields: [
      "projectType",
      "roofSize",
      "roofPitch",
      "desiredMaterial",
      "numberOfStories",
      "plansAvailable",
      "timeline",
    ],
  },

  "shingle-roof-repair": {
    slug: "shingle-roof-repair",
    title: "Shingle Roof Repair",
    shortTitle: "Shingle Repair",
    parentSlug: "roofing",
    description:
      "Repair asphalt shingle roof damage including missing shingles, lifted tabs, nail pops, ridge caps, and localized leaks.",
    commonProblems: [
      "Missing shingles",
      "Lifted shingles",
      "Cracked shingles",
      "Nail pops",
      "Ridge cap damage",
      "Granule loss",
    ],
    priceMin: 225,
    priceMax: 2200,
    priceUnit: "flat",
    relatedSlugs: [
      "roof-repair",
      "roof-leak-repair",
      "storm-damage-restoration",
      "roof-inspections-maintenance",
    ],
    formFields: [
      "shingleIssue",
      "affectedArea",
      "roofAge",
      "numberOfStories",
      "stormRelated",
      "photos",
    ],
  },

  "metal-roof-installation-repair": {
    slug: "metal-roof-installation-repair",
    title: "Metal Roof Installation & Repair",
    shortTitle: "Metal Roofing",
    parentSlug: "roofing",
    description:
      "Install, repair, and maintain metal roofing systems, including panels, seams, fasteners, flashing, and leak points.",
    commonProblems: [
      "Loose fasteners",
      "Panel seam leaks",
      "Flashing gaps",
      "Rust or coating wear",
      "Improper previous installation",
      "Metal roof expansion movement",
    ],
    priceMin: 450,
    priceMax: 45000,
    priceUnit: "flat",
    relatedSlugs: [
      "roof-installation",
      "roof-replacement",
      "roof-leak-repair",
      "commercial-roofing",
    ],
    formFields: [
      "metalRoofType",
      "repairOrInstall",
      "roofSize",
      "issueDescription",
      "numberOfStories",
      "photos",
    ],
  },

  "flat-roof-repair": {
    slug: "flat-roof-repair",
    title: "Flat Roof Repair",
    shortTitle: "Flat Roof Repair",
    parentSlug: "roofing",
    description:
      "Repair flat and low-slope roofing issues such as ponding water, membrane punctures, seam failures, and drainage problems.",
    commonProblems: [
      "Ponding water",
      "Membrane punctures",
      "Open seams",
      "Drainage issues",
      "Blistering or bubbling",
      "Leaks near roof edges",
    ],
    priceMin: 350,
    priceMax: 6000,
    priceUnit: "flat",
    relatedSlugs: [
      "commercial-roofing",
      "roof-leak-repair",
      "roof-inspections-maintenance",
      "storm-damage-restoration",
    ],
    formFields: [
      "flatRoofMaterial",
      "issueDescription",
      "roofSize",
      "drainageIssue",
      "commercialOrResidential",
      "photos",
    ],
  },

  "storm-damage-restoration": {
    slug: "storm-damage-restoration",
    title: "Storm Damage Roof Restoration",
    shortTitle: "Storm Damage",
    parentSlug: "roofing",
    description:
      "Inspect and repair roof damage caused by wind, hail, falling branches, heavy rain, and severe weather events.",
    commonProblems: [
      "Wind-lifted shingles",
      "Hail impact marks",
      "Fallen branch damage",
      "Active leaks after storm",
      "Damaged vents or flashing",
      "Insurance documentation needs",
    ],
    priceMin: 400,
    priceMax: 25000,
    priceUnit: "flat",
    relatedSlugs: [
      "emergency-roof-repair",
      "roof-repair",
      "roof-replacement",
      "roof-inspections-maintenance",
    ],
    formFields: [
      "stormType",
      "damageDate",
      "activeLeak",
      "insuranceClaim",
      "roofType",
      "photos",
      "urgency",
    ],
  },

  "gutter-installation-repair": {
    slug: "gutter-installation-repair",
    title: "Gutter Installation & Repair",
    shortTitle: "Gutters",
    parentSlug: "roofing",
    description:
      "Install, repair, replace, and adjust gutters and downspouts to move water away from the roofline and foundation.",
    commonProblems: [
      "Overflowing gutters",
      "Loose gutter sections",
      "Damaged downspouts",
      "Poor drainage",
      "Water near foundation",
      "Gutter leaks at seams",
    ],
    priceMin: 175,
    priceMax: 4500,
    priceUnit: "flat",
    relatedSlugs: [
      "soffit-fascia-repair",
      "roof-inspections-maintenance",
      "roof-repair",
      "storm-damage-restoration",
    ],
    formFields: [
      "gutterIssue",
      "linearFeet",
      "numberOfStories",
      "downspoutIssue",
      "repairOrInstall",
      "photos",
    ],
  },

  "roof-inspections-maintenance": {
    slug: "roof-inspections-maintenance",
    title: "Roof Inspections & Maintenance",
    shortTitle: "Inspections",
    parentSlug: "roofing",
    description:
      "Schedule roof inspections, maintenance checks, condition reports, minor repairs, and preventative roof care.",
    commonProblems: [
      "Annual roof check needed",
      "Home purchase inspection",
      "Post-storm roof review",
      "Maintenance before rainy season",
      "Unknown roof age",
      "Small issues before replacement",
    ],
    priceMin: 150,
    priceMax: 1200,
    priceUnit: "flat",
    relatedSlugs: [
      "roof-repair",
      "roof-replacement",
      "storm-damage-restoration",
      "gutter-installation-repair",
    ],
    formFields: [
      "inspectionReason",
      "roofType",
      "roofAge",
      "numberOfStories",
      "knownIssues",
      "photos",
    ],
  },

  "skylight-leak-repair": {
    slug: "skylight-leak-repair",
    title: "Skylight Leak Repair",
    shortTitle: "Skylight Leaks",
    parentSlug: "roofing",
    description:
      "Repair leaks around skylights caused by flashing failure, seal issues, roof wear, condensation, or storm damage.",
    commonProblems: [
      "Water around skylight frame",
      "Ceiling stains near skylight",
      "Failed skylight flashing",
      "Condensation concerns",
      "Cracked skylight seal",
      "Storm-related skylight leak",
    ],
    priceMin: 300,
    priceMax: 3500,
    priceUnit: "flat",
    relatedSlugs: [
      "roof-leak-repair",
      "chimney-flashing-repair",
      "roof-repair",
      "roof-inspections-maintenance",
    ],
    formFields: [
      "skylightType",
      "leakLocation",
      "roofType",
      "numberOfStories",
      "interiorDamage",
      "photos",
    ],
  },

  "chimney-flashing-repair": {
    slug: "chimney-flashing-repair",
    title: "Chimney Flashing Repair",
    shortTitle: "Chimney Flashing",
    parentSlug: "roofing",
    description:
      "Repair chimney flashing, counter flashing, roof-to-chimney transitions, and leak points around masonry or framed chimneys.",
    commonProblems: [
      "Leak near chimney",
      "Loose flashing",
      "Rusty flashing",
      "Separated sealant",
      "Water stains near fireplace",
      "Storm-damaged chimney area",
    ],
    priceMin: 350,
    priceMax: 3500,
    priceUnit: "flat",
    relatedSlugs: [
      "roof-leak-repair",
      "roof-repair",
      "skylight-leak-repair",
      "storm-damage-restoration",
    ],
    formFields: [
      "chimneyType",
      "leakLocation",
      "roofType",
      "flashingCondition",
      "numberOfStories",
      "photos",
    ],
  },

  "roof-vent-repair-installation": {
    slug: "roof-vent-repair-installation",
    title: "Roof Vent Repair & Installation",
    shortTitle: "Roof Vents",
    parentSlug: "roofing",
    description:
      "Repair or install roof vents, pipe boots, ridge vents, attic ventilation, and leak-prone roof penetrations.",
    commonProblems: [
      "Leaking pipe boot",
      "Damaged roof vent",
      "Poor attic ventilation",
      "Cracked vent flashing",
      "Missing vent cover",
      "Heat or moisture buildup",
    ],
    priceMin: 225,
    priceMax: 2500,
    priceUnit: "flat",
    relatedSlugs: [
      "roof-leak-repair",
      "roof-repair",
      "roof-installation",
      "roof-inspections-maintenance",
    ],
    formFields: [
      "ventType",
      "repairOrInstall",
      "roofType",
      "atticVentilationIssue",
      "numberOfStories",
      "photos",
    ],
  },

  "soffit-fascia-repair": {
    slug: "soffit-fascia-repair",
    title: "Soffit & Fascia Repair",
    shortTitle: "Soffit & Fascia",
    parentSlug: "roofing",
    description:
      "Repair damaged soffit, fascia, roof edge trim, wood rot, ventilation panels, and gutter-adjacent roofline components.",
    commonProblems: [
      "Rotten fascia boards",
      "Loose soffit panels",
      "Water damage near gutters",
      "Animal entry points",
      "Peeling roofline trim",
      "Ventilation panel damage",
    ],
    priceMin: 300,
    priceMax: 5000,
    priceUnit: "flat",
    relatedSlugs: [
      "gutter-installation-repair",
      "roof-repair",
      "roof-inspections-maintenance",
      "storm-damage-restoration",
    ],
    formFields: [
      "damagedArea",
      "materialType",
      "linearFeet",
      "gutterRelated",
      "numberOfStories",
      "photos",
    ],
  },

  "commercial-roofing": {
    slug: "commercial-roofing",
    title: "Commercial Roofing",
    shortTitle: "Commercial Roofing",
    parentSlug: "roofing",
    description:
      "Find commercial roofing pros for flat roofs, roof leaks, maintenance, repairs, replacements, and property roof inspections.",
    commonProblems: [
      "Flat roof leaks",
      "Tenant water complaints",
      "Ponding water",
      "Membrane damage",
      "Roof maintenance backlog",
      "Commercial roof replacement planning",
    ],
    priceMin: 750,
    priceMax: 75000,
    priceUnit: "flat",
    relatedSlugs: [
      "flat-roof-repair",
      "metal-roof-installation-repair",
      "roof-inspections-maintenance",
      "storm-damage-restoration",
    ],
    formFields: [
      "propertyType",
      "roofMaterial",
      "roofSize",
      "repairOrReplace",
      "accessDetails",
      "tenantImpact",
      "photos",
    ],
  },
};