import type { SubcategoryMap } from "../types";

export const roofingSubcategories: SubcategoryMap = {
  // ROOFING
  "roof-repair": {
    slug: "roof-repair",
    title: "Roof Repair",
    shortTitle: "Roof Repair",
    parentSlug: "roofing",
    description: "Fix leaks, missing shingles, storm damage, and flashing issues.",
    commonProblems: [
      "Roof leak",
      "Missing shingles",
      "Storm damage",
      "Flashing repair",
      "Sagging area",
    ],
    priceMin: 300,
    priceMax: 2500,
    priceUnit: "flat",
    relatedSlugs: ["roof-replacement", "gutter-installation-repair"],
    formFields: ["roof_type", "damage_type", "description", "photos"],
  },
  "roof-replacement": {
    slug: "roof-replacement",
    title: "Roof Replacement",
    shortTitle: "Roof Replacement",
    parentSlug: "roofing",
    description: "Full roof replacement with quality materials and warranty.",
    commonProblems: [
      "Full replacement needed",
      "Old roof 20+ years",
      "Multiple leaks",
      "Storm total loss",
    ],
    priceMin: 5000,
    priceMax: 20000,
    priceUnit: "flat",
    relatedSlugs: ["roof-repair", "storm-damage-restoration"],
    formFields: ["home_size", "roof_type", "description", "photos"],
  },
  "roof-installation": {
    slug: "roof-installation",
    title: "Roof Installation",
    shortTitle: "Roof Install",
    parentSlug: "roofing",
    description: "New construction roof installation for homes and additions.",
    commonProblems: ["New construction", "Addition roof", "Garage roof"],
    priceMin: 4000,
    priceMax: 18000,
    priceUnit: "flat",
    relatedSlugs: ["roof-replacement"],
    formFields: ["home_size", "roof_type", "description", "photos"],
  },
  "storm-damage-restoration": {
    slug: "storm-damage-restoration",
    title: "Storm Damage Restoration",
    shortTitle: "Storm Damage",
    parentSlug: "roofing",
    description: "Emergency storm damage repair — hail, wind, fallen trees.",
    commonProblems: [
      "Hail damage",
      "Wind damage",
      "Tree fell on roof",
      "Insurance claim help",
    ],
    priceMin: 500,
    priceMax: 15000,
    priceUnit: "flat",
    relatedSlugs: ["roof-repair", "roof-replacement"],
    formFields: ["damage_type", "description", "photos"],
  },
  "gutter-installation-repair": {
    slug: "gutter-installation-repair",
    title: "Gutter Installation & Repair",
    shortTitle: "Gutters",
    parentSlug: "roofing",
    description: "Install, repair, and clean gutters to protect your home.",
    commonProblems: [
      "Gutter leak",
      "Sagging gutter",
      "New gutter install",
      "Gutter cleaning",
      "Downspout repair",
    ],
    priceMin: 150,
    priceMax: 2000,
    priceUnit: "flat",
    relatedSlugs: ["roof-repair", "pressure-washing-exterior"],
    formFields: ["linear_ft", "description", "photos"],
  },
  "roof-inspections-maintenance": {
    slug: "roof-inspections-maintenance",
    title: "Roof Inspections & Maintenance",
    shortTitle: "Roof Inspection",
    parentSlug: "roofing",
    description: "Annual roof inspections and preventive maintenance.",
    commonProblems: [
      "Annual inspection",
      "Pre-purchase inspection",
      "Insurance inspection",
      "Preventive maintenance",
    ],
    priceMin: 150,
    priceMax: 500,
    priceUnit: "flat",
    relatedSlugs: ["roof-repair", "gutter-installation-repair"],
    formFields: ["home_size", "description"],
  },
};