import type { SubcategoryMap } from "../types";

export const solarSubcategories: SubcategoryMap = {
  "solar-panel-installation": {
    slug: "solar-panel-installation",
    title: "Solar Panel Installation",
    shortTitle: "Solar Installation",
    parentSlug: "solar",
    description:
      "Residential and small commercial solar panel installation planning, site assessment, roof suitability review, system sizing, and installation coordination.",
    commonProblems: [
      "High electric bills",
      "Need solar system sizing",
      "Roof suitability questions",
      "Permit and inspection coordination",
      "Panel placement planning",
      "Need local solar installers",
    ],
    priceMin: 8000,
    priceMax: 45000,
    priceUnit: "flat",
    relatedSlugs: [
      "solar-panel-replacement",
      "solar-inverter-installation",
      "solar-battery-installation",
      "solar-system-inspection",
    ],
    formFields: [
      "property_type",
      "average_electric_bill",
      "roof_type",
      "roof_age",
      "system_goal",
      "utility_provider",
      "photos",
      "preferred_timeline",
    ],
  },

  "solar-panel-repair": {
    slug: "solar-panel-repair",
    title: "Solar Panel Repair",
    shortTitle: "Solar Repair",
    parentSlug: "solar",
    description:
      "Solar panel repair for damaged panels, low production, loose wiring, inverter alerts, monitoring issues, storm damage, and system troubleshooting.",
    commonProblems: [
      "Solar system not producing",
      "Damaged solar panel",
      "Inverter error",
      "Monitoring app issue",
      "Storm or hail damage",
      "Loose wiring concern",
    ],
    priceMin: 250,
    priceMax: 2500,
    priceUnit: "flat",
    relatedSlugs: [
      "solar-system-troubleshooting",
      "solar-inverter-repair",
      "solar-system-inspection",
      "solar-panel-replacement",
    ],
    formFields: [
      "issue_type",
      "system_age",
      "panel_count",
      "inverter_type",
      "error_message",
      "roof_access",
      "photos",
      "urgent_timing",
    ],
  },

  "solar-panel-replacement": {
    slug: "solar-panel-replacement",
    title: "Solar Panel Replacement",
    shortTitle: "Panel Replacement",
    parentSlug: "solar",
    description:
      "Solar panel replacement for broken, underperforming, outdated, storm-damaged, or failed panels in residential and commercial solar systems.",
    commonProblems: [
      "Cracked solar panel",
      "Underperforming panel",
      "Storm damage",
      "Old panels need upgrade",
      "Panel mismatch concern",
      "Insurance repair project",
    ],
    priceMin: 500,
    priceMax: 6000,
    priceUnit: "flat",
    relatedSlugs: [
      "solar-panel-repair",
      "solar-system-inspection",
      "solar-panel-installation",
      "solar-system-troubleshooting",
    ],
    formFields: [
      "number_of_panels",
      "panel_brand",
      "damage_type",
      "system_age",
      "roof_access",
      "insurance_claim",
      "photos",
      "preferred_date",
    ],
  },

  "solar-inverter-installation": {
    slug: "solar-inverter-installation",
    title: "Solar Inverter Installation",
    shortTitle: "Inverter Installation",
    parentSlug: "solar",
    description:
      "Solar inverter installation and replacement for string inverters, microinverters, hybrid inverters, and battery-ready solar systems.",
    commonProblems: [
      "New inverter needed",
      "Old inverter failed",
      "Battery-ready upgrade",
      "System expansion",
      "Utility interconnection issue",
      "Monitoring setup needed",
    ],
    priceMin: 1500,
    priceMax: 9000,
    priceUnit: "flat",
    relatedSlugs: [
      "solar-inverter-repair",
      "solar-battery-installation",
      "solar-panel-installation",
      "solar-system-troubleshooting",
    ],
    formFields: [
      "inverter_type",
      "system_size",
      "current_inverter_brand",
      "battery_ready_needed",
      "utility_provider",
      "indoor_or_outdoor_location",
      "photos",
      "preferred_timeline",
    ],
  },

  "solar-inverter-repair": {
    slug: "solar-inverter-repair",
    title: "Solar Inverter Repair",
    shortTitle: "Inverter Repair",
    parentSlug: "solar",
    description:
      "Solar inverter troubleshooting and repair for error codes, failed startup, low production, communication issues, shutdowns, and monitoring alerts.",
    commonProblems: [
      "Inverter error code",
      "Inverter not turning on",
      "Low system production",
      "Wi-Fi monitoring issue",
      "Breaker tripping",
      "System shutdown",
    ],
    priceMin: 200,
    priceMax: 2500,
    priceUnit: "flat",
    relatedSlugs: [
      "solar-system-troubleshooting",
      "solar-system-inspection",
      "solar-inverter-installation",
      "solar-panel-repair",
    ],
    formFields: [
      "error_code",
      "inverter_brand",
      "system_age",
      "last_production_date",
      "breaker_issue",
      "monitoring_access",
      "photos",
      "urgent_timing",
    ],
  },

  "solar-battery-installation": {
    slug: "solar-battery-installation",
    title: "Solar Battery Installation",
    shortTitle: "Solar Battery",
    parentSlug: "solar",
    description:
      "Solar battery installation and backup power planning for home energy storage, outage protection, load backup, and solar system upgrades.",
    commonProblems: [
      "Need backup power",
      "Battery storage planning",
      "Outage protection",
      "Existing solar upgrade",
      "Load panel planning",
      "Battery-ready inverter question",
    ],
    priceMin: 7000,
    priceMax: 30000,
    priceUnit: "flat",
    relatedSlugs: [
      "solar-inverter-installation",
      "solar-panel-installation",
      "solar-system-inspection",
      "solar-system-troubleshooting",
    ],
    formFields: [
      "existing_solar",
      "backup_goals",
      "critical_loads",
      "battery_brand_preference",
      "electrical_panel_location",
      "utility_provider",
      "photos",
      "preferred_timeline",
    ],
  },

  "solar-system-inspection": {
    slug: "solar-system-inspection",
    title: "Solar System Inspection",
    shortTitle: "Solar Inspection",
    parentSlug: "solar",
    description:
      "Solar system inspection for home purchases, performance concerns, storm damage checks, maintenance reviews, and system condition reports.",
    commonProblems: [
      "Buying a home with solar",
      "Need solar condition report",
      "Storm damage concern",
      "Production seems low",
      "System maintenance review",
      "Insurance or warranty documentation",
    ],
    priceMin: 150,
    priceMax: 900,
    priceUnit: "flat",
    relatedSlugs: [
      "solar-panel-repair",
      "solar-system-troubleshooting",
      "solar-panel-replacement",
      "solar-maintenance-service",
    ],
    formFields: [
      "inspection_reason",
      "system_age",
      "panel_count",
      "roof_access",
      "monitoring_available",
      "real_estate_transaction",
      "photos",
      "preferred_date",
    ],
  },

  "solar-maintenance-service": {
    slug: "solar-maintenance-service",
    title: "Solar Maintenance Service",
    shortTitle: "Solar Maintenance",
    parentSlug: "solar",
    description:
      "Solar maintenance for visual checks, production review, panel cleaning coordination, wiring checks, inverter review, and seasonal system upkeep.",
    commonProblems: [
      "Annual solar checkup",
      "Dirty panels",
      "Production has dropped",
      "Loose or exposed wiring",
      "Inverter maintenance",
      "Need seasonal service",
    ],
    priceMin: 150,
    priceMax: 1200,
    priceUnit: "flat",
    relatedSlugs: [
      "solar-system-inspection",
      "solar-panel-cleaning",
      "solar-system-troubleshooting",
      "solar-panel-repair",
    ],
    formFields: [
      "maintenance_type",
      "system_age",
      "panel_count",
      "roof_pitch",
      "production_concern",
      "monitoring_available",
      "photos",
      "preferred_frequency",
    ],
  },

  "solar-panel-cleaning": {
    slug: "solar-panel-cleaning",
    title: "Solar Panel Cleaning",
    shortTitle: "Panel Cleaning",
    parentSlug: "solar",
    description:
      "Solar panel cleaning for dust, pollen, leaves, bird droppings, grime, and seasonal buildup that may reduce solar production.",
    commonProblems: [
      "Dirty solar panels",
      "Pollen buildup",
      "Bird droppings",
      "Tree debris",
      "Reduced production",
      "Seasonal cleaning needed",
    ],
    priceMin: 150,
    priceMax: 900,
    priceUnit: "flat",
    relatedSlugs: [
      "solar-maintenance-service",
      "solar-system-inspection",
      "solar-system-troubleshooting",
      "solar-panel-repair",
    ],
    formFields: [
      "panel_count",
      "roof_height",
      "roof_pitch",
      "buildup_type",
      "water_access",
      "last_cleaning_date",
      "photos",
      "preferred_date",
    ],
  },

  "solar-system-troubleshooting": {
    slug: "solar-system-troubleshooting",
    title: "Solar System Troubleshooting",
    shortTitle: "Solar Troubleshooting",
    parentSlug: "solar",
    description:
      "Solar troubleshooting for low production, system shutdowns, monitoring alerts, inverter faults, breaker trips, wiring issues, and performance questions.",
    commonProblems: [
      "Solar output dropped",
      "System offline",
      "Monitoring alert",
      "Breaker keeps tripping",
      "Inverter fault",
      "Unknown performance issue",
    ],
    priceMin: 200,
    priceMax: 1800,
    priceUnit: "flat",
    relatedSlugs: [
      "solar-panel-repair",
      "solar-inverter-repair",
      "solar-system-inspection",
      "solar-maintenance-service",
    ],
    formFields: [
      "problem_started",
      "system_status",
      "error_message",
      "inverter_brand",
      "monitoring_access",
      "recent_weather",
      "photos",
      "urgent_timing",
    ],
  },

  "commercial-solar-service": {
    slug: "commercial-solar-service",
    title: "Commercial Solar Service",
    shortTitle: "Commercial Solar",
    parentSlug: "solar",
    description:
      "Commercial solar service for small business systems, rooftop solar, system inspection, troubleshooting, maintenance, panel replacement, and upgrades.",
    commonProblems: [
      "Commercial solar maintenance",
      "Business solar production issue",
      "Rooftop system inspection",
      "Panel or inverter problem",
      "Need service documentation",
      "Commercial energy upgrade planning",
    ],
    priceMin: 500,
    priceMax: 25000,
    priceUnit: "flat",
    relatedSlugs: [
      "solar-panel-installation",
      "solar-system-inspection",
      "solar-maintenance-service",
      "solar-system-troubleshooting",
    ],
    formFields: [
      "business_type",
      "system_size",
      "roof_type",
      "service_needed",
      "access_requirements",
      "utility_provider",
      "photos",
      "preferred_timeline",
    ],
  },
};