import {
  closeSync,
  existsSync,
  mkdirSync,
  openSync,
  unlinkSync,
  writeFileSync,
} from "fs";
import path from "path";
import { config as loadDotenv } from "dotenv";
import {
  isAiAgentJobName,
  type AiAgentJobName,
} from "../src/lib/ai-agents/worker-jobs";
import {
  clearStaleAiAgentLock,
  getAiAgentLockPath,
} from "../src/lib/ai-agents/worker-dispatch";

type JobRunner = () => Promise<unknown>;

const envFile = process.env.FIXLY_ENV_FILE;

if (envFile) {
  loadDotenv({ path: envFile });
} else {
  loadDotenv({ path: ".env.production" });
  loadDotenv({ path: ".env.local", override: false });
}

async function main() {
  const job = process.argv[2];

  if (!job || !isAiAgentJobName(job)) {
    throw new Error(`Unknown AI agent job: ${job ?? "(missing)"}`);
  }

  const lockPath = getAiAgentLockPath(job);
  mkdirSync(path.dirname(lockPath), { recursive: true });
  clearStaleAiAgentLock(job);

  let lockFd: number | null = null;

  try {
    lockFd = openSync(lockPath, "wx");
    writeFileSync(lockFd, `${process.pid}\n${new Date().toISOString()}\n`);
  } catch {
    console.log(
      JSON.stringify({
        ok: true,
        skipped: true,
        reason: "already_running",
        job,
      })
    );
    return;
  }

  try {
    const startedAt = Date.now();
    console.log(
      JSON.stringify({
        event: "ai_agent_job_started",
        job,
        pid: process.pid,
        source: process.env.FIXLY_AI_AGENT_JOB_SOURCE ?? "cli",
        startedAt: new Date().toISOString(),
      })
    );

    const result = await getJobRunner(job)();

    console.log(
      JSON.stringify({
        event: "ai_agent_job_completed",
        job,
        durationMs: Date.now() - startedAt,
        result,
      })
    );
  } finally {
    if (lockFd !== null) {
      closeSync(lockFd);
    }

    if (existsSync(lockPath)) {
      unlinkSync(lockPath);
    }
  }
}

function getJobRunner(job: AiAgentJobName): JobRunner {
  switch (job) {
    case "auto-generate-drafts":
      return async () => {
        const { runAutoGenerateDraftsAgent } = await import(
          "../src/lib/ai-agents/auto-generate-drafts-agent"
        );
        return runAutoGenerateDraftsAgent();
      };
    case "auto-publish-generated-pages":
      return async () => {
        const { runAutoPublishGeneratedPagesAgent } = await import(
          "../src/lib/ai-agents/auto-publish-generated-pages-agent"
        );
        return runAutoPublishGeneratedPagesAgent();
      };
    case "bigquery-trends-ingest":
      return async () => {
        const { runBigQueryTrendsIngestAgent } = await import(
          "../src/lib/ai-agents/bigquery-trends-ingest-agent"
        );
        return runBigQueryTrendsIngestAgent();
      };
    case "fix-rejected-pages":
      return async () => {
        const { runFixRejectedPagesAgent } = await import(
          "../src/lib/ai-agents/fix-rejected-pages-agent"
        );
        return runFixRejectedPagesAgent();
      };
    case "generate-service-requests":
      return async () => {
        const { runServiceRequestGeneratorAgent } = await import(
          "../src/lib/ai-agents/request-generator-agent"
        );
        return runServiceRequestGeneratorAgent();
      };
    case "internal-seo-expansion":
      return async () => {
        const { runInternalSeoExpansionAgent } = await import(
          "../src/lib/ai-agents/internal-seo-expansion-agent"
        );
        return runInternalSeoExpansionAgent();
      };
    case "search-console-ingest":
      return async () => {
        const { runSearchConsoleIngestionAgent } = await import(
          "../src/lib/ai-agents/search-console-ingestion-agent"
        );
        return runSearchConsoleIngestionAgent();
      };
    case "seo-growth-orchestrator":
      return async () => {
        const { runSeoGrowthOrchestrator } = await import(
          "../src/lib/ai-agents/orchestrators/seo-growth-orchestrator"
        );
        return runSeoGrowthOrchestrator();
      };
    case "seo-opportunities":
      return async () => {
        const { runSeoOpportunityAgent } = await import(
          "../src/lib/ai-agents/seo-opportunity-agent"
        );
        return runSeoOpportunityAgent();
      };
  }
}

main().catch((error) => {
  console.error(
    JSON.stringify({
      event: "ai_agent_job_failed",
      error: error instanceof Error ? error.message : String(error),
      stack: error instanceof Error ? error.stack : undefined,
    })
  );
  process.exitCode = 1;
});
