import type { LegacyServiceRouteMap } from "./types";

export const awningsLegacyRoutes: LegacyServiceRouteMap = {
  awnings: {
    type: "category",
    categorySlug: "awnings",
    title: "Awning Services",
  },

  "awnings/retractable-awning-installation": {
    type: "subcategory",
    categorySlug: "awnings",
    subcategorySlug: "retractable-awning-installation",
    title: "Retractable Awning Installation",
  },
  "awnings/patio-awning-installation": {
    type: "subcategory",
    categorySlug: "awnings",
    subcategorySlug: "patio-awning-installation",
    title: "Patio Awning Installation",
  },
  "awnings/fixed-awning-installation": {
    type: "subcategory",
    categorySlug: "awnings",
    subcategorySlug: "fixed-awning-installation",
    title: "Fixed Awning & Canopy Installation",
  },
  "awnings/commercial-storefront-awning": {
    type: "subcategory",
    categorySlug: "awnings",
    subcategorySlug: "commercial-storefront-awning",
    title: "Commercial Storefront Awning Service",
  },
  "awnings/awning-repair": {
    type: "subcategory",
    categorySlug: "awnings",
    subcategorySlug: "awning-repair",
    title: "Awning Repair",
  },
  "awnings/awning-fabric-replacement": {
    type: "subcategory",
    categorySlug: "awnings",
    subcategorySlug: "awning-fabric-replacement",
    title: "Awning Fabric Replacement",
  },
  "awnings/awning-frame-repair": {
    type: "subcategory",
    categorySlug: "awnings",
    subcategorySlug: "awning-frame-repair",
    title: "Awning Frame Repair",
  },
  "awnings/motorized-awning-service": {
    type: "subcategory",
    categorySlug: "awnings",
    subcategorySlug: "motorized-awning-service",
    title: "Motorized Awning Service",
  },
  "awnings/awning-replacement": {
    type: "subcategory",
    categorySlug: "awnings",
    subcategorySlug: "awning-replacement",
    title: "Awning Replacement",
  },
  "awnings/awning-removal-disposal": {
    type: "subcategory",
    categorySlug: "awnings",
    subcategorySlug: "awning-removal-disposal",
    title: "Awning Removal & Disposal",
  },
  "awnings/seasonal-awning-setup-takedown": {
    type: "subcategory",
    categorySlug: "awnings",
    subcategorySlug: "seasonal-awning-setup-takedown",
    title: "Seasonal Awning Setup & Takedown",
  },
  "awnings/awning-lighting-installation": {
    type: "subcategory",
    categorySlug: "awnings",
    subcategorySlug: "awning-lighting-installation",
    title: "Awning Lighting Installation",
  },

  "retractable-awning-installation": {
    type: "subcategory",
    categorySlug: "awnings",
    subcategorySlug: "retractable-awning-installation",
    title: "Retractable Awning Installation",
  },
  "patio-awning-installation": {
    type: "subcategory",
    categorySlug: "awnings",
    subcategorySlug: "patio-awning-installation",
    title: "Patio Awning Installation",
  },
  "fixed-awning-installation": {
    type: "subcategory",
    categorySlug: "awnings",
    subcategorySlug: "fixed-awning-installation",
    title: "Fixed Awning & Canopy Installation",
  },
  "commercial-storefront-awning": {
    type: "subcategory",
    categorySlug: "awnings",
    subcategorySlug: "commercial-storefront-awning",
    title: "Commercial Storefront Awning Service",
  },
  "awning-repair": {
    type: "subcategory",
    categorySlug: "awnings",
    subcategorySlug: "awning-repair",
    title: "Awning Repair",
  },
  "awning-fabric-replacement": {
    type: "subcategory",
    categorySlug: "awnings",
    subcategorySlug: "awning-fabric-replacement",
    title: "Awning Fabric Replacement",
  },
  "awning-frame-repair": {
    type: "subcategory",
    categorySlug: "awnings",
    subcategorySlug: "awning-frame-repair",
    title: "Awning Frame Repair",
  },
  "motorized-awning-service": {
    type: "subcategory",
    categorySlug: "awnings",
    subcategorySlug: "motorized-awning-service",
    title: "Motorized Awning Service",
  },
  "awning-replacement": {
    type: "subcategory",
    categorySlug: "awnings",
    subcategorySlug: "awning-replacement",
    title: "Awning Replacement",
  },
  "awning-removal-disposal": {
    type: "subcategory",
    categorySlug: "awnings",
    subcategorySlug: "awning-removal-disposal",
    title: "Awning Removal & Disposal",
  },
  "seasonal-awning-setup-takedown": {
    type: "subcategory",
    categorySlug: "awnings",
    subcategorySlug: "seasonal-awning-setup-takedown",
    title: "Seasonal Awning Setup & Takedown",
  },
  "awning-lighting-installation": {
    type: "subcategory",
    categorySlug: "awnings",
    subcategorySlug: "awning-lighting-installation",
    title: "Awning Lighting Installation",
  },

  "awnings/retractable-installation": {
    type: "subcategory",
    categorySlug: "awnings",
    subcategorySlug: "retractable-awning-installation",
    title: "Retractable Awning Installation",
  },
  "awnings/fixed-canopy-setup": {
    type: "subcategory",
    categorySlug: "awnings",
    subcategorySlug: "fixed-awning-installation",
    title: "Fixed Awning & Canopy Installation",
  },
  "awnings/commercial-storefront": {
    type: "subcategory",
    categorySlug: "awnings",
    subcategorySlug: "commercial-storefront-awning",
    title: "Commercial Storefront Awning Service",
  },
  "awnings/removal-disposal": {
    type: "subcategory",
    categorySlug: "awnings",
    subcategorySlug: "awning-removal-disposal",
    title: "Awning Removal & Disposal",
  },
  "awnings/replacement": {
    type: "subcategory",
    categorySlug: "awnings",
    subcategorySlug: "awning-replacement",
    title: "Awning Replacement",
  },
  "awnings/seasonal-setup-takedown": {
    type: "subcategory",
    categorySlug: "awnings",
    subcategorySlug: "seasonal-awning-setup-takedown",
    title: "Seasonal Awning Setup & Takedown",
  },
  "awnings/frame-fabric-repair": {
    type: "subcategory",
    categorySlug: "awnings",
    subcategorySlug: "awning-repair",
    title: "Awning Repair",
  },
  "awnings/lighting-installation": {
    type: "subcategory",
    categorySlug: "awnings",
    subcategorySlug: "awning-lighting-installation",
    title: "Awning Lighting Installation",
  },
  "awnings/selection-assistance": {
    type: "subcategory",
    categorySlug: "awnings",
    subcategorySlug: "patio-awning-installation",
    title: "Patio Awning Installation",
  },

  "retractable-installation": {
    type: "subcategory",
    categorySlug: "awnings",
    subcategorySlug: "retractable-awning-installation",
    title: "Retractable Awning Installation",
  },
  "fixed-canopy-setup": {
    type: "subcategory",
    categorySlug: "awnings",
    subcategorySlug: "fixed-awning-installation",
    title: "Fixed Awning & Canopy Installation",
  },
  "commercial-storefront": {
    type: "subcategory",
    categorySlug: "awnings",
    subcategorySlug: "commercial-storefront-awning",
    title: "Commercial Storefront Awning Service",
  },
  "removal-disposal": {
    type: "subcategory",
    categorySlug: "awnings",
    subcategorySlug: "awning-removal-disposal",
    title: "Awning Removal & Disposal",
  },
  replacement: {
    type: "subcategory",
    categorySlug: "awnings",
    subcategorySlug: "awning-replacement",
    title: "Awning Replacement",
  },
  "seasonal-setup-takedown": {
    type: "subcategory",
    categorySlug: "awnings",
    subcategorySlug: "seasonal-awning-setup-takedown",
    title: "Seasonal Awning Setup & Takedown",
  },
  "frame-fabric-repair": {
    type: "subcategory",
    categorySlug: "awnings",
    subcategorySlug: "awning-repair",
    title: "Awning Repair",
  },
  "lighting-installation": {
    type: "subcategory",
    categorySlug: "awnings",
    subcategorySlug: "awning-lighting-installation",
    title: "Awning Lighting Installation",
  },
  "selection-assistance": {
    type: "subcategory",
    categorySlug: "awnings",
    subcategorySlug: "patio-awning-installation",
    title: "Patio Awning Installation",
  },
};