import type { Market } from "../types";

export const georgiaMarkets: Record<string, Market> = {
  atlanta: {
    slug: "atlanta-ga",
    city: "Atlanta",
    state: "GA",
    stateFull: "Georgia",
    country: "United States",
    countryCode: "us",
    region: "Atlanta metro area",
    zip: ["30301", "30302", "30303", "30304", "30305"],
    nearby: ["Lawrenceville", "Buford", "Duluth", "Suwanee", "Norcross"],
    lat: 33.749,
    lng: -84.388,
    language: "en",
    currency: "USD",
  },

buford: {
    slug: "buford-ga",
    city: "Buford",
    state: "GA",
    stateFull: "Georgia",
    country: "United States",
    countryCode: "us",
    region: "Gwinnett County",
    zip: ["30518", "30519"],
    nearby: ["Sugar Hill", "Suwanee", "Lawrenceville", "Duluth"],
    lat: 34.119,
    lng: -84.004,
    language: "en",
    currency: "USD",
  },
  lawrenceville: {
    slug: "lawrenceville-ga",
    city: "Lawrenceville",
    state: "GA",
    stateFull: "Georgia",
    country: "United States",
    countryCode: "us",
    region: "Gwinnett County",
    zip: ["30043", "30044", "30045", "30046"],
    nearby: ["Buford", "Duluth", "Suwanee", "Norcross"],
    lat: 33.956,
    lng: -83.988,
    language: "en",
    currency: "USD",
  },
  duluth: {
    slug: "duluth-ga",
    city: "Duluth",
    state: "GA",
    stateFull: "Georgia",
    country: "United States",
    countryCode: "us",
    region: "Gwinnett County",
    zip: ["30096", "30097"],
    nearby: ["Lawrenceville", "Suwanee", "Norcross", "Buford"],
    lat: 34.002,
    lng: -84.145,
    language: "en",
    currency: "USD",
  },
  suwanee: {
    slug: "suwanee-ga",
    city: "Suwanee",
    state: "GA",
    stateFull: "Georgia",
    country: "United States",
    countryCode: "us",
    region: "Gwinnett County",
    zip: ["30024"],
    nearby: ["Buford", "Duluth", "Sugar Hill", "Lawrenceville"],
    lat: 34.051,
    lng: -84.07,
    language: "en",
    currency: "USD",
  },
  norcross: {
    slug: "norcross-ga",
    city: "Norcross",
    state: "GA",
    stateFull: "Georgia",
    country: "United States",
    countryCode: "us",
    region: "Gwinnett County",
    zip: ["30071", "30093"],
    nearby: ["Duluth", "Lawrenceville", "Peachtree Corners", "Lilburn"],
    lat: 33.941,
    lng: -84.213,
    language: "en",
    currency: "USD",
  },
  "sugar-hill": {
    slug: "sugar-hill-ga",
    city: "Sugar Hill",
    state: "GA",
    stateFull: "Georgia",
    country: "United States",
    countryCode: "us",
    region: "Gwinnett County",
    zip: ["30518"],
    nearby: ["Buford", "Suwanee", "Gainesville", "Flowery Branch"],
    lat: 34.107,
    lng: -84.054,
    language: "en",
    currency: "USD",
  },
  alpharetta: {
    slug: "alpharetta-ga",
    city: "Alpharetta",
    state: "GA",
    stateFull: "Georgia",
    country: "United States",
    countryCode: "us",
    region: "Fulton County",
    zip: ["30004", "30005", "30009", "30022"],
    nearby: ["Johns Creek", "Roswell", "Milton", "Cumming"],
    lat: 34.075,
    lng: -84.294,
    language: "en",
    currency: "USD",
  },
  roswell: {
    slug: "roswell-ga",
    city: "Roswell",
    state: "GA",
    stateFull: "Georgia",
    country: "United States",
    countryCode: "us",
    region: "Fulton County",
    zip: ["30075", "30076"],
    nearby: ["Alpharetta", "Marietta", "Sandy Springs", "Milton"],
    lat: 34.023,
    lng: -84.362,
    language: "en",
    currency: "USD",
  },
  marietta: {
    slug: "marietta-ga",
    city: "Marietta",
    state: "GA",
    stateFull: "Georgia",
    country: "United States",
    countryCode: "us",
    region: "Cobb County",
    zip: ["30060", "30062", "30064", "30066", "30067", "30068"],
    nearby: ["Smyrna", "Kennesaw", "Roswell", "Acworth"],
    lat: 33.952,
    lng: -84.55,
    language: "en",
    currency: "USD",
  },

  savannah: {
    slug: "savannah-ga",
    city: "Savannah",
    state: "GA",
    stateFull: "Georgia",
    country: "United States",
    countryCode: "us",
    region: "Chatham County",
    zip: ["31401", "31404", "31405", "31406", "31407", "31419"],
    nearby: ["Pooler", "Garden City", "Richmond Hill", "Bloomingdale"],
    lat: 32.0809,
    lng: -81.0912,
    language: "en",
    currency: "USD",
  },
  augusta: {
    slug: "augusta-ga",
    city: "Augusta",
    state: "GA",
    stateFull: "Georgia",
    country: "United States",
    countryCode: "us",
    region: "Richmond County",
    zip: ["30901", "30904", "30906", "30907", "30909"],
    nearby: ["Evans", "Grovetown", "Martinez", "Hephzibah"],
    lat: 33.4735,
    lng: -82.0105,
    language: "en",
    currency: "USD",
  },
  columbus: {
    slug: "columbus-ga",
    city: "Columbus",
    state: "GA",
    stateFull: "Georgia",
    country: "United States",
    countryCode: "us",
    region: "Muscogee County",
    zip: ["31901", "31903", "31904", "31906", "31907", "31909"],
    nearby: ["Fort Moore", "Midland", "Cusseta", "Hamilton"],
    lat: 32.461,
    lng: -84.9877,
    language: "en",
    currency: "USD",
  },
  macon: {
    slug: "macon-ga",
    city: "Macon",
    state: "GA",
    stateFull: "Georgia",
    country: "United States",
    countryCode: "us",
    region: "Bibb County",
    zip: ["31201", "31204", "31206", "31210", "31216"],
    nearby: ["Warner Robins", "Byron", "Forsyth", "Gray"],
    lat: 32.8407,
    lng: -83.6324,
    language: "en",
    currency: "USD",
  },
  athens: {
    slug: "athens-ga",
    city: "Athens",
    state: "GA",
    stateFull: "Georgia",
    country: "United States",
    countryCode: "us",
    region: "Clarke County",
    zip: ["30601", "30605", "30606", "30607"],
    nearby: ["Watkinsville", "Bogart", "Winterville", "Jefferson"],
    lat: 33.9519,
    lng: -83.3576,
    language: "en",
    currency: "USD",
  },
  "sandy-springs": {
    slug: "sandy-springs-ga",
    city: "Sandy Springs",
    state: "GA",
    stateFull: "Georgia",
    country: "United States",
    countryCode: "us",
    region: "Fulton County",
    zip: ["30328", "30342", "30350"],
    nearby: ["Roswell", "Dunwoody", "Brookhaven", "Atlanta"],
    lat: 33.9304,
    lng: -84.3733,
    language: "en",
    currency: "USD",
  },
  "johns-creek": {
    slug: "johns-creek-ga",
    city: "Johns Creek",
    state: "GA",
    stateFull: "Georgia",
    country: "United States",
    countryCode: "us",
    region: "Fulton County",
    zip: ["30022", "30097"],
    nearby: ["Alpharetta", "Duluth", "Suwanee", "Roswell"],
    lat: 34.0289,
    lng: -84.1986,
    language: "en",
    currency: "USD",
  },
  "warner-robins": {
    slug: "warner-robins-ga",
    city: "Warner Robins",
    state: "GA",
    stateFull: "Georgia",
    country: "United States",
    countryCode: "us",
    region: "Houston County",
    zip: ["31088", "31093", "31098"],
    nearby: ["Macon", "Byron", "Perry", "Centerville"],
    lat: 32.613,
    lng: -83.6242,
    language: "en",
    currency: "USD",
  },
  albany: {
    slug: "albany-ga",
    city: "Albany",
    state: "GA",
    stateFull: "Georgia",
    country: "United States",
    countryCode: "us",
    region: "Dougherty County",
    zip: ["31701", "31705", "31707"],
    nearby: ["Leesburg", "Sylvester", "Dawson", "Camilla"],
    lat: 31.5785,
    lng: -84.1557,
    language: "en",
    currency: "USD",
  },
  "south-fulton": {
    slug: "south-fulton-ga",
    city: "South Fulton",
    state: "GA",
    stateFull: "Georgia",
    country: "United States",
    countryCode: "us",
    region: "Fulton County",
    zip: ["30331", "30336", "30213", "30291"],
    nearby: ["Atlanta", "College Park", "Union City", "Fairburn"],
    lat: 33.5929,
    lng: -84.5424,
    language: "en",
    currency: "USD",
  },
  "stonecrest": {
    slug: "stonecrest-ga",
    city: "Stonecrest",
    state: "GA",
    stateFull: "Georgia",
    country: "United States",
    countryCode: "us",
    region: "DeKalb County",
    zip: ["30038", "30058"],
    nearby: ["Lithonia", "Conyers", "Decatur", "Tucker"],
    lat: 33.7085,
    lng: -84.1349,
    language: "en",
    currency: "USD",
  },
  "brookhaven": {
    slug: "brookhaven-ga",
    city: "Brookhaven",
    state: "GA",
    stateFull: "Georgia",
    country: "United States",
    countryCode: "us",
    region: "DeKalb County",
    zip: ["30319", "30329", "30341"],
    nearby: ["Atlanta", "Chamblee", "Dunwoody", "Sandy Springs"],
    lat: 33.8651,
    lng: -84.3366,
    language: "en",
    currency: "USD",
  },
  "peachtree-corners": {
    slug: "peachtree-corners-ga",
    city: "Peachtree Corners",
    state: "GA",
    stateFull: "Georgia",
    country: "United States",
    countryCode: "us",
    region: "Gwinnett County",
    zip: ["30092", "30096", "30097"],
    nearby: ["Norcross", "Duluth", "Johns Creek", "Berkeley Lake"],
    lat: 33.9699,
    lng: -84.2216,
    language: "en",
    currency: "USD",
  },
  "dunwoody": {
    slug: "dunwoody-ga",
    city: "Dunwoody",
    state: "GA",
    stateFull: "Georgia",
    country: "United States",
    countryCode: "us",
    region: "DeKalb County",
    zip: ["30338", "30346", "30360"],
    nearby: ["Sandy Springs", "Brookhaven", "Chamblee", "Atlanta"],
    lat: 33.9462,
    lng: -84.3346,
    language: "en",
    currency: "USD",
  },
  "gainesville": {
    slug: "gainesville-ga",
    city: "Gainesville",
    state: "GA",
    stateFull: "Georgia",
    country: "United States",
    countryCode: "us",
    region: "Hall County",
    zip: ["30501", "30504", "30506", "30507"],
    nearby: ["Oakwood", "Flowery Branch", "Buford", "Dawsonville"],
    lat: 34.2979,
    lng: -83.8241,
    language: "en",
    currency: "USD",
  },
  "newnan": {
    slug: "newnan-ga",
    city: "Newnan",
    state: "GA",
    stateFull: "Georgia",
    country: "United States",
    countryCode: "us",
    region: "Coweta County",
    zip: ["30263", "30265"],
    nearby: ["Peachtree City", "Sharpsburg", "Senoia", "Fairburn"],
    lat: 33.3807,
    lng: -84.7997,
    language: "en",
    currency: "USD",
  },
  "valdosta": {
    slug: "valdosta-ga",
    city: "Valdosta",
    state: "GA",
    stateFull: "Georgia",
    country: "United States",
    countryCode: "us",
    region: "Lowndes County",
    zip: ["31601", "31602", "31605"],
    nearby: ["Hahira", "Lake Park", "Quitman", "Adel"],
    lat: 30.8327,
    lng: -83.2785,
    language: "en",
    currency: "USD",
  },
  "kennesaw": {
    slug: "kennesaw-ga",
    city: "Kennesaw",
    state: "GA",
    stateFull: "Georgia",
    country: "United States",
    countryCode: "us",
    region: "Cobb County",
    zip: ["30144", "30152"],
    nearby: ["Marietta", "Acworth", "Woodstock", "Smyrna"],
    lat: 34.0234,
    lng: -84.6155,
    language: "en",
    currency: "USD",
  },
  "woodstock": {
    slug: "woodstock-ga",
    city: "Woodstock",
    state: "GA",
    stateFull: "Georgia",
    country: "United States",
    countryCode: "us",
    region: "Cherokee County",
    zip: ["30188", "30189"],
    nearby: ["Canton", "Roswell", "Kennesaw", "Marietta"],
    lat: 34.1015,
    lng: -84.5194,
    language: "en",
    currency: "USD",
  },
  "smyrna": {
    slug: "smyrna-ga",
    city: "Smyrna",
    state: "GA",
    stateFull: "Georgia",
    country: "United States",
    countryCode: "us",
    region: "Cobb County",
    zip: ["30080", "30082"],
    nearby: ["Marietta", "Vinings", "Mableton", "Atlanta"],
    lat: 33.8838,
    lng: -84.5144,
    language: "en",
    currency: "USD",
  },

}