export type Category = {
  slug: string;
  title: string;
  shortTitle: string;
  description: string;
  icon: string;
  subcategories: string[];
};

export const categories: Record<string, Category> = {
  handyman: {
    slug: "handyman",
    title: "Handyman Services",
    shortTitle: "Handyman",
    description:
      "Professional handyman services for repairs, installations, furniture assembly, drywall repair, mounting, and home maintenance.",
    icon: "handyman",
    subcategories: [
      "furniture-assembly",
      "tv-mounting",
      "drywall-repair-patching",
      "door-repair-installation",
      "window-repair",
      "shelving-wall-mounting",
      "caulking-sealing",
      "fixture-hardware-installation",
      "curtain-blinds-installation",
      "picture-mirror-hanging",
      "small-carpentry-repairs",
      "general-home-repairs",
      "closet-system-installation",
      "grab-bar-installation",
      "weatherstripping-installation",
      "mailbox-installation",
      "gate-fence-hardware-repair",
      "deck-patio-minor-repairs",
      "baby-proofing-installation",
    ],
  },

  plumbing: {
    slug: "plumbing",
    title: "Plumbing Services",
    shortTitle: "Plumbing",
    description:
      "Licensed plumbers for leak repair, drain cleaning, fixture installation, toilet repair, water heaters, pipe repair, sewer lines, and emergency plumbing.",
    icon: "plumbing",
    subcategories: [
      "leak-detection-repair",
      "emergency-plumbing-repair",
      "drain-cleaning",
      "sewer-line-repair-inspection",
      "toilet-repair-installation",
      "water-heater-repair-installation",
      "tankless-water-heater-service",
      "faucet-sink-repair-installation",
      "shower-bathtub-plumbing",
      "garbage-disposal-plumbing",
      "pipe-repair-replacement",
      "sump-pump-repair",
      "gas-line-plumbing",
      "dishwasher-refrigerator-water-line-installation",
      "backflow-prevention-testing",
      "commercial-plumbing-maintenance",
      "plumbing-fixtures",
    ],
  },

  electrical: {
    slug: "electrical",
    title: "Electrical Services",
    shortTitle: "Electrical",
    description:
      "Licensed electricians for electrical repair, panel upgrades, lighting, outlets, ceiling fans, EV chargers, generators, inspections, and emergency electrical work.",
    icon: "electrical",
    subcategories: [
      "outlet-switch-repair-installation",
      "gfci-outlet-installation",
      "light-fixture-installation",
      "lighting-upgrades",
      "ceiling-fan-installation",
      "breaker-panel-repair",
      "dedicated-circuit-installation",
      "wiring-repair-troubleshooting",
      "ev-charger-installation",
      "generator-transfer-switch-installation",
      "surge-protection-installation",
      "electrical-safety-inspection",
      "smoke-detector-installation",
      "commercial-electrical-maintenance",
    ],
  },

  cleaning: {
    slug: "cleaning",
    title: "Cleaning Services",
    shortTitle: "Cleaning",
    description:
      "Professional cleaning services for regular home cleaning, deep cleaning, move-out cleaning, post-construction cleaning, rental turnover, and commercial spaces.",
    icon: "cleaning",
    subcategories: [
      "residential-cleaning",
      "deep-cleaning",
      "move-out-cleaning",
      "move-in-cleaning",
      "apartment-cleaning",
      "maid-service",
      "post-construction-cleaning",
      "office-cleaning",
      "commercial-cleaning",
      "janitorial-services",
      "airbnb-vacation-rental-cleaning",
      "carpet-cleaning",
      "upholstery-cleaning",
      "floor-cleaning",
      "tile-grout-cleaning",
      "window-cleaning",
      "gutter-cleaning",
      "exterior-pressure-washing-cleaning",
      "dryer-vent-cleaning",
      "pet-stain-odor-removal",
      "laundry-service",
      "bathroom-cleaning",
      "kitchen-cleaning",
      "garage-cleaning",
    ],
  },

  painting: {
    slug: "painting",
    title: "Painting Services",
    shortTitle: "Painting",
    description:
      "Interior and exterior painting by professional painters, including drywall repair, ceiling painting, cabinet painting, fence painting, and touch-ups.",
    icon: "painting",
    subcategories: [
      "interior-painting",
      "exterior-painting",
      "cabinet-painting",
      "wall-painting-touch-ups",
      "ceiling-painting",
      "door-trim-painting",
      "drywall-painting-texturing",
      "popcorn-ceiling-removal",
      "fence-deck-painting",
      "deck-fence-staining-sealing",
      "wallpaper-removal",
      "stucco-painting",
      "commercial-painting",
      "pressure-washing-paint-prep",
    ],
  },

  solar: {
    slug: "solar",
    title: "Solar Services",
    shortTitle: "Solar",
    description:
      "Solar panel installation, repair, replacement, inverter service, battery backup, inspections, cleaning, maintenance, and commercial solar support.",
    icon: "solar",
    subcategories: [
      "solar-panel-installation",
      "solar-panel-repair",
      "solar-panel-replacement",
      "solar-inverter-installation",
      "solar-inverter-repair",
      "solar-battery-installation",
      "solar-system-inspection",
      "solar-maintenance-service",
      "solar-panel-cleaning",
      "solar-system-troubleshooting",
      "commercial-solar-service",
    ],
  },

  "lawn-care": {
    slug: "lawn-care",
    title: "Lawn Care & Landscaping",
    shortTitle: "Lawn Care",
    description:
      "Lawn mowing, landscaping, yard cleanup, sod installation, leaf removal, hedge trimming, sprinkler repair, and seasonal outdoor maintenance.",
    icon: "lawn",
    subcategories: [
      "lawn-mowing-service",
      "lawn-maintenance-service",
      "yard-cleanup-service",
      "leaf-removal-service",
      "weed-control-service",
      "mulch-installation-service",
      "flower-bed-maintenance",
      "landscape-edging-service",
      "sod-installation-service",
      "lawn-repair-service",
      "grass-seeding-overseeding",
      "lawn-aeration-service",
      "lawn-fertilization-service",
      "brush-removal-service",
      "hedge-trimming-service",
      "small-tree-shrub-removal",
      "lawn-grading-leveling",
      "seasonal-lawn-care",
      "sprinkler-repair-service",
    ],
  },

  pool: {
    slug: "pool",
    title: "Pool Services",
    shortTitle: "Pool",
    description:
      "Pool cleaning, weekly maintenance, chemical balancing, green pool cleanup, pump repair, heater repair, leak detection, filter service, and seasonal pool care.",
    icon: "pool",
    subcategories: [
      "pool-cleaning-service",
      "weekly-pool-maintenance",
      "green-pool-cleanup",
      "pool-chemical-balancing",
      "pool-filter-cleaning",
      "pool-pump-repair",
      "pool-pump-replacement",
      "pool-heater-repair",
      "pool-heater-installation",
      "pool-leak-detection",
      "pool-plumbing-repair",
      "pool-equipment-installation",
      "pool-tile-coping-repair",
      "pool-resurfacing",
      "pool-opening-closing",
    ],
  },

  roofing: {
    slug: "roofing",
    title: "Roofing Services",
    shortTitle: "Roofing",
    description:
      "Roof installation, repair, replacement, leak repair, storm damage restoration, gutter work, inspections, and roof maintenance.",
    icon: "roofing",
    subcategories: [
      "roof-repair",
      "emergency-roof-repair",
      "roof-leak-repair",
      "roof-replacement",
      "roof-installation",
      "shingle-roof-repair",
      "metal-roof-installation-repair",
      "flat-roof-repair",
      "storm-damage-restoration",
      "gutter-installation-repair",
      "roof-inspections-maintenance",
      "skylight-leak-repair",
      "chimney-flashing-repair",
      "roof-vent-repair-installation",
      "soffit-fascia-repair",
      "commercial-roofing",
    ],
  },

  "appliance-repair-installation": {
    slug: "appliance-repair-installation",
    title: "Appliance Repair & Installation",
    shortTitle: "Appliances",
    description:
      "Expert repair and installation for washers, dryers, refrigerators, dishwashers, ovens, ranges, microwaves, garbage disposals, and appliance hookups.",
    icon: "appliances",
    subcategories: [
      "washer-dryer-repair-installation",
      "refrigerator-freezer-repair",
      "dishwasher-repair-installation",
      "oven-range-stove-repair-installation",
      "microwave-installation-repair",
      "garbage-disposal-repair-installation",
      "ice-maker-water-line-installation",
      "dryer-vent-cleaning-repair",
      "appliance-installation",
      "appliance-troubleshooting",
      "appliance-maintenance",
    ],
  },

  "pressure-washing": {
    slug: "pressure-washing",
    title: "Pressure Washing",
    shortTitle: "Pressure Washing",
    description:
      "Professional pressure washing for driveways, siding, decks, patios, sidewalks, roofs, fences, pool decks, and commercial surfaces.",
    icon: "pressure",
    subcategories: [
      "house-pressure-washing",
      "soft-wash-house-cleaning",
      "driveway-pressure-washing",
      "concrete-pressure-washing",
      "sidewalk-pressure-washing",
      "patio-pressure-washing",
      "deck-pressure-washing",
      "fence-pressure-washing",
      "roof-soft-washing",
      "gutter-brightening-cleaning",
      "pool-deck-pressure-washing",
      "commercial-pressure-washing",
      "oil-stain-pressure-washing",
    ],
  },

  "junk-removal": {
    slug: "junk-removal",
    title: "Junk Removal",
    shortTitle: "Junk Removal",
    description:
      "Fast junk removal for household junk, furniture, appliances, garage cleanouts, attic cleanouts, yard waste, construction debris, and eviction cleanouts.",
    icon: "junk",
    subcategories: [
      "household-junk-removal",
      "furniture-junk-removal",
      "mattress-disposal-service",
      "appliance-junk-hauling",
      "garage-cleanout-service",
      "attic-basement-cleanout",
      "construction-debris-removal",
      "yard-waste-removal",
      "estate-cleanout-service",
      "hot-tub-removal",
      "commercial-junk-removal",
      "dumpster-alternative-junk-removal",
    ],
  },

  awnings: {
    slug: "awnings",
    title: "Awning Services",
    shortTitle: "Awnings",
    description:
      "Awning installation, repair, replacement, fabric replacement, frame repair, motorized awning service, removal, lighting, and seasonal setup.",
    icon: "awnings",
    subcategories: [
      "retractable-awning-installation",
      "patio-awning-installation",
      "fixed-awning-installation",
      "commercial-storefront-awning",
      "awning-repair",
      "awning-fabric-replacement",
      "awning-frame-repair",
      "motorized-awning-service",
      "awning-replacement",
      "awning-removal-disposal",
      "seasonal-awning-setup-takedown",
      "awning-lighting-installation",
    ],
  },

  "fence-installation-repair-services": {
    slug: "fence-installation-repair-services",
    title: "Fence Installation & Repair",
    shortTitle: "Fencing",
    description:
      "Fence installation, repair, replacement, gates, wood fencing, vinyl fencing, chain link fencing, privacy fences, and commercial fence work.",
    icon: "fence",
    subcategories: [
      "fence-repair",
      "fence-installation",
      "privacy-fence-installation",
      "wood-fence-installation",
      "wood-fence-repair",
      "vinyl-fence-installation",
      "vinyl-fence-repair",
      "chain-link-fence-installation",
      "chain-link-fence-repair",
      "fence-post-repair",
      "gate-repair",
      "gate-installation",
      "fence-replacement",
      "fence-staining-sealing",
      "fence-maintenance",
      "commercial-fence-installation",
    ],
  },

  remodeling: {
    slug: "remodeling",
    title: "Remodeling Services",
    shortTitle: "Remodeling",
    description:
      "Kitchen, bathroom, basement, whole-house, cabinet, countertop, backsplash, flooring, and full renovation services.",
    icon: "remodeling",
    subcategories: [
      "bathroom-remodeling",
      "kitchen-remodeling",
      "basement-remodeling",
      "room-additions",
      "garage-conversion",
      "whole-home-remodeling",
      "interior-remodeling",
      "home-office-remodeling",
      "shower-remodeling",
      "bathtub-replacement",
      "cabinet-installation",
      "countertop-installation",
      "backsplash-installation",
      "tile-installation",
      "flooring-installation",
      "drywall-installation",
      "trim-molding-installation",
      "kitchen-island-installation",
      "load-bearing-wall-removal",
    ],
  },

  flooring: {
    slug: "flooring",
    title: "Flooring Services",
    shortTitle: "Flooring",
    description:
      "Flooring installation, repair, replacement, refinishing, removal, leveling, tile, hardwood, laminate, vinyl, carpet, and commercial flooring.",
    icon: "flooring",
    subcategories: [
      "flooring-installation",
      "flooring-repair",
      "lvp-flooring-installation",
      "lvp-flooring-repair",
      "laminate-flooring-installation",
      "hardwood-flooring-installation",
      "hardwood-floor-repair",
      "hardwood-floor-refinishing",
      "tile-flooring-installation",
      "tile-flooring-repair",
      "carpet-installation-replacement",
      "carpet-repair-stretching",
      "flooring-removal",
      "subfloor-repair",
      "baseboard-trim-installation",
      "flooring-inspection",
    ],
  },

  maintenance: {
    slug: "maintenance",
    title: "Maintenance Services",
    shortTitle: "Maintenance",
    description:
      "Home maintenance, rental property maintenance, seasonal upkeep, preventive checks, punch list repairs, emergency handyman help, and small commercial property maintenance.",
    icon: "maintenance",
    subcategories: [
      "home-maintenance-services",
      "seasonal-home-maintenance",
      "preventive-home-maintenance",
      "rental-property-maintenance",
      "move-in-move-out-maintenance",
      "handyman-maintenance-repairs",
      "exterior-property-maintenance",
      "gutter-cleaning-maintenance",
      "property-inspection-maintenance",
      "commercial-property-maintenance",
    ],
  },

  hvac: {
    slug: "hvac",
    title: "HVAC & Air Conditioning Services",
    shortTitle: "HVAC",
    description:
      "AC repair, heating repair, furnace service, HVAC installation, maintenance, inspections, ductwork, thermostats, emergency HVAC, and commercial HVAC service.",
    icon: "hvac",
    subcategories: [
      "hvac-repair",
      "ac-repair",
      "ac-installation-replacement",
      "furnace-repair",
      "furnace-installation-replacement",
      "heat-pump-repair-installation",
      "mini-split-installation",
      "ductwork-repair-installation",
      "thermostat-installation-repair",
      "hvac-maintenance-tune-up",
      "indoor-air-quality",
      "hvac-inspection-troubleshooting",
      "emergency-hvac-repair",
      "commercial-hvac-service",
    ],
  },

  garage: {
    slug: "garage",
    title: "Garage Door Repair & Installation",
    shortTitle: "Garage Door",
    description:
      "Garage door repair, opener installation, spring replacement, cable repair, track repair, panel replacement, installation, replacement, and maintenance.",
    icon: "garage",
    subcategories: [
      "garage-door-repair",
      "garage-door-installation",
      "garage-door-replacement",
      "garage-door-opener-repair",
      "garage-door-opener-installation",
      "garage-door-spring-replacement",
      "garage-door-cable-replacement",
      "garage-door-track-roller-repair",
      "garage-door-panel-replacement",
      "garage-door-sensor-alignment",
      "garage-storage-installation",
      "garage-shelving-installation",
      "garage-cabinet-installation",
      "overhead-garage-storage-installation",
    ],
  },

  pest: {
    slug: "pest",
    title: "Pest Control Services",
    shortTitle: "Pest Control",
    description:
      "Pest inspections, extermination, rodent control, termite service, bed bug treatment, mosquito control, wasp removal, ant control, cockroach control, and prevention.",
    icon: "pest",
    subcategories: [
      "pest-inspection",
      "general-pest-control",
      "ant-extermination",
      "cockroach-extermination",
      "rodent-control",
      "termite-inspection-treatment",
      "bed-bug-treatment",
      "mosquito-control",
      "wasp-hornet-removal",
      "flea-tick-treatment",
      "wildlife-removal-exclusion",
      "commercial-pest-control",
    ],
  },

  moving: {
    slug: "moving",
    title: "Moving Services",
    shortTitle: "Moving",
    description:
      "Local movers, apartment moving, packing, loading, unloading, furniture moving, office moves, senior moves, storage moving help, and urgent moving labor.",
    icon: "moving",
    subcategories: [
      "local-moving-service",
      "long-distance-moving-service",
      "apartment-moving-service",
      "furniture-moving-service",
      "packing-unpacking-service",
      "labor-only-moving-help",
      "loading-unloading-service",
      "office-moving-service",
      "piano-moving-service",
      "senior-moving-service",
      "moving-junk-removal",
      "storage-moving-service",
    ],
  },
};

export function getCategoryBySlug(slug: string): Category | undefined {
  return Object.values(categories).find((category) => category.slug === slug);
}

export function getAllCategorySlugs(): string[] {
  return Object.values(categories).map((category) => category.slug);
}
