/* AUTO-GENERATED FILE. DO NOT EDIT MANUALLY. */
/* Generated by _project/scripts/generate-geo-data-registry.mjs */

import type { Market } from "../types";

import marketData0 from "./au-cities.seed.json";
import marketData1 from "./ca-cities.seed.json";
import marketData2 from "./gb-cities.seed.json";
import marketData3 from "./nz-cities.seed.json";
import marketData4 from "./us-cities.seed.json";

export const generatedMarketData = [
  { countryCode: "au", markets: marketData0 },
  { countryCode: "ca", markets: marketData1 },
  { countryCode: "gb", markets: marketData2 },
  { countryCode: "nz", markets: marketData3 },
  { countryCode: "us", markets: marketData4 },
] as Array<{
  countryCode: string;
  markets: Market[];
}>;
