/* AUTO-GENERATED FILE. DO NOT EDIT MANUALLY. */
/* Generated by _project/scripts/generate-geo-data-registry.mjs */

import type { Market } from "../types";

import marketData0 from "./au-cities.seed.json";
import marketData1 from "./nz-cities.seed.json";
import marketData2 from "./us-cities.seed.json";

export const generatedMarketData = [
  { countryCode: "au", markets: marketData0 },
  { countryCode: "nz", markets: marketData1 },
  { countryCode: "us", markets: marketData2 },
] as Array<{
  countryCode: string;
  markets: Market[];
}>;
